-- Generated by scripts/build-rooms.mjs from: regions/the-wood-2.rooms
-- 42 rooms, 114 exits. Do not hand-edit — regenerate from the source text.
-- Validated: every exit resolves, every exit has a return path (or is marked one-way),
-- no duplicate ids, no orphans, every room reachable from a gate.

-- the-birch-edge: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-birch-edge', 'north', 'the-wind-shorn-edge', NULL);

-- the-holly-brake: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-holly-brake', 'north', 'the-old-coppice', NULL);

-- the-stone-pile: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-stone-pile', 'north', 'the-hornbeam-row', NULL);

-- the-lightning-split: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lightning-split', 'north', 'the-crow-roost', NULL);

-- the-ash-stand: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ash-stand', 'north', 'the-high-holly', NULL);

-- the-bramble-margin: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bramble-margin', 'south', 'the-sunken-ditch', NULL);

-- the-nettle-glade: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-nettle-glade', 'south', 'the-alder-carr', NULL);

-- the-drinking-pool: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drinking-pool', 'south', 'the-mire-edge', NULL);

-- the-badger-ground: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-badger-ground', 'south', 'the-fox-earths', NULL);

-- the-charcoal-hut: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-charcoal-hut', 'south', 'the-burnt-stand', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-wind-shorn-edge', 'door', 'The Wind-Shorn Edge', 'The wood''s northern lip, where nothing gets to grow tall. Everything here has been pruned by weather into the same crouching shape, leaning inland, and past the last of it the ground opens out grey and empty and offers you no reason to cross it.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wind-shorn-edge', 'south', 'the-birch-edge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wind-shorn-edge', 'west', 'the-old-coppice', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-old-coppice', 'door', 'The Old Coppice', 'Hazel cut to the stool on a cycle and then abandoned mid-cycle, so every stump has thrown up a dozen poles, all of them the same age and far too thick now for anything they were meant for. Walking through is a business of turning sideways.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-old-coppice', 'east', 'the-wind-shorn-edge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-old-coppice', 'south', 'the-holly-brake', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-old-coppice', 'west', 'the-hornbeam-row', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-old-coppice', 'north', 'the-spring-head', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-spring-head', 'door', 'The Spring Head', 'Water comes up out of the ground here without ceremony, filling a stone-lined basin somebody cut for it a very long time ago, and running away north through the leaf-litter. The stone is cut square and the water is very cold and very clear.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-spring-head', 'south', 'the-old-coppice', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-hornbeam-row', 'door', 'The Hornbeam Row', 'Hornbeam, planted in a line and left, their trunks fluted and grey and hard as iron — this is the wood people came to when they needed something that would not wear out. The line runs east to west and does not deviate for anything.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hornbeam-row', 'east', 'the-old-coppice', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hornbeam-row', 'south', 'the-stone-pile', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hornbeam-row', 'west', 'the-crow-roost', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-crow-roost', 'door', 'The Crow Roost', 'A stand of tall pines with the ground beneath them white and sour with droppings and nothing growing in it at all. The birds are up there in numbers, and they stop when you arrive, and they start again when they have decided about you.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-crow-roost', 'east', 'the-hornbeam-row', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-crow-roost', 'south', 'the-lightning-split', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-crow-roost', 'west', 'the-high-holly', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-crow-roost', 'north', 'the-hunters-stand', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-hunters-stand', 'door', 'The Hunter''s Stand', 'A platform of grey boards lashed into the fork of an oak, twelve feet up, with a ladder of nailed battens going to it. From up there you would be able to see over a good stretch of the canopy. The battens do not all look sound.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hunters-stand', 'south', 'the-crow-roost', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-high-holly', 'door', 'The High Holly', 'Holly grown to full tree height rather than brake, dark and heavy-crowned, standing far enough apart to walk between and close enough to close the sky. It is a good deal darker here than the hour accounts for.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-high-holly', 'east', 'the-crow-roost', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-high-holly', 'south', 'the-ash-stand', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-high-holly', 'west', 'the-north-turning', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-sunken-ditch', 'door', 'The Sunken Ditch', 'A ditch runs along the wood''s southern edge, silted to half its depth and full of last year''s leaves, with the remains of a bank on the far side. It was dug to keep deer in, or out, by somebody who owned enough of the world to care which.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sunken-ditch', 'north', 'the-bramble-margin', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sunken-ditch', 'west', 'the-alder-carr', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sunken-ditch', 'south', 'the-lime-kiln', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-lime-kiln', 'door', 'The Lime Kiln', 'A brick-lined pit with a stone arch at its foot, built into the bank and burned out long ago. The inside is still white in patches. Somebody fed this thing for weeks at a time and somebody else carried away what it made.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lime-kiln', 'north', 'the-sunken-ditch', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-alder-carr', 'door', 'The Alder Carr', 'Alder standing in standing water, their roots up out of it like knuckles, the ground between them not really ground. Every step decides for itself how far down it is going. The air is thick and still and smells of the bottom of things.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-alder-carr', 'east', 'the-sunken-ditch', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-alder-carr', 'north', 'the-nettle-glade', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-alder-carr', 'west', 'the-mire-edge', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-mire-edge', 'door', 'The Mire Edge', 'The carr gives out into open mire — flat, pale, quaking, with a skin of moss over it that will hold a bird and has no opinion about holding you. Something has been across it recently in a straight line, which is more confidence than you have.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-mire-edge', 'east', 'the-alder-carr', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-mire-edge', 'north', 'the-drinking-pool', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-mire-edge', 'west', 'the-fox-earths', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-fox-earths', 'door', 'The Fox Earths', 'Dry sandy rise out of the wet, dug through and through, holes at every angle with fans of pale spoil below them. It smells sharply of fox for twenty paces in every direction, and the smell is not old.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fox-earths', 'east', 'the-mire-edge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fox-earths', 'north', 'the-badger-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fox-earths', 'west', 'the-burnt-stand', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fox-earths', 'south', 'the-deer-fence', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-deer-fence', 'door', 'The Deer Fence', 'A line of split posts marching away east and west, most of them still standing, the wire between them long gone to rust and lying in the leaves in loops. It enclosed something once. It does not enclose anything now.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-deer-fence', 'north', 'the-fox-earths', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-burnt-stand', 'door', 'The Burnt Stand', 'Fire came through here a long while back and the trees stand dead in their own char, black and limbless and perfectly upright, with green growing up thick and fast between them. It is the lightest place in the wood and the least alive.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-burnt-stand', 'east', 'the-fox-earths', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-burnt-stand', 'north', 'the-charcoal-hut', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-burnt-stand', 'west', 'the-south-turning', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-north-turning', 'door', 'The North Turning', 'The high holly thins and the ground tilts, and there is a stretch here where the trees have arranged themselves into something that looks like an avenue for about thirty paces before admitting it isn''t. Nothing marks the end of it.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-north-turning', 'east', 'the-high-holly', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-north-turning', 'west', 'the-crooked-stand', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-south-turning', 'door', 'The South Turning', 'West of the burnt ground the green comes back all at once, and closes, and the light goes from that hard white glare to nothing much in the space of a few steps. Your eyes take a while. By the time they have, you are in it.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-south-turning', 'east', 'the-burnt-stand', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-south-turning', 'west', 'the-black-alders', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-crooked-stand', 'door', 'The Crooked Stand', 'Every trunk here came up out of the ground at an angle and then thought better of it, so the whole stand is bent the same way at the same height, like a crowd all leaning to hear something. The floor is deep in years of leaves.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-crooked-stand', 'north', 'the-white-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-crooked-stand', 'east', 'the-mast-fall', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-crooked-stand', 'south', 'the-birdless-acre', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-crooked-stand', 'west', 'the-far-hollow', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-white-ground', 'door', 'The White Ground', 'The leaf-mould gives way to a floor of pale fungus, spread flat and wide over the ground and up the base of every trunk, so that the whole stretch is the colour of old bone. It gives underfoot without any sound at all.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-white-ground', 'north', 'the-leaning-wood', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-white-ground', 'east', 'the-grey-thicket', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-white-ground', 'south', 'the-turning-leaves', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-white-ground', 'west', 'the-crooked-stand', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-leaning-wood', 'door', 'The Leaning Wood', 'Trees at every spacing and no spacing, a stretch of wood with no character to it whatever — no clearing, no water, no fall, no ruin. Just wood, going away from you in all directions to about the same distance.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-leaning-wood', 'north', 'the-mast-fall', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-leaning-wood', 'east', 'the-birdless-acre', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-leaning-wood', 'south', 'the-far-hollow', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-leaning-wood', 'west', 'the-white-ground', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-mast-fall', 'door', 'The Mast Fall', 'Beech mast lies inches deep over everything, shells and husks and the ones that never opened, a whole autumn''s worth dropped at once and gone nowhere since. It rustles at every step, loudly, and keeps rustling a moment after you stop.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-mast-fall', 'north', 'the-grey-thicket', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-mast-fall', 'east', 'the-crow-roost', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-mast-fall', 'south', 'the-crooked-stand', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-mast-fall', 'west', 'the-leaning-wood', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-grey-thicket', 'door', 'The Grey Thicket', 'Scrub grown up under a gap in the canopy and then shaded out again when the gap closed, so it is all dead — a thicket of grey brittle stems standing exactly where they grew, snapping off at the touch and not falling over.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-grey-thicket', 'north', 'the-birdless-acre', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-grey-thicket', 'east', 'the-far-hollow', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-grey-thicket', 'south', 'the-white-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-grey-thicket', 'west', 'the-mast-fall', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-birdless-acre', 'door', 'The Birdless Acre', 'An ordinary stretch of good wood — mature trees, decent spacing, light coming down in patches — with nothing in it. No birds, no small movement in the litter, no insects in the light shafts. Everything about it is right except that.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-birdless-acre', 'north', 'the-turning-leaves', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-birdless-acre', 'east', 'the-crooked-stand', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-birdless-acre', 'south', 'the-leaning-wood', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-birdless-acre', 'west', 'the-grey-thicket', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-turning-leaves', 'door', 'The Turning Leaves', 'The canopy over this stretch has gone to autumn colour while everything around it has not, and the leaves come down steadily the whole time you are standing in it, one at a time, with no wind to account for any of it.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-turning-leaves', 'north', 'the-far-hollow', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-turning-leaves', 'east', 'the-white-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-turning-leaves', 'south', 'the-first-clearing', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-turning-leaves', 'west', 'the-birdless-acre', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-far-hollow', 'door', 'The Far Hollow', 'A shallow bowl in the wood floor, wide and quite regular, with the trees growing right down into it and out the other side. Nothing is in the bottom of it. It is a long way from anywhere and there is no reason for it to be here.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-far-hollow', 'north', 'the-crooked-stand', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-far-hollow', 'east', 'the-leaning-wood', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-far-hollow', 'south', 'the-grey-thicket', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-far-hollow', 'west', 'the-turning-leaves', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-black-alders', 'door', 'The Black Alders', 'Alders standing close in wet black ground, their bark near enough to black itself, and everything below knee height gone the same colour. The water between the roots does not move and does not reflect much of anything.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-black-alders', 'north', 'the-sodden-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-black-alders', 'east', 'the-still-air', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-black-alders', 'south', 'the-drowned-roots', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-black-alders', 'west', 'the-blind-corner', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-sodden-ground', 'door', 'The Sodden Ground', 'Ground so saturated that your prints fill behind you before you have finished making the next one. There is no standing water and no dry footing either — just a wood growing out of something that has not decided which it is.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sodden-ground', 'north', 'the-reed-break', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sodden-ground', 'east', 'the-moss-floor', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sodden-ground', 'south', 'the-low-mist', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sodden-ground', 'west', 'the-black-alders', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-reed-break', 'door', 'The Reed Break', 'Reeds up over your head in a stand that has no business being inside a wood, dense and dry-rattling, with the trees continuing straight up out of the middle of them. You cannot see your own feet and you cannot see three paces.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-reed-break', 'north', 'the-still-air', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-reed-break', 'east', 'the-alder-carr', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-reed-break', 'south', 'the-blind-corner', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-reed-break', 'west', 'the-sodden-ground', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-still-air', 'door', 'The Still Air', 'The air here does not move at all. Not a leaf, not a stem, not the surface of the water lying in the hollows — and it is not that there is no wind, because you can hear wind, working the canopy somewhere not far off.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-still-air', 'north', 'the-moss-floor', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-still-air', 'east', 'the-low-mist', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-still-air', 'south', 'the-black-alders', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-still-air', 'west', 'the-reed-break', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-moss-floor', 'door', 'The Moss Floor', 'Moss has covered everything — floor, fallen wood, the lower six feet of every trunk — in one continuous green pelt a hand deep, so that the shapes underneath are only suggestions. Your feet make no sound whatsoever.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-moss-floor', 'north', 'the-drowned-roots', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-moss-floor', 'east', 'the-blind-corner', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-moss-floor', 'south', 'the-sodden-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-moss-floor', 'west', 'the-still-air', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-drowned-roots', 'door', 'The Drowned Roots', 'The water is deeper here, shin-high and cold, and the roots come up through it in arches you have to step over or duck under. Underneath the surface the bottom is a mat of roots too, going down further than a wood should need.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drowned-roots', 'north', 'the-badger-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drowned-roots', 'east', 'the-black-alders', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drowned-roots', 'south', 'the-reed-break', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drowned-roots', 'west', 'the-moss-floor', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-low-mist', 'door', 'The Low Mist', 'Mist lies flat across this stretch at about waist height, quite level, with the trunks going up through it and the canopy clear above. From here everything below your ribs is guesswork, including the ground.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-low-mist', 'north', 'the-blind-corner', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-low-mist', 'east', 'the-sodden-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-low-mist', 'south', 'the-still-air', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-low-mist', 'west', 'the-drowned-roots', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-blind-corner', 'door', 'The Blind Corner', 'The trees close into a wall on three sides — not planted, just grown that way — leaving a pocket of open floor with one obvious way in. Standing in it, you cannot see anything coming until it is already at the gap.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-blind-corner', 'north', 'the-black-alders', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-blind-corner', 'east', 'the-reed-break', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-blind-corner', 'south', 'the-moss-floor', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-blind-corner', 'west', 'the-low-mist', NULL);
