-- Generated by scripts/build-rooms.mjs from: regions/the-wood-3.rooms
-- 70 rooms, 208 exits. Do not hand-edit — regenerate from the source text.
-- Validated: every exit resolves, every exit has a return path (or is marked one-way),
-- no duplicate ids, no orphans, every room reachable from a gate.

-- the-wind-shorn-edge: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wind-shorn-edge', 'north', 'the-outer-scrub', NULL);

-- the-spring-head: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-spring-head', 'north', 'the-bracken-edge', NULL);

-- the-hornbeam-row: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hornbeam-row', 'north', 'the-north-ride', NULL);

-- the-hunters-stand: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hunters-stand', 'north', 'the-thin-soil', NULL);

-- the-high-holly: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-high-holly', 'north', 'the-last-oaks', NULL);

-- the-lime-kiln: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lime-kiln', 'south', 'the-willow-margin', NULL);

-- the-alder-carr: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-alder-carr', 'south', 'the-flood-meadow', NULL);

-- the-mire-edge: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-mire-edge', 'south', 'the-south-ride', NULL);

-- the-deer-fence: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-deer-fence', 'south', 'the-black-mud', NULL);

-- the-burnt-stand: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-burnt-stand', 'south', 'the-drowned-holly', NULL);

-- the-close-dark: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-close-dark', 'down', 'the-sunken-wood', NULL);

-- the-leaning-wood: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-leaning-wood', 'down', 'the-earth-fall', NULL);

-- the-still-air: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-still-air', 'down', 'the-slip', NULL);

-- the-far-hollow: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-far-hollow', 'down', 'the-old-ditch', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-outer-scrub', 'door', 'The Outer Scrub', 'Thorn and stunted birch in poor ground, the last of the wood before it gives up entirely, with the open country showing grey through the gaps. Nothing here is taller than you are.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-outer-scrub', 'south', 'the-wind-shorn-edge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-outer-scrub', 'west', 'the-bracken-edge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-outer-scrub', 'north', 'the-fallen-wall', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-fallen-wall', 'door', 'The Fallen Wall', 'A drystone wall running east to west, down to knee height along most of its length and gone altogether in places, with trees now growing on both sides of it and through it. Somebody''s boundary, kept up for centuries and then not.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fallen-wall', 'south', 'the-outer-scrub', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-bracken-edge', 'door', 'The Bracken Edge', 'Bracken has taken everything that gets light here, shoulder-high and unbroken, so that the trees stand up out of a green sea you have to wade. Underneath it the ground is invisible and uneven.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bracken-edge', 'east', 'the-outer-scrub', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bracken-edge', 'south', 'the-spring-head', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bracken-edge', 'west', 'the-north-ride', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-north-ride', 'door', 'The North Ride', 'A straight cut through the wood forty feet wide, grassed over now, running away east and west further than you can see. It was made for dragging timber out, or for driving game along, and it has not been used for either in a long time.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-north-ride', 'east', 'the-bracken-edge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-north-ride', 'south', 'the-hornbeam-row', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-north-ride', 'west', 'the-thin-soil', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-north-ride', 'north', 'the-charcoal-ring', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-charcoal-ring', 'door', 'The Charcoal Ring', 'Another burning-floor, smaller than the one south of here and much older, the black circle almost grown over. Whoever worked this end of the wood worked it the same way, on the same schedule, for generations.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-charcoal-ring', 'south', 'the-north-ride', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-thin-soil', 'door', 'The Thin Soil', 'Rock comes near the surface here and the trees know it — short, thick-trunked, wide-crowned, rooted sideways across the stone instead of down into it. In three places the bare rock is through, grey and scoured.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-thin-soil', 'east', 'the-north-ride', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-thin-soil', 'south', 'the-hunters-stand', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-thin-soil', 'west', 'the-last-oaks', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-thin-soil', 'north', 'the-timber-stack', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-timber-stack', 'door', 'The Timber Stack', 'Cut trunks stacked in a crib eight feet high, squared and sound and stripped, seasoned past use and never collected. The bottom course has gone soft into the ground. The top course would still take an axe.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-timber-stack', 'south', 'the-thin-soil', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-last-oaks', 'door', 'The Last Oaks', 'Six oaks of enormous age standing well apart in clean ground, each one wide enough to fill a room, and nothing growing under any of them. They were old before the wall fell. They have outlasted every use anybody had for them.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-last-oaks', 'east', 'the-thin-soil', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-last-oaks', 'south', 'the-high-holly', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-last-oaks', 'west', 'the-far-north-turning', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-last-oaks', 'north', 'the-poachers-camp', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-poachers-camp', 'door', 'The Poacher''s Camp', 'A hollow behind a fallen crown with a fire-scrape in it, a stone to sit on, and a wire snare still set in the run behind, rusted through and holding nothing. Somebody worked this ground carefully and quietly and did not come back for their gear.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-poachers-camp', 'south', 'the-last-oaks', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-willow-margin', 'door', 'The Willow Margin', 'Willow along the wood''s southern water, silvered and thin, leaning out over ground that is more water than ground. Everything here bends and nothing here breaks.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-willow-margin', 'north', 'the-lime-kiln', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-willow-margin', 'west', 'the-flood-meadow', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-willow-margin', 'south', 'the-old-pond', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-old-pond', 'door', 'The Old Pond', 'A pond somebody dug, square-cornered under the weed, with a stone sill at one end where the overflow ran. It is silting up from the edges in. What is left of the open water is black and perfectly still.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-old-pond', 'north', 'the-willow-margin', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-flood-meadow', 'door', 'The Flood Meadow', 'Open ground inside the wood that the water takes every winter and gives back every spring, so nothing woody has ever got a hold. Coarse grass, flat as a table, and a tidemark of stranded twigs all round the edge at knee height.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-flood-meadow', 'east', 'the-willow-margin', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-flood-meadow', 'north', 'the-alder-carr', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-flood-meadow', 'west', 'the-south-ride', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-flood-meadow', 'south', 'the-heronry', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-heronry', 'door', 'The Heronry', 'Big untidy nests wedged in the tops of the tallest alders, a dozen of them, and the ground beneath white and stinking and littered with bones the size of your finger. The birds are not in residence. Something has been at the nests.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-heronry', 'north', 'the-flood-meadow', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-south-ride', 'door', 'The South Ride', 'The southern twin of the north ride, the same forty-foot cut, but this one holds water down its whole length in a shallow green channel. Walking it means walking in it.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-south-ride', 'east', 'the-flood-meadow', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-south-ride', 'north', 'the-mire-edge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-south-ride', 'west', 'the-black-mud', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-south-ride', 'south', 'the-withy-hut', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-withy-hut', 'door', 'The Withy Hut', 'A low round hut of woven withies plastered with mud, built to cut and soak and bend osiers in, and dry inside to this day. It has one low door and no window, and nothing has denned in it — too tight, too smelling of man, too easy to be cornered in.', 0, 1, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-withy-hut', 'north', 'the-south-ride', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-black-mud', 'door', 'The Black Mud', 'Ground churned to a black grease that takes your boot to the ankle and gives it back reluctantly. Everything that crosses here leaves a record, and the record is crowded, and some of it is fresh.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-black-mud', 'east', 'the-south-ride', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-black-mud', 'north', 'the-deer-fence', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-black-mud', 'west', 'the-drowned-holly', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-black-mud', 'south', 'the-osier-beds', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-osier-beds', 'door', 'The Osier Beds', 'Willow cut to the stool in rows and left, so each stump carries a fistful of straight red rods eight feet long. They were harvested every winter without fail. They have not been cut in years, and the rows are still perfectly straight.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-osier-beds', 'north', 'the-black-mud', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-drowned-holly', 'door', 'The Drowned Holly', 'Holly standing in water, which it should not tolerate and evidently does, the lower leaves black and the upper still hard and green. The water is clear and shallow and has no obvious source or outlet.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drowned-holly', 'east', 'the-black-mud', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drowned-holly', 'north', 'the-burnt-stand', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drowned-holly', 'west', 'the-far-south-turning', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-far-north-turning', 'door', 'The Far North Turning', 'Past the last of the great oaks the ground rises very slightly and the wood changes species without changing character. There is nothing here to notice and nothing here to remember, which is the only warning you get.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-far-north-turning', 'east', 'the-last-oaks', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-far-north-turning', 'west', 'the-bracken-sea', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-far-south-turning', 'door', 'The Far South Turning', 'The water underfoot deepens by an inch and the trees stand closer, and the sound of your own wading stops carrying more than a few paces. It is not a boundary. Nothing here is a boundary.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-far-south-turning', 'east', 'the-drowned-holly', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-far-south-turning', 'west', 'the-willow-break', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-bracken-sea', 'door', 'The Bracken Sea', 'Bracken over your head, in every direction, with the trunks going up through it and no ground visible anywhere. You are walking by feel and pushing with your arms, and the way closes behind you as you go.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bracken-sea', 'north', 'the-pine-dark', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bracken-sea', 'east', 'the-empty-ride', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bracken-sea', 'south', 'the-thin-birches', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bracken-sea', 'west', 'the-ant-hills', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-pine-dark', 'door', 'The Pine Dark', 'Planted pine in dead straight rows, so dense that the lower branches are all dead and the floor is bare orange needle and nothing else. There is no undergrowth, no birdsong, and no light worth the name.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-pine-dark', 'north', 'the-windfall', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-pine-dark', 'east', 'the-lichen-wood', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-pine-dark', 'south', 'the-old-burn', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-pine-dark', 'west', 'the-holly-maze', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-windfall', 'door', 'The Windfall', 'A gale laid a whole stand down in one night and they lie as they fell, crossed over each other at every angle, root-plates up. Getting through is a matter of climbing, and every surface is slick.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-windfall', 'north', 'the-empty-ride', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-windfall', 'east', 'the-thin-birches', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-windfall', 'south', 'the-ant-hills', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-windfall', 'west', 'the-dry-gully', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-empty-ride', 'door', 'The Empty Ride', 'A cut ride like the ones at the wood''s edge — the same width, the same grass — running east and west, except that it does not come from anywhere and does not go anywhere, and both ends simply stop in standing wood.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-empty-ride', 'north', 'the-lichen-wood', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-empty-ride', 'east', 'the-old-burn', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-empty-ride', 'south', 'the-holly-maze', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-empty-ride', 'west', 'the-open-canopy', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-lichen-wood', 'door', 'The Lichen Wood', 'Every branch is furred with grey-green lichen hanging in beards a foot long, thick enough to blur the shapes of the trees. It only grows where the air has been clean and undisturbed for a very long time.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lichen-wood', 'north', 'the-thin-birches', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lichen-wood', 'east', 'the-ant-hills', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lichen-wood', 'south', 'the-dry-gully', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lichen-wood', 'west', 'the-deer-lawn', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-thin-birches', 'door', 'The Thin Birches', 'Birch grown up too close and starved of light, hundreds of them no thicker than your wrist, all the same height, all dying. Half are dead standing and held up by the others.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-thin-birches', 'north', 'the-old-burn', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-thin-birches', 'east', 'the-holly-maze', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-thin-birches', 'south', 'the-open-canopy', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-thin-birches', 'west', 'the-bracken-sea', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-old-burn', 'door', 'The Old Burn', 'Fire came through a generation ago and the wood has closed over the scar, but the ground still tells: charcoal in the litter, and every mature trunk blackened on one side to the same height.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-old-burn', 'north', 'the-ant-hills', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-old-burn', 'east', 'the-hornbeam-row', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-old-burn', 'south', 'the-deer-lawn', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-old-burn', 'west', 'the-pine-dark', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-ant-hills', 'door', 'The Ant Hills', 'Wood-ant nests the height of your chest, a dozen of them spread through open pine, each one a heap of needles alive on the surface with a movement you can hear if you stand still. The ground between them is highways.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ant-hills', 'north', 'the-holly-maze', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ant-hills', 'east', 'the-open-canopy', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ant-hills', 'south', 'the-bracken-sea', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ant-hills', 'west', 'the-windfall', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-holly-maze', 'door', 'The Holly Maze', 'Holly gone rampant, grown into itself into walls and blind passages taller than a man, with bare swept floor between. It is not a maze. It only has the shape of one, and it goes on for some distance.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-holly-maze', 'north', 'the-dry-gully', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-holly-maze', 'east', 'the-deer-lawn', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-holly-maze', 'south', 'the-pine-dark', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-holly-maze', 'west', 'the-empty-ride', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-dry-gully', 'door', 'The Dry Gully', 'A watercourse with no water in it, cut deep into the wood floor, floored with clean rounded stones. Something ran here for a long time and does not any more, and the trees have grown right up to both lips.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-dry-gully', 'north', 'the-open-canopy', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-dry-gully', 'east', 'the-bracken-sea', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-dry-gully', 'south', 'the-north-ride', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-dry-gully', 'west', 'the-lichen-wood', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-open-canopy', 'door', 'The Open Canopy', 'A stretch where the crowns do not meet, and the sky is up there in patches, and the light comes down in hard columns you can walk between. Everything at ground level is a tangle of things racing for it.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-open-canopy', 'north', 'the-deer-lawn', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-open-canopy', 'east', 'the-pine-dark', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-open-canopy', 'south', 'the-empty-ride', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-open-canopy', 'west', 'the-thin-birches', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-deer-lawn', 'door', 'The Deer Lawn', 'Grass, cropped to the length of a carpet over half an acre, ringed by trees browsed to a perfectly level line at the height of a deer''s reach. Nothing is standing on it. It has been kept like this by a great many mouths over a great many years.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-deer-lawn', 'north', 'the-bracken-sea', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-deer-lawn', 'east', 'the-windfall', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-deer-lawn', 'south', 'the-lichen-wood', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-deer-lawn', 'west', 'the-old-burn', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-willow-break', 'door', 'The Willow Break', 'Willow grown into a thicket you cannot see through at any height, standing in water, every stem leaning a different way. Pushing through means both hands, and you cannot hear anything over the noise you are making.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-willow-break', 'north', 'the-flooded-ride', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-willow-break', 'east', 'the-sedge-flat', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-willow-break', 'south', 'the-quaking-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-willow-break', 'west', 'the-silted-pond', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-flooded-ride', 'door', 'The Flooded Ride', 'Another of the wood''s straight cuts, this one under a foot of standing water for its whole visible length, mirror-flat, with the trees on both sides doubled in it. Wading it, you break the only straight line here.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-flooded-ride', 'north', 'the-black-pool', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-flooded-ride', 'east', 'the-leaning-alders', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-flooded-ride', 'south', 'the-eel-ditch', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-flooded-ride', 'west', 'the-rush-bed', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-black-pool', 'door', 'The Black Pool', 'Open water in the trees, a good stone''s throw across, so dark it gives back the canopy and nothing of its own depth. The edge shelves away immediately. Nothing grows in it and nothing is on it.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-black-pool', 'north', 'the-sedge-flat', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-black-pool', 'east', 'the-quaking-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-black-pool', 'south', 'the-silted-pond', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-black-pool', 'west', 'the-frog-chorus', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-sedge-flat', 'door', 'The Sedge Flat', 'Sedge in tussocks, each one a firm footing surrounded by water of no known depth, spaced just too far apart to step between comfortably. Going straight across is a series of decisions.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sedge-flat', 'north', 'the-leaning-alders', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sedge-flat', 'east', 'the-eel-ditch', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sedge-flat', 'south', 'the-rush-bed', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sedge-flat', 'west', 'the-sunk-fence', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-leaning-alders', 'door', 'The Leaning Alders', 'Alders that started upright and have been slowly laid over by the ground softening under them, so the whole stand leans thirty degrees the same way, still growing, still in leaf.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-leaning-alders', 'north', 'the-quaking-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-leaning-alders', 'east', 'the-mire-edge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-leaning-alders', 'south', 'the-frog-chorus', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-leaning-alders', 'west', 'the-brown-water', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-quaking-ground', 'door', 'The Quaking Ground', 'A raft of root and moss floating on water, springing underfoot for yards around every step you take, so that the trees themselves move slightly when you walk. It holds. It is not clear how.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-quaking-ground', 'north', 'the-eel-ditch', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-quaking-ground', 'east', 'the-rush-bed', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-quaking-ground', 'south', 'the-sunk-fence', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-quaking-ground', 'west', 'the-willow-break', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-eel-ditch', 'door', 'The Eel Ditch', 'A cut ditch, straight, waist-deep, running through the wet wood with brick still showing at the corners of it. The water in it moves, very slowly, and something in it moves faster than the water does.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-eel-ditch', 'north', 'the-silted-pond', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-eel-ditch', 'east', 'the-frog-chorus', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-eel-ditch', 'south', 'the-brown-water', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-eel-ditch', 'west', 'the-flooded-ride', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-silted-pond', 'door', 'The Silted Pond', 'A pond three-quarters filled with its own silt, so what is left is a crescent of water round a flat of grey mud that will not hold anything. The mud is printed all over, and the prints go in and do not come out.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-silted-pond', 'north', 'the-rush-bed', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-silted-pond', 'east', 'the-sunk-fence', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-silted-pond', 'south', 'the-willow-break', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-silted-pond', 'west', 'the-black-pool', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-rush-bed', 'door', 'The Rush Bed', 'Soft rush in a stand taller than your head, so dense it takes the light out entirely, growing out of six inches of water. Every step is loud and every direction looks the same from inside it.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rush-bed', 'north', 'the-frog-chorus', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rush-bed', 'east', 'the-brown-water', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rush-bed', 'south', 'the-flooded-ride', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rush-bed', 'west', 'the-sedge-flat', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-frog-chorus', 'door', 'The Frog Chorus', 'The noise here is enormous and unbroken and comes from everywhere at once, and it stops the moment you arrive, all of it, and starts again behind you before you have gone ten paces.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-frog-chorus', 'north', 'the-sunk-fence', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-frog-chorus', 'east', 'the-willow-break', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-frog-chorus', 'south', 'the-black-pool', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-frog-chorus', 'west', 'the-quaking-ground', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-sunk-fence', 'door', 'The Sunk Fence', 'A line of posts running away through the water with their tops a foot proud of it, the wire long gone. It goes straight for as far as you can follow it and disappears under without changing angle.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sunk-fence', 'north', 'the-south-ride', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sunk-fence', 'east', 'the-flooded-ride', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sunk-fence', 'south', 'the-sedge-flat', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sunk-fence', 'west', 'the-eel-ditch', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-brown-water', 'door', 'The Brown Water', 'Water stained the colour of strong tea by whatever it has been sitting in, shin-deep everywhere and the same depth everywhere, with no bank and no channel and no edge to it that you can find.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-brown-water', 'north', 'the-willow-break', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-brown-water', 'east', 'the-black-pool', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-brown-water', 'south', 'the-leaning-alders', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-brown-water', 'west', 'the-old-burn', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-sunken-wood', 'door', 'The Sunken Wood', 'The ground here is fifteen feet below the wood you were in, and the trees growing out of it reach their crowns up to the same level as the trees up there, so the canopy is continuous and the floor is not.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sunken-wood', 'north', 'the-under-eaves', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sunken-wood', 'east', 'the-cold-seep', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sunken-wood', 'south', 'the-earth-fall', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sunken-wood', 'west', 'the-slip', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-under-eaves', 'door', 'The Under-Eaves', 'Down here the light arrives already used — filtered through the whole depth of the canopy above and then again through what grows at this level — and everything is the colour of a bruise.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-under-eaves', 'north', 'the-fern-pit', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-under-eaves', 'east', 'the-buried-wall', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-under-eaves', 'south', 'the-white-roots', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-under-eaves', 'west', 'the-lost-stand', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-fern-pit', 'door', 'The Fern Pit', 'Ferns four feet high covering the whole floor of the depression, unbroken, and the air standing damp and green in among them. On the north side the bank is climbable, roots for handholds all the way.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fern-pit', 'north', 'the-cold-seep', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fern-pit', 'east', 'the-earth-fall', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fern-pit', 'south', 'the-slip', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fern-pit', 'west', 'the-green-dark', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fern-pit', 'up', 'the-charcoal-flat', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-cold-seep', 'door', 'The Cold Seep', 'Water comes out of the bank here in a dozen places at once, not fast, and runs away over a floor of clean grey clay. The cold of it comes up through your boots within a few steps.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cold-seep', 'north', 'the-buried-wall', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cold-seep', 'east', 'the-white-roots', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cold-seep', 'south', 'the-lost-stand', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cold-seep', 'west', 'the-bottom-of-it', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-buried-wall', 'door', 'The Buried Wall', 'Dressed stone showing through the bank in a course six feet long, cut and squared and laid by somebody, with the wood growing over the top of it and the rest of it going away into the earth in both directions.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-buried-wall', 'north', 'the-earth-fall', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-buried-wall', 'east', 'the-slip', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-buried-wall', 'south', 'the-green-dark', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-buried-wall', 'west', 'the-old-ditch', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-earth-fall', 'door', 'The Earth Fall', 'A section of the upper bank has come away and lies here in a slope of raw earth and toppled trees, still settling, with the roots of things standing up out of it. The hole it left is up there and you cannot reach it.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-earth-fall', 'north', 'the-white-roots', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-earth-fall', 'east', 'the-lost-stand', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-earth-fall', 'south', 'the-bottom-of-it', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-earth-fall', 'west', 'the-sunken-wood', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-white-roots', 'door', 'The White Roots', 'Roots come out of the bank at every height and hang in the air where the earth has washed from under them, pale and blind and thick as your arm, and you go through them the way you would go through a curtain.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-white-roots', 'north', 'the-slip', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-white-roots', 'east', 'the-green-dark', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-white-roots', 'south', 'the-old-ditch', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-white-roots', 'west', 'the-under-eaves', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-slip', 'door', 'The Slip', 'Wet clay on a slope, scored all over with the marks of things that have come down it and not gone back up. It is perfectly passable downhill and not passable at all in the other direction.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-slip', 'north', 'the-lost-stand', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-slip', 'east', 'the-bottom-of-it', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-slip', 'south', 'the-sunken-wood', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-slip', 'west', 'the-fern-pit', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-lost-stand', 'door', 'The Lost Stand', 'Trees down here that are not the same species as the ones above — older, heavier, a wood that was growing before the ground fell in and has been carrying on ever since without reference to anything. The east bank goes up in steps.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lost-stand', 'north', 'the-bottom-of-it', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lost-stand', 'east', 'the-old-ditch', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lost-stand', 'south', 'the-under-eaves', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lost-stand', 'west', 'the-cold-seep', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lost-stand', 'up', 'the-mire-edge', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-green-dark', 'door', 'The Green Dark', 'There is enough light to walk by and not enough to read a face, and all of it is green, and it does not change with the hour because it never came directly from the sky in the first place.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-green-dark', 'north', 'the-bottom-of-it', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-green-dark', 'east', 'the-sunken-wood', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-green-dark', 'south', 'the-fern-pit', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-green-dark', 'west', 'the-buried-wall', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-bottom-of-it', 'door', 'The Bottom of It', 'The lowest ground, where the seeps collect into a floor of black standing water an inch deep over clay, absolutely flat, going away between the trunks in every direction with no rise anywhere in sight.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bottom-of-it', 'north', 'the-old-ditch', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bottom-of-it', 'east', 'the-under-eaves', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bottom-of-it', 'south', 'the-cold-seep', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bottom-of-it', 'west', 'the-white-roots', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-old-ditch', 'door', 'The Old Ditch', 'A ditch dug down here when down here was up there — before the ground went — running straight through the sunken wood and cut off at both ends by banks of fallen earth. It still holds its shape exactly.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-old-ditch', 'north', 'the-sunken-wood', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-old-ditch', 'east', 'the-fern-pit', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-old-ditch', 'south', 'the-buried-wall', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-old-ditch', 'west', 'the-white-roots', NULL);
