-- Generated by scripts/build-rooms.mjs from: regions/the-wood-4.rooms
-- 61 rooms, 185 exits. Do not hand-edit — regenerate from the source text.
-- Validated: every exit resolves, every exit has a return path (or is marked one-way),
-- no duplicate ids, no orphans, every room reachable from a gate.

-- the-cold-seep: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cold-seep', 'up', 'the-long-glade', NULL);

-- the-white-roots: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-white-roots', 'up', 'the-standing-water', NULL);

-- the-bottom-of-it: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bottom-of-it', 'up', 'the-far-mire', NULL);

-- the-sunken-wood: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sunken-wood', 'down', 'the-lower-ditch', NULL);

-- the-buried-wall: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-buried-wall', 'down', 'the-old-course', NULL);

-- the-green-dark: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-green-dark', 'down', 'the-still-pool', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-far-birches', 'door', 'The Far Birches', 'Birch again, the way the wood began on the other side, except that there is no road behind this stand and no gap in it that goes anywhere you have been. The light comes from the wrong direction for the hour.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-far-birches', 'west', 'the-wolf-pits', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-far-birches', 'south', 'the-long-glade', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-far-birches', 'north', 'the-park-pale', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-far-birches', 'east', 'the-bracken-sea', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-park-pale', 'door', 'The Park Pale', 'A bank and ditch running north to south with the stumps of a paling fence still in the crest of it, cut and set to keep deer inside a park. There is no park. There has not been a park for a very long time.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-park-pale', 'south', 'the-far-birches', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-wolf-pits', 'door', 'The Wolf Pits', 'Two deep steep-sided pits with a narrow bar of earth between them, dug where a run comes through, revetted in stone at the lip. Whatever they were dug for was worth this much labour, once.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wolf-pits', 'east', 'the-far-birches', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wolf-pits', 'west', 'the-north-marches', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wolf-pits', 'south', 'the-keepers-approach', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wolf-pits', 'north', 'the-dovecote', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-dovecote', 'door', 'The Dovecote', 'A round stone tower the height of two men, roofless, its whole inner wall stepped with nesting boxes from the floor to the top course. It held several hundred birds and somebody ate them.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-dovecote', 'south', 'the-wolf-pits', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-north-marches', 'door', 'The North Marches', 'Wide open wood, mature and well spaced, with grass under it instead of leaf-litter — grazed ground, kept that way by something in numbers. It goes on north further than you want to commit to.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-north-marches', 'east', 'the-wolf-pits', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-north-marches', 'west', 'the-edge-of-it', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-north-marches', 'south', 'the-moat-bank', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-north-marches', 'north', 'the-fishponds', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-fishponds', 'door', 'The Fishponds', 'Three rectangular ponds in a line down the slope, each one feeding the next through a stone sluice, all of them silted to a black flat and grown over with reed. They were stocked and harvested and counted.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fishponds', 'south', 'the-north-marches', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-edge-of-it', 'door', 'The Edge of It', 'The wood simply stops. Not a boundary, not a ride, not a change of species — a line, beyond which is grey open country with nothing on it, going away west as far as there is light to see it by.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-edge-of-it', 'east', 'the-north-marches', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-edge-of-it', 'south', 'the-west-ride', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-long-glade', 'door', 'The Long Glade', 'A glade running east to west, narrow and half a mile of it, floored in fine grass. Standing at one end you can see the whole length, and there is nothing in it, and nothing crosses it while you watch.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-long-glade', 'north', 'the-far-birches', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-long-glade', 'west', 'the-keepers-approach', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-long-glade', 'south', 'the-standing-water', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-keepers-approach', 'door', 'The Keeper''s Approach', 'An avenue of limes, planted in two lines with forty feet between them, running west. They are grown out of all discipline now but the lines hold. Somebody meant this to be walked up, slowly, toward something.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-keepers-approach', 'east', 'the-long-glade', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-keepers-approach', 'west', 'the-moat-bank', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-keepers-approach', 'north', 'the-wolf-pits', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-keepers-approach', 'south', 'the-orchard-gone-wild', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-moat-bank', 'door', 'The Moat Bank', 'The outer bank of a moat, grassed over, with the water still lying in the ditch below it — square-cut, corners intact, going round something. From up here you can see the whole enclosure and what is left standing in it.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-moat-bank', 'east', 'the-keepers-approach', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-moat-bank', 'west', 'the-west-ride', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-moat-bank', 'north', 'the-north-marches', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-moat-bank', 'south', 'the-yew-walk', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-west-ride', 'door', 'The West Ride', 'The last of the rides, running west and ending at a gap in the moat bank where a bridge was. The abutments are there. Everything between them is gone.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-west-ride', 'east', 'the-moat-bank', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-west-ride', 'north', 'the-edge-of-it', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-west-ride', 'south', 'the-boar-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-west-ride', 'west', 'the-gate-arch', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-standing-water', 'door', 'The Standing Water', 'Water lying in a broad shallow sheet over the wood floor with no bank to it, ankle-deep and still, the trees going down into their own reflections. It has no source and no outlet and it does not drain.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-standing-water', 'north', 'the-long-glade', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-standing-water', 'west', 'the-orchard-gone-wild', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-standing-water', 'south', 'the-far-mire', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-orchard-gone-wild', 'door', 'The Orchard Gone Wild', 'Fruit trees in rows, unpruned for a century, grown tall and thin and reaching, still bearing something small and hard. Between the rows the grass is deep. Somebody''s apples, still coming, for nobody.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-orchard-gone-wild', 'east', 'the-standing-water', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-orchard-gone-wild', 'west', 'the-yew-walk', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-orchard-gone-wild', 'north', 'the-keepers-approach', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-orchard-gone-wild', 'south', 'the-sunken-lawn', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-yew-walk', 'door', 'The Yew Walk', 'Yews planted in a double row, enormous now, their crowns grown into one another to make a tunnel that keeps out weather and light in equal measure. The floor of it is bare red needle and nothing else.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-yew-walk', 'east', 'the-orchard-gone-wild', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-yew-walk', 'west', 'the-boar-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-yew-walk', 'north', 'the-moat-bank', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-yew-walk', 'south', 'the-broken-avenue', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-boar-ground', 'door', 'The Boar Ground', 'Ground rooted up wholesale — turf turned in sheets, saplings pushed over, the whole stretch worked at by something heavy and unhurried. It is not old and it is not finished.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-boar-ground', 'east', 'the-yew-walk', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-boar-ground', 'north', 'the-west-ride', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-boar-ground', 'south', 'the-holly-hedge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-boar-ground', 'west', 'the-thorn-waste', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-far-mire', 'door', 'The Far Mire', 'Wet ground again at the wood''s far southern corner, pale and quaking, with the trees standing in it thinly and leaning. Something has crossed it in a straight line and the line is still holding its shape.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-far-mire', 'north', 'the-standing-water', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-far-mire', 'west', 'the-sunken-lawn', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-far-mire', 'south', 'the-stew-pond', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-far-mire', 'east', 'the-willow-break', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-stew-pond', 'door', 'The Stew Pond', 'A pond dug and lined and provided with a stone sill, for keeping fish alive until they were wanted. It has held its shape perfectly and it is entirely full of black leaf-mud.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-stew-pond', 'north', 'the-far-mire', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-sunken-lawn', 'door', 'The Sunken Lawn', 'A rectangle of ground a foot lower than everything around it, level as a table, its edges too straight to be anything but cut. Grass, close and fine, and nothing growing on it taller than your ankle.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sunken-lawn', 'east', 'the-far-mire', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sunken-lawn', 'west', 'the-broken-avenue', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sunken-lawn', 'north', 'the-orchard-gone-wild', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-broken-avenue', 'door', 'The Broken Avenue', 'Another planted line, this one of beech, and half of it down — every third or fourth tree fallen in the same direction on the same night, and the survivors standing on in the gaps.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-broken-avenue', 'east', 'the-sunken-lawn', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-broken-avenue', 'west', 'the-holly-hedge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-broken-avenue', 'north', 'the-yew-walk', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-broken-avenue', 'south', 'the-hollow-yew', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-hollow-yew', 'door', 'The Hollow Yew', 'One yew, alone, older than the planted ones by centuries, hollow enough to stand inside with room to turn round. The inside is dry and dark and smells of nothing at all.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hollow-yew', 'north', 'the-broken-avenue', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-holly-hedge', 'door', 'The Holly Hedge', 'A hedge of holly laid and woven by hand, grown out now to twice its intended height but still visibly a made thing, running north to south. It marks the last enclosed edge of the holding.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-holly-hedge', 'east', 'the-broken-avenue', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-holly-hedge', 'north', 'the-boar-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-holly-hedge', 'south', 'the-ash-heap', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-ash-heap', 'door', 'The Ash Heap', 'A mound of white wood-ash and clinker, dumped over years, grown over with nettle at the edges and still bare on top. Whatever burned here burned steadily and for a long time.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ash-heap', 'north', 'the-holly-hedge', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-gate-arch', 'door', 'The Gate Arch', 'A stone arch standing on its own, the gatehouse it belonged to gone from around it, with the sockets for the gate-pins still cut in the jambs. The road under it is still paved for twenty feet in each direction.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-gate-arch', 'east', 'the-west-ride', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-gate-arch', 'south', 'the-well-court', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-gate-arch', 'north', 'the-stable-range', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-stable-range', 'door', 'The Stable Range', 'A long low range with the mangers still in it, twelve bays of them, and the tethering rings still set in the wall. The roof went first and everything else has been going since.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-stable-range', 'south', 'the-gate-arch', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-well-court', 'door', 'The Well Court', 'A courtyard with a wellhead in the middle of it, the winding gear gone but the shaft open and lined and dropping further than your eye follows. Grass has come up between every flag.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-well-court', 'north', 'the-gate-arch', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-well-court', 'east', 'the-kitchen-range', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-well-court', 'west', 'the-chapel-shell', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-well-court', 'south', 'the-hall-floor', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-kitchen-range', 'door', 'The Kitchen Range', 'Two enormous hearths back to back in a wall that is otherwise mostly gone, the flues still standing up out of it, the stone burned to a soft white for six feet above each opening.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-kitchen-range', 'west', 'the-well-court', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-kitchen-range', 'south', 'the-fish-house', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-fish-house', 'door', 'The Fish House', 'A small vaulted building set into the ground with stone tanks in the floor, three of them, fed once from the moat. They hold rainwater now, and something is living in them.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fish-house', 'north', 'the-kitchen-range', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-chapel-shell', 'door', 'The Chapel Shell', 'Four walls and no roof, the window openings still traced in cut stone, and a floor of grave-slabs worn smooth and unreadable. Whatever this family was, they were buried in their own house.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-chapel-shell', 'east', 'the-well-court', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-hall-floor', 'door', 'The Hall Floor', 'The great hall, reduced to its floor and the stumps of its walls: a rectangle of paving with a hearth in the middle of it, open to the sky, big enough that the roof over it must have been a considerable idea.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hall-floor', 'north', 'the-well-court', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hall-floor', 'south', 'the-solar', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hall-floor', 'east', 'the-icehouse', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-solar', 'door', 'The Solar', 'The private end, one room''s worth, up three steps from the hall floor and better built than the rest — dressed ashlar, a fireplace with carving on the lintel, a window that faced the garden.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-solar', 'north', 'the-hall-floor', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-icehouse', 'door', 'The Icehouse', 'A brick dome half buried in the bank with a low passage into it, and the passage is clear. Inside, the air is markedly colder than outside, which after this long is not something the brick is doing.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-icehouse', 'west', 'the-hall-floor', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-lower-ditch', 'door', 'The Lower Ditch', 'A cut running through the dark at the bottom of everything, revetted with rough stone, going straight in both directions. It was open to the sky once. It has a wood''s worth of ground over it now.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lower-ditch', 'north', 'the-flint-floor', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lower-ditch', 'east', 'the-drip-line', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lower-ditch', 'south', 'the-low-sump', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lower-ditch', 'west', 'the-clay-shelf', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-flint-floor', 'door', 'The Flint Floor', 'The floor here is a pavement of knapped flint set on edge, close-packed, laid by hand over a wide area and buried since. It rings faintly underfoot, which nothing else down here does.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-flint-floor', 'north', 'the-black-loam', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-flint-floor', 'east', 'the-old-course', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-flint-floor', 'south', 'the-tree-fall', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-flint-floor', 'west', 'the-still-pool', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-black-loam', 'door', 'The Black Loam', 'Soil so dark and fine it takes a print like wax and gives nothing back, deep enough that the tree roots reaching down into it never find a bottom. It smells rich and wrong.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-black-loam', 'north', 'the-drip-line', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-black-loam', 'east', 'the-low-sump', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-black-loam', 'south', 'the-clay-shelf', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-black-loam', 'west', 'the-buried-lane', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-drip-line', 'door', 'The Drip Line', 'Water comes down from the ceiling of roots in a hundred separate threads, steadily, into pools it has worn into the floor over an unhurried span of time. The sound is continuous and covers everything.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drip-line', 'north', 'the-old-course', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drip-line', 'east', 'the-tree-fall', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drip-line', 'south', 'the-still-pool', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drip-line', 'west', 'the-last-light', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-old-course', 'door', 'The Old Course', 'A riverbed, dry, with its gravel graded and its banks intact, running through the dark under the wood. The river left. Everything it built is exactly where it was.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-old-course', 'north', 'the-low-sump', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-old-course', 'east', 'the-clay-shelf', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-old-course', 'south', 'the-buried-lane', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-old-course', 'west', 'the-under-roots', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-old-course', 'up', 'the-yew-walk', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-low-sump', 'door', 'The Low Sump', 'The low point, where everything that comes down here collects: black water without a current, wide, and deeper at the middle than you would test. Nothing moves on it.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-low-sump', 'north', 'the-tree-fall', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-low-sump', 'east', 'the-still-pool', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-low-sump', 'south', 'the-last-light', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-low-sump', 'west', 'the-lower-ditch', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-tree-fall', 'door', 'The Tree Fall', 'A tree came down through the ground from above and is still here, most of it, jammed at an angle from the floor to the roots overhead, gone soft and pale and mounded with fungus.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-tree-fall', 'north', 'the-clay-shelf', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-tree-fall', 'east', 'the-buried-lane', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-tree-fall', 'south', 'the-under-roots', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-tree-fall', 'west', 'the-flint-floor', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-clay-shelf', 'door', 'The Clay Shelf', 'A ledge of grey clay running out across the dark, smooth, wet, and holding every mark ever made on it. There are a great many marks and they are of several different kinds.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-clay-shelf', 'north', 'the-still-pool', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-clay-shelf', 'east', 'the-last-light', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-clay-shelf', 'south', 'the-lower-ditch', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-clay-shelf', 'west', 'the-black-loam', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-still-pool', 'door', 'The Still Pool', 'Water with a surface like a laid floor, absolutely unmoving, reflecting the roots above it so exactly that it takes a moment to work out which way up you are looking.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-still-pool', 'north', 'the-buried-lane', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-still-pool', 'east', 'the-under-roots', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-still-pool', 'south', 'the-flint-floor', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-still-pool', 'west', 'the-drip-line', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-buried-lane', 'door', 'The Buried Lane', 'A sunken track with banks on both sides and a hard rutted floor, running through the underground dark exactly as it would run through open country. It was a lane. The ground came up over it.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-buried-lane', 'north', 'the-last-light', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-buried-lane', 'east', 'the-lower-ditch', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-buried-lane', 'south', 'the-black-loam', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-buried-lane', 'west', 'the-old-course', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-last-light', 'door', 'The Last Light', 'A shaft of grey comes down from somewhere far overhead through a hole in the root-ceiling, and lands here, and lights a circle of floor about the size of a table. It is the only daylight down here.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-last-light', 'north', 'the-under-roots', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-last-light', 'east', 'the-flint-floor', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-last-light', 'south', 'the-drip-line', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-last-light', 'west', 'the-low-sump', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-last-light', 'up', 'the-broken-avenue', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-under-roots', 'door', 'The Under-Roots', 'The ceiling is entirely roots, woven together into a mat you could not put a knife through, and they come down to the floor in places in columns. It is holding up the whole wood, and you are underneath it.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-under-roots', 'north', 'the-lower-ditch', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-under-roots', 'east', 'the-black-loam', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-under-roots', 'south', 'the-old-course', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-under-roots', 'west', 'the-tree-fall', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-thorn-waste', 'door', 'The Thorn Waste', 'Thorn scrub over broken ground, head-high, in no order, with narrow ways through it that were made by something lower than you. It goes on in every direction at about the same height.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-thorn-waste', 'north', 'the-grey-scrub', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-thorn-waste', 'east', 'the-gorse-brake', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-thorn-waste', 'south', 'the-heath-edge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-thorn-waste', 'west', 'the-rabbit-warren', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-grey-scrub', 'door', 'The Grey Scrub', 'Everything here is the same grey-green and the same height and none of it is a tree. The wood has given out and not been replaced by anything with a shape.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-grey-scrub', 'north', 'the-broken-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-grey-scrub', 'east', 'the-sand-cut', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-grey-scrub', 'south', 'the-stunted-oaks', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-grey-scrub', 'west', 'the-dry-heath', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-broken-ground', 'door', 'The Broken Ground', 'Ground worked over and abandoned: shallow pits and heaps in no pattern, all of them grown over, all of them the same age. Somebody dug for something here across a wide area and either found it or gave up.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-broken-ground', 'north', 'the-gorse-brake', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-broken-ground', 'east', 'the-heath-edge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-broken-ground', 'south', 'the-rabbit-warren', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-broken-ground', 'west', 'the-pale-grass', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-gorse-brake', 'door', 'The Gorse Brake', 'Gorse in a solid mass, flowering, armed on every inch, with dry dead growth underneath it a foot deep. The smell is coconut and the noise underfoot is like walking on kindling.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-gorse-brake', 'north', 'the-sand-cut', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-gorse-brake', 'east', 'the-stunted-oaks', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-gorse-brake', 'south', 'the-dry-heath', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-gorse-brake', 'west', 'the-flint-scatter', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-sand-cut', 'door', 'The Sand Cut', 'A face of clean yellow sand standing eight feet high where something cut into the rise, with martin holes drilled along the top of it in a row and the spoil fanned out below.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sand-cut', 'north', 'the-heath-edge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sand-cut', 'east', 'the-rabbit-warren', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sand-cut', 'south', 'the-pale-grass', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sand-cut', 'west', 'the-wind-gap', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-heath-edge', 'door', 'The Heath Edge', 'Heather and bare sand, low and open, with the last of the scrub behind you and nothing in front but more of the same going away to a horizon that is much closer than it should be.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-heath-edge', 'north', 'the-stunted-oaks', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-heath-edge', 'east', 'the-dry-heath', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-heath-edge', 'south', 'the-flint-scatter', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-heath-edge', 'west', 'the-thorn-waste', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-stunted-oaks', 'door', 'The Stunted Oaks', 'Oaks that never got anywhere — forty of them, none taller than a man, all of them a century old at least, gnarled and thick-trunked and knee-high in heather.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-stunted-oaks', 'north', 'the-rabbit-warren', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-stunted-oaks', 'east', 'the-boar-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-stunted-oaks', 'south', 'the-wind-gap', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-stunted-oaks', 'west', 'the-grey-scrub', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-rabbit-warren', 'door', 'The Rabbit Warren', 'Sand worked through and through with burrows until the whole rise is hollow, the ground giving slightly wherever you put your weight. The cropped turf between the holes is very short and very green.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rabbit-warren', 'north', 'the-pale-grass', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rabbit-warren', 'east', 'the-flint-scatter', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rabbit-warren', 'south', 'the-thorn-waste', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rabbit-warren', 'west', 'the-broken-ground', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-dry-heath', 'door', 'The Dry Heath', 'Open heath, dry to the root, with a wind moving over it that has nothing to catch on. After the wood the sky is an unreasonable amount of sky.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-dry-heath', 'north', 'the-flint-scatter', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-dry-heath', 'east', 'the-wind-gap', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-dry-heath', 'south', 'the-grey-scrub', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-dry-heath', 'west', 'the-sand-cut', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-pale-grass', 'door', 'The Pale Grass', 'Grass bleached almost white, growing in tufts out of sand, with the bare ground showing between every tuft. Nothing is grazing it and nothing has trodden it.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-pale-grass', 'north', 'the-wind-gap', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-pale-grass', 'east', 'the-thorn-waste', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-pale-grass', 'south', 'the-broken-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-pale-grass', 'west', 'the-heath-edge', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-flint-scatter', 'door', 'The Flint Scatter', 'The surface is more flint than soil, broken nodules everywhere, and a good number of them are worked — struck flakes, cores, an edge here and there, lying where they were dropped.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-flint-scatter', 'north', 'the-holly-hedge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-flint-scatter', 'east', 'the-grey-scrub', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-flint-scatter', 'south', 'the-sand-cut', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-flint-scatter', 'west', 'the-stunted-oaks', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-wind-gap', 'door', 'The Wind-Gap', 'A saddle in the rise where the wind comes through in a steady stream and has scoured the ground to bare sand and stone. It is the highest point out here and it shows you nothing you recognise.', 0, 0, 'wood', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wind-gap', 'north', 'the-thorn-waste', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wind-gap', 'east', 'the-broken-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wind-gap', 'south', 'the-heath-edge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wind-gap', 'west', 'the-pale-grass', NULL);
