-- Generated by scripts/build-rooms.mjs from: regions/west-road-3.rooms
-- 12 rooms, 22 exits. Do not hand-edit — regenerate from the source text.
-- Validated: every exit resolves, every exit has a return path (or is marked one-way),
-- no duplicate ids, no orphans, every room reachable from a gate.

-- the-long-straight: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-long-straight', 'west', 'the-second-milestone', NULL);

-- the-weed-paving: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-weed-paving', 'east', 'the-third-milestone', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-second-milestone', 'door', 'The Second Milestone', 'A milestone of the same pattern as the one back east, cut with the same hand and the same numbers, standing to the same height in grass that nobody cuts. The face has been scratched at by passers-by until the distance it names is a matter of opinion.', 0, 0, 'road', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-second-milestone', 'east', 'the-long-straight', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-second-milestone', 'west', 'the-open-heath', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-open-heath', 'door', 'The Open Heath', 'The trees give out entirely and the road runs across a flat brown heath, ling and bare sand and standing water in the hollows, with nothing higher than your knee for as far as it goes. You can see a very long way. So can everything else.', 0, 0, 'road', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-open-heath', 'east', 'the-second-milestone', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-open-heath', 'west', 'the-burnt-farmstead', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-open-heath', 'north', 'the-pinfold', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-pinfold', 'door', 'The Pinfold', 'A round stone pound with an iron gate hanging off one pin, built to hold strays until somebody paid to have them back. The walls are chest-high and dry-laid and there is nothing in it now but nettles and the smell of very old dung.', 0, 0, 'road', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-pinfold', 'south', 'the-open-heath', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-burnt-farmstead', 'door', 'The Burnt Farmstead', 'A holding set back from the road behind a wall, burnt down to the gable ends and left. Somebody tried to farm the heath, which was optimistic, and then somebody else made sure they stopped. The hearth is still there, and the doorstep is worn hollow.', 0, 0, 'road', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-burnt-farmstead', 'east', 'the-open-heath', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-burnt-farmstead', 'west', 'the-wind-row', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-wind-row', 'door', 'The Wind Row', 'A double line of thorns planted along the road''s north side to break the weather off it, grown into one continuous bent hedge leaning south. Walking under it, the wind goes over your head and the noise it makes covers everything else.', 0, 0, 'road', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wind-row', 'east', 'the-burnt-farmstead', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wind-row', 'west', 'the-culvert', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wind-row', 'north', 'the-smithy-ruin', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-smithy-ruin', 'door', 'The Smithy Ruin', 'A wayside smithy with the roof gone and the walls to head height, the forge itself still standing in the corner as a block of scorched stone. The floor is black with beaten scale and the little cinders of two hundred years of somebody else''s work.', 0, 0, 'road', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-smithy-ruin', 'south', 'the-wind-row', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-culvert', 'door', 'The Culvert', 'The road crosses a drain on a barrel-arch of brick, low and neat, with the water going through it a good drop below. The parapet is gone on the south side. There is a way down the bank if you want to be under the road rather than on it.', 0, 0, 'road', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-culvert', 'east', 'the-wind-row', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-culvert', 'west', 'the-crooked-mile', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-crooked-mile', 'door', 'The Crooked Mile', 'A stretch where the paving bends twice for no reason the land gives — around something that was there when it was laid and is not there now. The kink is exact and old and nobody has ever straightened it.', 0, 0, 'road', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-crooked-mile', 'east', 'the-culvert', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-crooked-mile', 'west', 'the-hollow-elm', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-hollow-elm', 'door', 'The Hollow Elm', 'An elm dead of its own disease standing alone at the verge, hollow all the way up and open down one side, big enough inside for two people to stand out of the rain and dry enough that people plainly have. There is ash in the bottom of it.', 0, 0, 'road', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hollow-elm', 'east', 'the-crooked-mile', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hollow-elm', 'west', 'the-third-milestone', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-third-milestone', 'door', 'The Third Milestone', 'The last of the numbered stones, leaning hard downhill and half swallowed by the verge, its face turned away from the road as if it had given up on being read. West of here the paving starts losing its edges.', 0, 0, 'road', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-third-milestone', 'east', 'the-hollow-elm', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-third-milestone', 'west', 'the-weed-paving', NULL);
