-- Generated by scripts/build-rooms.mjs from: regions/the-dens-1.rooms, regions/the-dens-2.rooms
-- 67 rooms, 178 exits. Do not hand-edit — regenerate from the source text.
-- Validated: every exit resolves, every exit has a return path (or is marked one-way),
-- no duplicate ids, no orphans, every room reachable from a gate.

-- the-gap-in-the-trees: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-gap-in-the-trees', 'north', 'the-hurdle-gate', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-gap-in-the-trees', 'south', 'the-waste-edge', NULL);

-- the-birch-edge: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-birch-edge', 'east', 'the-hurdle-gate', NULL);

-- the-wind-shorn-edge: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wind-shorn-edge', 'east', 'the-old-assart', NULL);

-- the-outer-scrub: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-outer-scrub', 'east', 'the-thorn-hedge', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-hurdle-gate', 'door', 'The Hurdle Gate', 'A gap in a bank and ditch, with a hurdle across it — woven hazel, grey and light as basketwork, dropped into two posts. It was made to keep stock in, not people out, and it still would. Beyond it the ground opens and goes green in a way the wood has not been since you entered it, and the sky is back.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hurdle-gate', 'south', 'the-gap-in-the-trees', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hurdle-gate', 'west', 'the-birch-edge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hurdle-gate', 'east', 'the-drift-lane', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hurdle-gate', 'north', 'the-old-assart', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-drift-lane', 'door', 'The Drift Lane', 'Two banks with a way between them, running east, grassed over and sunk a foot below the fields either side by nothing but use. Nothing has been driven along it in a long time. In the middle of the track a line of taller grass has come up where the wheels never touched.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drift-lane', 'west', 'the-hurdle-gate', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drift-lane', 'east', 'the-lane-head', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drift-lane', 'north', 'the-cow-pasture', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-lane-head', 'door', 'The Lane Head', 'The lane widens where it met something — another track, or a yard, or a gate that has gone. The banks stop dead on both sides and the grass takes over. There is a mounting-block still standing here, two worn steps of stone, for getting onto a horse that nobody has ridden in for lifetimes.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lane-head', 'west', 'the-drift-lane', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lane-head', 'east', 'the-cart-turn', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lane-head', 'north', 'the-sunken-way', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-cart-turn', 'door', 'The Cart Turn', 'A bare circle of hard ground where carts were backed and swung, still bare, the earth beaten too dead to grow anything but moss. One cart is here, or the frame of one, sunk to the axle and gone soft. Its shafts point east at nothing.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cart-turn', 'west', 'the-lane-head', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-old-assart', 'door', 'The Old Assart', 'This was taken out of the wood with axes and fire, and you can still see the shape of the taking: the field is a rough oval and the trees stand around it in a wall, and every stump inside was grubbed out by somebody who then had to carry it somewhere. Grass now, thigh-high, and going back to thorn at the edges.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-old-assart', 'south', 'the-hurdle-gate', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-old-assart', 'west', 'the-wind-shorn-edge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-old-assart', 'east', 'the-cow-pasture', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-old-assart', 'north', 'the-thorn-hedge', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-cow-pasture', 'door', 'The Cow Pasture', 'Old grazing, close-cropped once and shaggy now, with a drinking hollow at the low end that still holds water and a rubbing-post in the middle worn smooth and shiny at cow height. The grass grows in the dark rings where the muck fell.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cow-pasture', 'south', 'the-drift-lane', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cow-pasture', 'west', 'the-old-assart', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cow-pasture', 'east', 'the-sunken-way', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cow-pasture', 'north', 'the-ridge-and-furrow', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-sunken-way', 'door', 'The Sunken Way', 'The track up to the houses, cut into the slope by feet and rain until it runs a body''s depth below the field on either hand, roots showing in both banks like pipework. Walking it, you can see nothing but sky and the two walls of earth, and nothing can see you.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sunken-way', 'south', 'the-lane-head', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sunken-way', 'west', 'the-cow-pasture', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sunken-way', 'east', 'the-well-green', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sunken-way', 'north', 'the-street-foot', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-well-green', 'door', 'The Well Green', 'A shelf of level grass with the village well in the middle of it — a stone ring, waist-high, capped with a slab somebody dragged on and left crooked. Under the slab the water is a long way down and perfectly still, and the bucket rope has rotted off at the windlass.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-well-green', 'west', 'the-sunken-way', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-well-green', 'north', 'the-village-pound', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-thorn-hedge', 'door', 'The Thorn Hedge', 'A hedge laid by hand — every stem half-cut and bent over and woven along, a craft that takes years to learn — and then left, so it has grown up out of its own weaving into a line of small crooked trees standing in a row with their old wounds healed over sideways. It marks a boundary nobody argues about now.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-thorn-hedge', 'south', 'the-old-assart', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-thorn-hedge', 'west', 'the-outer-scrub', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-thorn-hedge', 'east', 'the-ridge-and-furrow', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-thorn-hedge', 'north', 'the-far-furlong', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-ridge-and-furrow', 'door', 'The Ridge and Furrow', 'The ground here runs in long parallel waves, a stride from crest to crest, and if you walk across them you are climbing and dropping all the way and if you walk along them you are on the flat. It is ploughing. Somebody''s ox turned at the end of every one of these for a few hundred years, and the shape has outlasted them by a few hundred more.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ridge-and-furrow', 'west', 'the-thorn-hedge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ridge-and-furrow', 'south', 'the-cow-pasture', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ridge-and-furrow', 'east', 'the-street-foot', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ridge-and-furrow', 'north', 'the-common-field', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-street-foot', 'door', 'The Street Foot', 'Where the field stops and the houses start. There is no boundary except that the grass gives way to a hard rutted surface and the first walls stand up on your left. Somebody has been here more recently than the rest of it: a fire was lit against the gable end and put out badly, and the scorch is still black.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-street-foot', 'west', 'the-ridge-and-furrow', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-street-foot', 'south', 'the-sunken-way', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-street-foot', 'north', 'the-street', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-street-foot', 'east', 'the-village-pound', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-village-pound', 'door', 'The Village Pound', 'A round stone pen with a gate that still swings, built to hold animals found straying until their owner paid to have them back. It is four courses high and dry-laid and in better repair than anything with a roof on it. Whatever was last shut in here got out over the top.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-village-pound', 'west', 'the-street-foot', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-village-pound', 'south', 'the-well-green', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-far-furlong', 'door', 'The Far Furlong', 'The last strip before the wood, and the wood has been coming for it: birch saplings stand all across the top end in their hundreds, none of them older than a person, all of them winning. The plough-ridges are still there under the leaf-litter if you scuff it with a foot.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-far-furlong', 'south', 'the-thorn-hedge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-far-furlong', 'east', 'the-common-field', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-far-furlong', 'north', 'the-headland-baulk', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-common-field', 'door', 'The Common Field', 'The big field, open, no hedge anywhere in it, worked in strips by everybody at once and grazed by everybody''s stock after harvest. It has not been either since. What is left is a great quiet meadow that goes yellow-brown in a wind, and deer come out onto it in the evening because nothing here objects.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-common-field', 'west', 'the-far-furlong', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-common-field', 'south', 'the-ridge-and-furrow', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-common-field', 'east', 'the-street', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-common-field', 'north', 'the-croft-backs', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-street', 'door', 'The Street', 'The one street, running north, wide enough for two carts, with the crofts standing back off it behind their own low walls. The surface is stone where somebody laid stone and mud where nobody did. Every door in sight is shut. That is the thing you notice, and then cannot stop noticing: they were shut on the way out, by people who expected to want them shut.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-street', 'south', 'the-street-foot', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-street', 'west', 'the-common-field', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-street', 'north', 'the-street-cross', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-street', 'east', 'the-smithy-yard', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-smithy-yard', 'door', 'The Smithy Yard', 'A yard black underfoot with a century of hammer-scale trodden into it, and it will never grow anything again. There is a stone trough at the wall, cracked through and empty, and a heap of clinker gone half to earth, and the smell of old iron still coming up out of the ground when it rains.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-smithy-yard', 'west', 'the-street', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-smithy-yard', 'east', 'the-smithy', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-smithy-yard', 'north', 'the-reeves-yard', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-smithy', 'door', 'The Smithy', 'Inside, the roof holds and the light comes through the door and one wind-eye. The hearth is a stone box with a hood over it, the anvil block is still bolted down though the anvil went with somebody, and there is a wall of hooks with nothing on them. Everything is in its place. The place is just empty.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-smithy', 'west', 'the-smithy-yard', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-headland-baulk', 'door', 'The Headland Baulk', 'The turning-strip at the top of the furlongs, left unploughed so the team had somewhere to swing, and so kept as rough grass for three hundred years. It runs east and west like a green road that goes nowhere and was never meant to.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-headland-baulk', 'south', 'the-far-furlong', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-headland-baulk', 'east', 'the-croft-backs', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-headland-baulk', 'north', 'the-burnt-croft', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-croft-backs', 'door', 'The Croft Backs', 'Behind the houses: the long thin gardens that came with them, each one walled off from the next, all of them gone to nettle and currant and a few gaunt apple trees still fruiting out of habit. There are gaps in the back walls where people took the short way to the field, worn into the stone.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-croft-backs', 'west', 'the-headland-baulk', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-croft-backs', 'south', 'the-common-field', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-croft-backs', 'east', 'the-street-cross', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-croft-backs', 'north', 'the-chapel-green', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-street-cross', 'door', 'The Street Cross', 'The middle of the place: a stone cross on three steps, the head of it broken off level and the stump worn round. People met here, and were told things here, and the steps are dished where they sat. Somebody has scratched a tally into the bottom step, a great many strokes, and then stopped.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-street-cross', 'south', 'the-street', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-street-cross', 'west', 'the-croft-backs', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-street-cross', 'north', 'the-street-head', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-street-cross', 'east', 'the-reeves-yard', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-reeves-yard', 'door', 'The Reeve''s Yard', 'The biggest yard on the street, cobbled, with a barn on one side that has lost half its roof and a house on the other that has lost none of its. A reeve was a farmer the lord made responsible for everybody else''s work, which made him neither one thing nor the other, and he got a better house for it.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-reeves-yard', 'west', 'the-street-cross', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-reeves-yard', 'south', 'the-smithy-yard', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-reeves-yard', 'east', 'the-reeves-house', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-reeves-yard', 'north', 'the-north-croft', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-reeves-house', 'door', 'The Reeve''s House', 'Two rooms and a floor above, which was wealth here. The hearth is a proper one against a stone gable with a lintel and a hook still in it. There is a bench built into the wall, a bedstead frame with nothing on it, and a shuttered window that shuts. Somebody swept this floor before they left it.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-reeves-house', 'west', 'the-reeves-yard', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-reeves-house', 'up', 'the-reeves-loft', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-reeves-loft', 'door', 'The Reeve''s Loft', 'Up the ladder, under the thatch, where the family slept and the grain was kept dry. It is close and dark and warmer than downstairs by the whole width of a winter. The boards are sound. Along the wall, five pegs, and on the last of them a child''s coat gone stiff as bark.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-reeves-loft', 'down', 'the-reeves-house', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-burnt-croft', 'door', 'The Burnt Croft', 'One house did burn, and only one, a long time before the rest of it emptied — the walls stand to shoulder height with the fire''s black still on the inside face, and an ash tree has grown up through where the hearth was. Nobody built here again. Whatever the story was, everybody who knew it agreed about it.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-burnt-croft', 'south', 'the-headland-baulk', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-burnt-croft', 'east', 'the-chapel-green', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-burnt-croft', 'north', 'the-dead-orchard', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-chapel-green', 'door', 'The Chapel Green', 'A patch of level ground in front of the chapel, kept clear of graves and used for everything else — the ground is still bare in the middle from whatever it was used for. Two yews, both enormous, both older than the chapel, standing where yews always stand.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-chapel-green', 'west', 'the-burnt-croft', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-chapel-green', 'south', 'the-croft-backs', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-chapel-green', 'east', 'the-street-head', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-chapel-green', 'north', 'the-bare-chapel', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-street-head', 'door', 'The Street Head', 'The street ends at a gate in a wall, and past the gate the ground drops toward the sound of water. From here you can see the whole place at once, down the length of it, and count the roofs, and see that they are all still on.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-street-head', 'south', 'the-street-cross', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-street-head', 'west', 'the-chapel-green', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-street-head', 'east', 'the-north-croft', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-street-head', 'north', 'the-mill-lane', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-north-croft', 'door', 'The North Croft', 'The last yard before the wall, and the poorest — a house with a byre built onto the end of it under the same roof, so the family and the cow lived a partition apart and kept each other warm. The muck channel still runs out through the wall and away downhill.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-north-croft', 'west', 'the-street-head', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-north-croft', 'south', 'the-reeves-yard', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-north-croft', 'east', 'the-north-house', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-north-house', 'door', 'The North House', 'One room, and the byre through the gap where a partition was. The floor is beaten earth with a hearth-stone set in the middle of it and no chimney at all — the smoke went up through the thatch, and the underside of the thatch is black with it and hard as a shell, and that is what has kept the rain out this long.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-north-house', 'west', 'the-north-croft', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-bare-chapel', 'door', 'The Bare Chapel', 'Stone, and small, and the roof is stone too — the only stone roof for a very long way, which is why it is the only building here that will certainly still be standing in another hundred years. Everything inside that could be carried was carried out. What is left is a font cut from a single block, a stone bench along the north wall, and a door that shuts on the world and is thick enough to mean it.', 0, 1, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bare-chapel', 'south', 'the-chapel-green', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-dead-orchard', 'door', 'The Dead Orchard', 'The chapel''s orchard, and half of it is standing dead — bare grey trunks with the bark coming off in sheets — while the other half goes on flowering and fruiting out of the same soil for no reason anyone could explain. Windfalls rot in the grass under the living half every year, and something comes for them every night.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-dead-orchard', 'south', 'the-burnt-croft', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-mill-lane', 'door', 'The Mill Lane', 'Down off the shoulder of the hill on a made surface, laid with flat stones set on edge because a mill lane has to take a loaded cart in the wet. Alder starts on both sides as the ground goes soft, and you can hear water working somewhere below before you can see any.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-mill-lane', 'south', 'the-street-head', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-mill-lane', 'north', 'the-mill-dam', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-mill-dam', 'door', 'The Mill Dam', 'An earth bank thrown across the beck with a stone sluice through it, and behind the bank a long still pond gone half to reed. The sluice is shut, or shut enough — water goes over the top of the bank in a wide shallow sheet instead of through the gate, which is why the pond has stayed a pond and the wheel has stayed dry.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-mill-dam', 'south', 'the-mill-lane', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-mill-dam', 'west', 'the-mill', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-mill', 'door', 'The Mill', 'A tall narrow building with the beck under one end of it. Inside, the machinery is nearly all there: the great wooden gear, the shaft, the tun, the two stones lying face to face with a lifetime of flour still grey in the seams. It smells of meal and cold water. Nothing turns, because the sluice is shut.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-mill', 'east', 'the-mill-dam', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-mill', 'down', 'the-wheel-pit', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-wheel-pit', 'door', 'The Wheel Pit', 'Under the floor, where the wheel hangs in its slot with the dry channel beneath it. The wheel is oak and iron-shod and rotted through in three of its buckets, and it is enormous seen from below. The stone walls are green to head height where the water used to reach and dry above that. It is very dark down here and the beck talks the whole time on the other side of the sluice.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wheel-pit', 'up', 'the-mill', NULL);

-- the-bramble-margin: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bramble-margin', 'east', 'the-waste-edge', NULL);

-- the-sunken-ditch: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sunken-ditch', 'east', 'the-squatters-row', NULL);

-- the-lime-kiln: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lime-kiln', 'east', 'the-kiln-track', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-waste-edge', 'door', 'The Waste Edge', 'The road''s last bank falls away south into ground that was never worth anything: rush and sedge and thin sour grass, standing water in the low places all year, a scatter of thorn. Nobody enclosed it because nobody wanted it, and that is exactly why there are people''s leavings all over it.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-waste-edge', 'north', 'the-gap-in-the-trees', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-waste-edge', 'west', 'the-bramble-margin', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-waste-edge', 'east', 'the-turf-cutting', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-waste-edge', 'south', 'the-squatters-row', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-turf-cutting', 'door', 'The Turf Cutting', 'Long rectangular bites have been taken out of the ground here, each one a spade''s width and a spade''s depth, and the water has come up in the bottom of every one of them. Turf was fuel, and turf was walls, and this is where both came from. The cuts nearest the road are the newest and they are not new.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-turf-cutting', 'west', 'the-waste-edge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-turf-cutting', 'east', 'the-broom-scrub', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-turf-cutting', 'south', 'the-hurdle-yard', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-broom-scrub', 'door', 'The Broom Scrub', 'Broom has taken a dry rise in the middle of the wet, dense and green-stemmed and shoulder-high, and in summer the pods crack open in the heat with a sound like something small breaking. There are paths through it that are not wide enough for a person, and one that is.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-broom-scrub', 'west', 'the-turf-cutting', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-broom-scrub', 'east', 'the-marl-pit', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-broom-scrub', 'south', 'the-drying-green', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-marl-pit', 'door', 'The Marl Pit', 'A steep-sided hole dug out for the clay under the peat, which they spread on the fields to sweeten them. It is thirty feet across and the sides are sheer and the bottom is water. There is a way down the collapsed corner if you want it, and the cattle rail somebody put round the lip has fallen in.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-marl-pit', 'west', 'the-broom-scrub', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-marl-pit', 'south', 'the-empty-toft', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-marl-pit', 'down', 'the-marl-water', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-marl-water', 'door', 'The Marl Water', 'Down at the bottom of the pit, on a ledge of blue clay, with the water going away from your feet into a colour nothing else in the world is. It is cold down here out of the wind and completely out of sight of everything, and the sky is a circle a long way up. Things have fallen in and stayed.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-marl-water', 'up', 'the-marl-pit', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-squatters-row', 'door', 'The Squatters'' Row', 'Six dwellings in a line along the dry contour, none of them the same as the next: turf, hurdle, salvaged timber, one with a real stone gable somebody must have carried here piece by piece. There was a custom that if you could raise a roof between dusk and dawn and have smoke coming out of it by morning, the ground was yours. Somebody kept that agreement here, six times.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-squatters-row', 'north', 'the-waste-edge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-squatters-row', 'west', 'the-sunken-ditch', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-squatters-row', 'east', 'the-hurdle-yard', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-squatters-row', 'south', 'the-kiln-track', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-hurdle-yard', 'door', 'The Hurdle Yard', 'A working yard of woven hazel panels, dozens of them, stacked and leaning and some still standing in the lines they were set in. Hurdles were how you made a pen anywhere you needed one, and somebody here made them to sell. The half-finished one on the trestle has been half-finished a very long time.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hurdle-yard', 'west', 'the-squatters-row', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hurdle-yard', 'north', 'the-turf-cutting', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hurdle-yard', 'east', 'the-drying-green', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hurdle-yard', 'south', 'the-black-hut', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-drying-green', 'door', 'The Drying Green', 'Level ground with lines of low posts across it, and between the posts nothing now but the weather. Washing was dried here, and hides were pegged out here, and the two things went on side by side because the ground was common and nobody could stop either. The grass under the drying lines is a different green from the rest.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drying-green', 'west', 'the-hurdle-yard', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drying-green', 'north', 'the-broom-scrub', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drying-green', 'east', 'the-empty-toft', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drying-green', 'south', 'the-shallow-well', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-empty-toft', 'door', 'The Empty Toft', 'A house-sized rectangle of levelled ground with a low bank round it, and inside the bank not one stone left standing — the walls went to somebody else''s walls, the roof went for firewood, and what is left is the shape of a home printed on the ground like a coin under paper. There is a doorstep, still, worn hollow.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-empty-toft', 'west', 'the-drying-green', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-empty-toft', 'north', 'the-marl-pit', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-empty-toft', 'east', 'the-withy-rows', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-empty-toft', 'south', 'the-fever-graves', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-withy-rows', 'door', 'The Withy Rows', 'Willow grown as a crop: cut off at the ground every year so it throws up a fist of long straight rods, harvested for baskets and hurdles and eel-traps. Nobody has cut these in decades, so each stool has become a small mad tree of its own, forty trunks out of one root, and the rows are still perfectly straight underneath the chaos.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-withy-rows', 'west', 'the-empty-toft', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-withy-rows', 'south', 'the-scrub-end', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-kiln-track', 'door', 'The Kiln Track', 'A causeway of dumped stone and clinker across the wet, made so a cart could get west to the lime kiln in the wood without going in to the axle. It has sunk unevenly and it is a bad surface, but it is a surface, and it is the only way across this corner that does not involve your knees.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-kiln-track', 'north', 'the-squatters-row', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-kiln-track', 'west', 'the-lime-kiln', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-kiln-track', 'east', 'the-black-hut', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-kiln-track', 'south', 'the-bark-heap', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-black-hut', 'door', 'The Black Hut', 'Turf walls two feet thick, a roof of turf on rafters of bent alder, no window, and a door you go through bent double. Inside it is black — smoke-black, floor to roof, from a fire that had no chimney and did not need one. It is bone dry and it is warm the moment you are out of the wind, and there is old bracken bedding along one wall.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-black-hut', 'north', 'the-hurdle-yard', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-black-hut', 'west', 'the-kiln-track', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-shallow-well', 'door', 'The Shallow Well', 'Not a well so much as a hole with a barrel sunk in it — a common trick where the water sits close to the surface. The barrel staves are still sound in the wet and the water inside is clear and about three feet down and full of the sky. There is a hoof-print in the mud on every side of it.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-shallow-well', 'north', 'the-drying-green', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-shallow-well', 'east', 'the-fever-graves', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-shallow-well', 'south', 'the-hearth-stones', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-fever-graves', 'door', 'The Fever Graves', 'Twenty-odd low mounds in rows, unmarked except by the rushes growing greener over them, on ground outside every boundary there was. When something went through here quickly they buried the dead quickly and away from everyone, which is what this is. It is a tidier piece of ground than anything else on the common.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fever-graves', 'west', 'the-shallow-well', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fever-graves', 'north', 'the-empty-toft', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fever-graves', 'east', 'the-scrub-end', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fever-graves', 'south', 'the-thorn-corner', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-scrub-end', 'door', 'The Scrub End', 'The common gives out eastward into thorn and bramble and standing water with no way through that a person would choose. You can see a long way over the top of it and there is nothing to see: more of the same, going on until the light stops.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-scrub-end', 'west', 'the-fever-graves', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-scrub-end', 'north', 'the-withy-rows', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-bark-heap', 'door', 'The Bark Heap', 'Oak bark, stripped in long curls and stacked in a great heap to dry, worth more per cart than the timber it came off because the tanners could not work without it. The heap has slumped and gone to leaf-mould at the bottom and is still recognisably a heap at the top. It smells sharp and dry and faintly of tea.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bark-heap', 'north', 'the-kiln-track', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bark-heap', 'east', 'the-peelers-camp', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bark-heap', 'south', 'the-gorse-common', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-peelers-camp', 'door', 'The Peelers'' Camp', 'Where the bark-peelers lived for the six weeks of the year the sap was up and the bark would come away: a ring of lean-to shelters against a fallen trunk, a cooking pit, a rack for the tools. It was never meant to last past midsummer and it has lasted a great deal longer than that, because nobody came to take it down.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-peelers-camp', 'west', 'the-bark-heap', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-peelers-camp', 'east', 'the-hearth-stones', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-peelers-camp', 'south', 'the-warren-bank', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-hearth-stones', 'door', 'The Hearth Stones', 'Four hearths in open ground, each one a ring of stones with the fire''s red still baked into them, standing well apart in what was obviously an agreed arrangement. No walls anywhere. People camped here in numbers, more than once, and knew each other well enough to leave that much room and no more.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hearth-stones', 'west', 'the-peelers-camp', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hearth-stones', 'north', 'the-shallow-well', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hearth-stones', 'east', 'the-thorn-corner', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hearth-stones', 'south', 'the-warreners-lodge', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-thorn-corner', 'door', 'The Thorn Corner', 'The common''s east corner, where the thorn has been let go entirely and stands twice head height in a solid mass, with one path into it that has been kept open by something walking it. Blackthorn, mostly, which is the one that goes septic.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-thorn-corner', 'west', 'the-hearth-stones', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-thorn-corner', 'north', 'the-fever-graves', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-thorn-corner', 'south', 'the-lodge-yard', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-gorse-common', 'door', 'The Gorse Common', 'Gorse over the whole rise, dark green and armed to the last inch and flowering yellow in every month of the year, with tunnels through the bottom of it worn by things much lower than you. It burns hot and fast in a dry summer and comes back thicker. Nothing has burned it in a while.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-gorse-common', 'north', 'the-bark-heap', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-gorse-common', 'east', 'the-warren-bank', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-warren-bank', 'door', 'The Warren Bank', 'Dry sandy bank, south-facing, and worked from end to end with burrows — but the bank itself is man-made, a long earthwork raised and planted with sand specifically so rabbits would take to it. Rabbits were farmed here, not hunted. They have been managing the arrangement themselves for a long time now and there are a great many of them.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-warren-bank', 'west', 'the-gorse-common', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-warren-bank', 'north', 'the-peelers-camp', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-warren-bank', 'south', 'the-pillow-mounds', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-warreners-lodge', 'door', 'The Warrener''s Lodge', 'The one solid building on the common, and built solid for a reason: a warrener slept out here with the stock he was responsible for, alone, with people who wanted his rabbits on every side of him. Thick walls, a barred shutter, a door with three sockets for a bar, and a hearth. Inside it is dry and dim and smells of stone.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-warreners-lodge', 'north', 'the-hearth-stones', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-warreners-lodge', 'east', 'the-lodge-yard', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-warreners-lodge', 'up', 'the-lodge-loft', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-lodge-loft', 'door', 'The Lodge Loft', 'The floor above, reached by a ladder that can be pulled up after you, which is not an accident. A slit window on each of the four walls looks out over the whole warren, and that is what this room is for: sitting in the dark, seeing everything, and being seen by nothing.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lodge-loft', 'down', 'the-warreners-lodge', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-lodge-yard', 'door', 'The Lodge Yard', 'A walled yard behind the lodge with the nets and traps still hanging in it — long purse-nets gone to grey thread, and the hoops of things that were meant to be entered and not left. There is a stone slab at working height by the door, scrubbed white by weather now, and a drain cut in it.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lodge-yard', 'west', 'the-warreners-lodge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lodge-yard', 'north', 'the-thorn-corner', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-pillow-mounds', 'door', 'The Pillow Mounds', 'Long low rectangular banks laid out in a pattern across the grass, a stride high and twenty long, each one dug through with a channel — artificial burrows, made for the rabbits to take to. From the ground they look like graves for something the wrong shape. From the top of one you can see they are laid out in a comb.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-pillow-mounds', 'north', 'the-warren-bank', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-pillow-mounds', 'east', 'the-far-waste', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn) VALUES
  ('the-far-waste', 'door', 'The Far Waste', 'The common stops meaning anything here. The ground goes flat and wet and open and keeps going south with nothing on it but rush and sky and, a long way out, one thorn tree standing by itself with the wind bent into it. Nobody has put anything here. There is nothing here to put anything on.', 0, 0, 'den', 0);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-far-waste', 'west', 'the-pillow-mounds', NULL);
