-- Generated by scripts/build-rooms.mjs from: regions/east-road-1.rooms, regions/east-road-2.rooms, regions/east-road-3.rooms
-- 105 rooms, 212 exits. Do not hand-edit — regenerate from the source text.
-- Validated: every exit resolves, every exit has a return path (or is marked one-way),
-- no duplicate ids, no orphans, every room reachable from a gate.

-- the-old-road: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-old-road', 'east', 'the-thorn-gap', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-thorn-gap', 'door', 'The Thorn Gap', 'Someone has been at the thorn with a billhook, and not recently — the cut ends have healed over into knuckles of scar-wood, and the gap they left is narrower every year. Beyond it the paving picks up again, dressed and cambered and utterly unlike the country it crosses. The wall of thorn closes behind you like a held breath.', 0, 0, 'road', 0, 3, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-thorn-gap', 'west', 'the-old-road', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-thorn-gap', 'east', 'the-east-paving', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-east-paving', 'door', 'The East Paving', 'The stones here were laid better than the ones going west, and laid later. Each one is squared, bedded on a raft of rammed flint, and drained by a channel cut down the verge that still carries water when it rains. Two hundred years and it is barely dished. Whoever kept this end of the road, kept it well, and stopped all at once.', 0, 0, 'road', 0, 4, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-east-paving', 'west', 'the-thorn-gap', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-east-paving', 'east', 'the-toll-stone', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-toll-stone', 'door', 'The Toll Stone', 'A block of grey stone stands square in the verge with a slot cut in the top of it and a schedule of charges cut into the face — cart, beast, man on foot, man with a load. The slot goes down into a chamber nobody has opened. The rates are legible. There is nobody to pay.', 0, 0, 'road', 0, 5, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-toll-stone', 'west', 'the-east-paving', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-toll-stone', 'east', 'the-hollow-way', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-hollow-way', 'door', 'The Hollow Way', 'The road runs between low banks, and the banks are not worn — they are BUILT, revetted with dry stone that has kept its courses. The stonework has the same hand as the fortress walls, which tells you who paid for this and how far their arm reached. Ivy has got into the joints and is patiently taking them apart.', 0, 0, 'road', 0, 6, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hollow-way', 'west', 'the-toll-stone', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hollow-way', 'east', 'the-fifth-milestone', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hollow-way', 'north', 'the-road-kiln', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-road-kiln', 'door', 'The Lime Kiln', 'A stone bottle sunk into the bank, taller than a man inside, its mouth black and its throat white with old burn. Lime for the road''s mortar came out of here by the cartload. The last charge was never drawn: it sits in the belly of the kiln, fired and gone hard, a plug of stone that used to be stone.', 0, 0, 'road', 0, 6, 9);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-road-kiln', 'south', 'the-hollow-way', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-fifth-milestone', 'door', 'The Fifth Milestone', 'The same squat grey pillar as the one out west, the same weathered flat face — and this one is legible. FIVE, cut deep, and below it a distance in a measure nobody uses. The numbers run the other way from here. West of the fortress they count out; east of it, they count up.', 0, 0, 'road', 0, 7, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fifth-milestone', 'west', 'the-hollow-way', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fifth-milestone', 'east', 'the-carters-rest', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-carters-rest', 'door', 'The Carter''s Rest', 'A stone shelter set back off the verge, three walls and a roof of slabs, built for waiting out weather with an animal. The hearth in the corner has been used since the fortress fell — not often, and not lately, but the ash is layered and somebody swept it once. Wide enough for two carts. Empty.', 0, 1, 'road', 0, 8, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-carters-rest', 'west', 'the-fifth-milestone', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-carters-rest', 'east', 'the-broken-culvert', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-broken-culvert', 'door', 'The Broken Culvert', 'The road crosses a buried stream on a barrel arch, and the arch has dropped a stone. Water comes up through the paving on the low side and lies there. The subsidence is a foot deep and getting deeper, and the road, which has no one to mend it, has begun to go into the hole a wheel-rut at a time.', 0, 0, 'road', 0, 9, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-broken-culvert', 'west', 'the-carters-rest', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-broken-culvert', 'east', 'the-elm-avenue', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-elm-avenue', 'door', 'The Elm Avenue', 'Elms were planted down both verges in a straight line, at even spacing, by somebody who expected to be dead long before they came to anything. They came to something. Half are standing and half are down, and the standing ones close overhead so the road runs through a green tunnel with the light coming through it in coins.', 0, 0, 'road', 0, 10, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-elm-avenue', 'west', 'the-broken-culvert', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-elm-avenue', 'east', 'the-relay-house', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-elm-avenue', 'south', 'the-fallen-avenue', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-fallen-avenue', 'door', 'The Fallen Avenue', 'Three elms came down together in the same weather and nobody has cleared them. They lie across what used to be the drainage, and the water has spread out behind them into a long shallow pool that reflects the whole avenue upside down. The trunks are soft enough now to take a boot-print.', 0, 0, 'road', 0, 10, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fallen-avenue', 'north', 'the-elm-avenue', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-relay-house', 'door', 'The Relay House', 'A posting station: stable, yard, and a long low house with a hatch in the road-facing wall and a lamp above it that is lit. Fresh beasts were kept here for anyone carrying the fortress''s business east. The stalls are empty and swept. The hatch opens. Whatever the arrangement is, it has not lapsed, and nobody here will explain it.', 1, 0, 'road', 0, 11, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-relay-house', 'west', 'the-elm-avenue', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-relay-house', 'east', 'the-weighbridge', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-weighbridge', 'door', 'The Weighbridge', 'A plate of iron let into the paving, big enough for a cart and axle, with a slot at the side where the beam ran down into a pit. The mechanism is still in the pit, under water. The plate rings under your boots — one clean note, carrying much further than it should, announcing you to the whole length of the road.', 0, 0, 'road', 0, 12, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-weighbridge', 'west', 'the-relay-house', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-weighbridge', 'east', 'the-cut-bank', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-cut-bank', 'door', 'The Cut Bank', 'The road goes through a shoulder of hill instead of over it, in a cut with faces of raw chalk on both sides and rooks in the ledges. The chalk sweats. Flint comes out of the faces in courses like dark stitching, and there is a spoil-heap at the east end that has been there so long it has its own turf.', 0, 0, 'road', 0, 13, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cut-bank', 'west', 'the-weighbridge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cut-bank', 'east', 'the-sixth-milestone', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cut-bank', 'north', 'the-thorn-drop', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-sixth-milestone', 'door', 'The Sixth Milestone', 'SIX. Somebody has been keeping a tally on the back of this one, well away from the road-facing side: scratches in fives, hundreds of them, gone right round the pillar and started again. Whatever was being counted, it was counted patiently, over a long time, by somebody who came back.', 0, 0, 'road', 0, 14, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sixth-milestone', 'west', 'the-cut-bank', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sixth-milestone', 'east', 'the-drowned-ford', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-drowned-ford', 'door', 'The Drowned Ford', 'The stream the culvert was built to carry gets its own way here. It comes down off the north and crosses the road in a wide, stony, ankle-deep sheet, and the paving continues underneath it, visible and green. There are stepping stones for anyone too proud to wet their boots. Watercress grows thick on the downstream side.', 0, 0, 'road', 0, 15, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drowned-ford', 'west', 'the-sixth-milestone', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drowned-ford', 'east', 'the-fallen-elm', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drowned-ford', 'south', 'the-beck-mouth', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-fallen-elm', 'door', 'The Fallen Elm', 'The biggest of the avenue elms came down here, across the road, and was cut through rather than cleared — a slice the width of a cart taken out of the middle of it and the two halves left where they lie. The heartwood is a ruin of beetle-work. The rings, if you count them, run out well before the fortress did.', 0, 0, 'road', 0, 16, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fallen-elm', 'west', 'the-drowned-ford', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fallen-elm', 'east', 'the-verge-shrine', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-verge-shrine', 'door', 'The Verge Shrine', 'A niche the size of a bread-oven built into a roadside wall, with a stone shelf in it worn to a dip. Travellers left something here going out and something coming back. The shelf has a scatter on it now — a button, a tooth, a coin so worn it is just a disc — left by people who did not know the form and did it anyway.', 0, 0, 'road', 0, 17, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-verge-shrine', 'west', 'the-fallen-elm', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-verge-shrine', 'east', 'the-long-rise', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-long-rise', 'door', 'The Long Rise', 'The road stops being level. It is not a hill yet, only a tilt you notice in your legs before your eyes, and it goes on far enough that the tilt stops being a thing that ends. Looking back, the fortress is lower than you are. Looking forward, the country ahead of you is nothing but sky.', 0, 0, 'road', 0, 18, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-long-rise', 'west', 'the-verge-shrine', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-long-rise', 'east', 'the-chalk-cut', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-chalk-cut', 'door', 'The Chalk Cut', 'The engineers took the rise in a straight line, which meant cutting, and the cut is deep here — white walls twice a man''s height, the road a pale ribbon at the bottom of it. Sound behaves oddly. Anything that comes down the cut arrives before it should, and you hear yourself arriving too.', 0, 0, 'road', 0, 19, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-chalk-cut', 'west', 'the-long-rise', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-chalk-cut', 'east', 'the-seventh-milestone', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-seventh-milestone', 'door', 'The Seventh Milestone', 'SEVEN, and the pillar is leaning. The ground has crept under it — the whole hillside is moving downhill at the speed of stone, a hand''s breadth a century, and it has taken the milestone with it. It still points at the road. It is no longer beside the road it points at.', 0, 0, 'road', 0, 20, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-seventh-milestone', 'west', 'the-chalk-cut', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-seventh-milestone', 'east', 'the-tollkeepers-ruin', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-tollkeepers-ruin', 'door', 'The Tollkeeper''s Ruin', 'A second toll-house, out here where nobody would stop to be charged, gone to three courses of wall and a hearth full of nettles. The gate-post is still standing with the iron in it. Whatever this end of the writ was collecting, it was worth building for, and the building did not outlast the collecting by long.', 0, 0, 'road', 0, 21, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-tollkeepers-ruin', 'west', 'the-seventh-milestone', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-tollkeepers-ruin', 'east', 'the-hawthorn-narrows', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-hawthorn-narrows', 'door', 'The Hawthorn Narrows', 'Hawthorn has come in off both verges and met in the middle, and the road here is a tunnel a man wide with the paving still sound underfoot. The thorn is old, black-barked and thick as an arm. There is one way through and it is the way you are already going, and you would hear anything coming.', 0, 0, 'road', 0, 22, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hawthorn-narrows', 'west', 'the-tollkeepers-ruin', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hawthorn-narrows', 'east', 'the-drove-pound', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-drove-pound', 'door', 'The Drove Pound', 'A walled square off the verge, big enough to hold a herd for a night, with a water trough along one side fed by a lead pipe from the hill. This is where stock coming down off the drove was held before it went onto the paving, and where anything the road caught straying was put until somebody paid for it. The gate is off. The trough still runs.', 0, 0, 'road', 0, 23, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drove-pound', 'west', 'the-hawthorn-narrows', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drove-pound', 'east', 'the-cattle-grid', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-cattle-grid', 'door', 'The Cattle Grid', 'A pit floored with iron bars laid across the road, to stop stock coming down off the high ground and onto the paving. The drove comes in from the north here — a green lane, wide and hoof-cut, joining the road at a gate that has rotted off its hinges. The bars are still sound. Nothing has stopped anything in a long time.', 0, 0, 'road', 0, 24, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cattle-grid', 'west', 'the-drove-pound', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cattle-grid', 'east', 'the-open-stretch', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cattle-grid', 'north', 'the-grid-drop', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-open-stretch', 'door', 'The Open Stretch', 'The cuttings and the hedges give out and the road runs across the top of the world on an embankment, with the whole eastern country laid out beyond it: grey folds of hill, one on the next, going up. There is nothing to stand behind out here for a quarter of a mile in any direction.', 0, 0, 'road', 0, 25, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-open-stretch', 'west', 'the-cattle-grid', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-open-stretch', 'east', 'the-saddle-gap', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-saddle-gap', 'door', 'The Wind Gap', 'The road takes a saddle between two shoulders of hill, and the wind takes the saddle. It comes through hard enough to lean on and it does not stop. The grass here grows one way. Anything you say goes east whether you meant it to or not, and anything said east of you never arrives.', 0, 0, 'road', 0, 26, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-saddle-gap', 'west', 'the-open-stretch', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-saddle-gap', 'east', 'the-eighth-milestone', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-eighth-milestone', 'door', 'The Eighth Milestone', 'EIGHT — and this one has been dressed since. The old face is cut away and a new legend cut in its place, in a different hand, smaller and quicker: not a distance. A warning, or an instruction, in a language that used the same letters and not the same words. Nobody who could read it is left to ask.', 0, 0, 'road', 0, 27, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-eighth-milestone', 'west', 'the-saddle-gap', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-eighth-milestone', 'east', 'the-scarp-foot', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-scarp-foot', 'door', 'The Scarp Foot', 'The tilt ends the way a tilt ends: in a wall. Ahead of the road the ground stands up in a grey scarp, and the road, which has gone straight through everything else in its way, does not go through this. It turns. You can see the line it takes, a pale scratch cut diagonally up the face of the thing, and it is a long way up.', 0, 0, 'road', 0, 28, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-scarp-foot', 'west', 'the-eighth-milestone', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-scarp-foot', 'east', 'the-quarry-turn', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-scarp-foot', 'north', 'the-scarp-spring', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-scarp-foot', 'south', 'the-beck-stair', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-scarp-spring', 'door', 'The Scarp Spring', 'Water comes straight out of the foot of the scarp here, from a bed of gravel, at a rate that does not vary and a temperature that does not either. It is the cleanest thing for twenty rooms. Somebody has set a stone trough under it, and the trough is older than the road, and it is still full.', 0, 0, 'road', 0, 28, 9);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-scarp-spring', 'south', 'the-scarp-foot', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-quarry-turn', 'door', 'The Quarry Turn', 'The road doglegs to take the grade, and in the elbow of it is the quarry the road was built out of — a bite taken from the scarp, floored with chippings, walled in fresh grey stone that has never weathered because it never had the chance. The last blocks are still on the skids, dressed, squared, and waiting for a cart that is not coming.', 0, 0, 'road', 0, 29, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-quarry-turn', 'west', 'the-scarp-foot', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-quarry-turn', 'east', 'the-paving-end', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-paving-end', 'door', 'The Last Paving', 'The dressed stone ends. Not raggedly, not fallen away — it simply STOPS, in a clean straight edge across the road with the last course laid true, and beyond it the way ahead is a track cut into the hillside with a pick. This is the mark where the money ran out, or the men did, or the writ did.', 0, 0, 'road', 0, 30, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-paving-end', 'west', 'the-quarry-turn', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-paving-end', 'east', 'the-first-hairpin', NULL);

-- the-mass-grave: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-mass-grave', 'east', 'the-grave-verge', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-grave-verge', 'door', 'The Grave Verge', 'The pits stop at a line you can see from here — a change in the grass, greener and ranker on the fortress side, thin and grey beyond it. Past the line the ground has never been broken. A track leaves eastward along the edge of it, hoof-cut, going up, made by animals that were driven and men who were paid by the head.', 0, 0, 'road', 0, 3, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-grave-verge', 'west', 'the-mass-grave', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-grave-verge', 'east', 'the-sheep-creep', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-sheep-creep', 'door', 'The Sheep Creep', 'The lane narrows to a gap between two banks where the flock had to file through one at a time — a counting point, worn down to bedrock by however many hundred thousand feet. The stone is polished like a step. Nothing has been counted through here in a long while and the bedrock has not begun to forget.', 0, 0, 'road', 0, 4, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sheep-creep', 'west', 'the-grave-verge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sheep-creep', 'east', 'the-first-fold', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-first-fold', 'door', 'The First Fold', 'A stone fold off the north side of the lane, four walls and one gap, built to hold a flock overnight against whatever came off the hill. The walls are chest-high and dry-laid and still true. There is no roof and there never was. Wool is still caught in the joints on the windward side.', 0, 1, 'road', 0, 5, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-first-fold', 'west', 'the-sheep-creep', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-first-fold', 'east', 'the-drove-green', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-drove-green', 'door', 'The Green Lane', 'A hundred feet of grass running between two hedge-banks, wide enough to move a herd along without losing any of it into the crops that used to be either side. There are no crops now. The lane is the only thing on this hillside that still remembers what it was for, and it remembers it in its shape.', 0, 0, 'road', 0, 6, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drove-green', 'west', 'the-first-fold', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drove-green', 'east', 'the-hollow-oak', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-hollow-oak', 'door', 'The Hollow Oak', 'An oak stands alone at a bend in the lane, so old it has gone hollow and so hollow that the inside of it is a room. There is a scatter of dry leaves in there and a bed''s worth of flat floor. Generations of drovers have cut their marks into the rim of the opening and every one of them is healed over into scar.', 0, 0, 'road', 0, 7, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hollow-oak', 'west', 'the-drove-green', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hollow-oak', 'east', 'the-drovers-cairn', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hollow-oak', 'north', 'the-oak-hollow', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-oak-hollow', 'door', 'The Inside of the Oak', 'Wood all round, close, dry, and warmer than outdoors by a real margin. The light comes in through the split and nothing else does. It smells of tannin and old animal. Somebody stacked kindling against the far curve and left it, and it is still stacked, and it is still dry.', 0, 1, 'road', 0, 7, 7);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-oak-hollow', 'south', 'the-hollow-oak', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-drovers-cairn', 'door', 'The Drover''s Cairn', 'A heap of stones at the highest point on this stretch, waist-high and growing: everyone who came past put one on. It has been growing so long the ones at the bottom have gone into the ground. There is no name on it and it is not a grave. It is a record of how many people have been this way, and it is very large.', 0, 0, 'road', 0, 8, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drovers-cairn', 'west', 'the-hollow-oak', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drovers-cairn', 'east', 'the-wether-slope', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-wether-slope', 'door', 'The Wether Slope', 'The hillside opens out into rough pasture, hard grazing, gorse in the hollows and a wind that never entirely stops. The old lynchets run across it in steps — plough terraces, from when this was worth ploughing. You can see the paved road far below on the right, running its dead straight line through everything.', 0, 0, 'road', 0, 9, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wether-slope', 'west', 'the-drovers-cairn', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wether-slope', 'east', 'the-broken-fold', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-broken-fold', 'door', 'The Broken Fold', 'The second fold, and this one has lost its west wall — pushed out from the inside, the stones lying in a fan across the grass where something big went through them rather than round. The other three walls are perfect. The gap has not been mended, and by the state of the grass in it, nobody has tried.', 0, 0, 'road', 0, 10, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-broken-fold', 'west', 'the-wether-slope', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-broken-fold', 'east', 'the-shepherds-bothy', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-shepherds-bothy', 'door', 'The Shepherd''s Bothy', 'A hut of turf on a stone footing, dug into the slope with its back to the weather, low enough that you go in bent. A plank bed, a hearth-slab, a shelf. The roof is holding. It was a summer place for one man and a dog, and it is still exactly that, minus the man and the dog.', 0, 1, 'road', 0, 11, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-shepherds-bothy', 'west', 'the-broken-fold', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-shepherds-bothy', 'east', 'the-bothy-spring', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-bothy-spring', 'door', 'The Spring Head', 'Water rises here in a basin of clean gravel and runs off downhill in a thread you could step over. This is why the bothy is where it is, and the fold, and the lane. Everything on this hillside is arranged around a hole in the ground the width of a hat.', 0, 0, 'road', 0, 12, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bothy-spring', 'west', 'the-shepherds-bothy', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bothy-spring', 'east', 'the-high-gorse', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-high-gorse', 'door', 'The Gorse Brake', 'Gorse has taken this whole shoulder — old gorse, ten feet of it, black-stemmed underneath and hard yellow on top, growing so thick that the lane through it is a corridor with walls. It is in flower. It is always in flower. The smell of it in the sun is coconut and the reality of it is a wall of needles.', 0, 0, 'road', 0, 13, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-high-gorse', 'west', 'the-bothy-spring', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-high-gorse', 'east', 'the-burnt-brake', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-high-gorse', 'south', 'the-thorn-drop', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-burnt-brake', 'door', 'The Burnt Brake', 'Somebody fired the gorse here, to bring the grazing back, and it worked: black stems and green shoots and the ground underneath still sooty. The burn is recent enough to smell. Whoever did it stopped when the wind turned, which you can see from the ragged edge where the fire went out on its own.', 0, 0, 'road', 0, 14, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-burnt-brake', 'west', 'the-high-gorse', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-burnt-brake', 'east', 'the-marker-stone', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-marker-stone', 'door', 'The Marker Stone', 'A standing stone at the parting of two ways — grey, lichened, twice a man''s height, and older than every other made thing in sight by a margin that is hard to think about. The drove goes round it. The drove has always gone round it. Somebody has cut a small neat cross into the base of it, recently, as a precaution.', 0, 0, 'road', 0, 15, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-marker-stone', 'west', 'the-burnt-brake', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-marker-stone', 'east', 'the-high-common', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-thorn-drop', 'door', 'The Thorn Drop', 'The hillside falls away south of the marker in a scramble of thorn and loose stone, and there is a path of sorts down it — a sheep-track, not a road, taking the drop in switchbacks a man can just about use with his hands free. The paving is a long way down and clearly visible. It would be a bad descent in the wet.', 0, 0, 'road', 0, 13, 9);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-thorn-drop', 'north', 'the-high-gorse', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-thorn-drop', 'south', 'the-cut-bank', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-high-common', 'door', 'The High Common', 'Unfenced grazing that runs to the horizon in every direction that is not down. Nothing grows above ankle height. There are no walls, no trees and no shelter of any kind, and the wind has an unbroken run at you from the east, off ground you have not seen yet and can already feel is higher.', 0, 0, 'road', 0, 16, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-high-common', 'west', 'the-marker-stone', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-high-common', 'east', 'the-lapwing-flat', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-lapwing-flat', 'door', 'The Lapwing Flat', 'A shallow saucer of wet ground on the common, rush-grown, with standing water in the middle of it that never quite dries. Birds nest on the open ground here and go up in a body if anything crosses it, tumbling and calling. They will tell everything on this hillside exactly where you are.', 0, 0, 'road', 0, 17, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lapwing-flat', 'west', 'the-high-common', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lapwing-flat', 'east', 'the-common-boundary', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-common-boundary', 'door', 'The Old Boundary', 'A bank and ditch runs north to south across the common, straight, with a gap in it where the drove goes through. It is not a defence — too low, too long. It divided somebody''s land from somebody else''s, and both of them are gone, and the line they argued about is the most permanent thing up here.', 0, 0, 'road', 0, 18, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-common-boundary', 'west', 'the-lapwing-flat', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-common-boundary', 'east', 'the-wind-scoured-ridge', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-wind-scoured-ridge', 'door', 'The Wind-Scoured Ridge', 'The lane runs the spine of the ridge and the wind runs it too, hard, from the east. The turf is cropped to a mat and the exposed stone is polished. From here you can see the drove behind you, the paved road below you, and ahead of you the country beginning to stand up in earnest.', 0, 0, 'road', 0, 19, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wind-scoured-ridge', 'west', 'the-common-boundary', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wind-scoured-ridge', 'east', 'the-hanging-fold', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-hanging-fold', 'door', 'The Hanging Fold', 'The last of the folds, built on a shelf with a drop off the south side of it, so that a man could hold a flock against the hill and the hill did the rest of the work. The wall along the drop is the highest and the best-built. Somebody understood exactly how much they had to do and did precisely that much.', 0, 1, 'road', 0, 20, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hanging-fold', 'west', 'the-wind-scoured-ridge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hanging-fold', 'east', 'the-hare-ground', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-hare-ground', 'door', 'The Hare Ground', 'Open, stony, and cropped short, and it is full of forms — hollows in the grass the size and shape of a crouched animal, dozens of them, most of them cold. Whatever uses this ground uses it in numbers and would rather run than hide. The stones underfoot are all one size, as though the ground had been sieved.', 0, 0, 'road', 0, 21, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hare-ground', 'west', 'the-hanging-fold', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hare-ground', 'east', 'the-fallen-dyke', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-fallen-dyke', 'door', 'The Fallen Wall', 'A dry-stone wall crosses the drove and has come down for thirty feet, the stones lying where they rolled. It has been down long enough to have grass in it. Rebuilding it would be two days'' work for one man and nobody has spent them, and past a certain point a wall down is just a wall of stones on the ground.', 0, 0, 'road', 0, 22, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fallen-dyke', 'west', 'the-hare-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fallen-dyke', 'east', 'the-drove-head', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-drove-head', 'door', 'The Drove Head', 'The lane widens into a funnel — the shape of ground that was used to hold and sort a herd before putting it down onto the road. There are the ghosts of hurdles in the turf, and a mounting block, and a slot in the bank where a gate hung. Below and ahead of you, the paving comes back into sight.', 0, 0, 'road', 0, 23, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drove-head', 'west', 'the-fallen-dyke', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drove-head', 'east', 'the-grid-lane', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-grid-lane', 'door', 'The Grid Lane', 'The last of the green way, dropping steeply between banks toward the iron and the paving. Hoof-cut so deep that the banks are over your head at the bottom of it, and wet at the foot where everything that comes down here brings water with it. The drove ends the way it started: as a gap between two banks that things were driven through.', 0, 0, 'road', 0, 24, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-grid-lane', 'west', 'the-drove-head', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-grid-lane', 'south', 'the-grid-drop', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-grid-drop', 'door', 'The Grid Drop', 'The last of the green way tips off the shoulder and drops toward the paving in one steep pitch, banks over your head on both sides, the ground underfoot churned to a stair by everything that has ever been driven down it. You can hear the road before you can see it. Nothing coming down here can stop before the bottom.', 0, 0, 'road', 0, 24, 9);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-grid-drop', 'north', 'the-grid-lane', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-grid-drop', 'south', 'the-cattle-grid', NULL);

-- sally-port: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('sally-port', 'east', 'the-postern-ditch', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-postern-ditch', 'door', 'The Postern Ditch', 'The ditch that took the sally port''s water runs east along the foot of the wall, revetted at first and then not. It is a stride across and knee-deep in leaf-rot, and it goes where the wall goes and then keeps going after the wall stops. Anybody leaving the fortress in this ditch would not be seen doing it.', 0, 0, 'road', 0, 1, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-postern-ditch', 'west', 'sally-port', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-postern-ditch', 'south', 'the-drain-mouth', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-drain-mouth', 'door', 'The Drain Mouth', 'The revetting ends in a stone arch the height of a crouching man, and everything the fortress ever put down a drain has come out of it. The water leaving is clearer than the water arriving, which is the one good thing you can say about the ground between. Past the arch the ditch has cut its own channel and become a stream.', 0, 0, 'road', 0, 1, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drain-mouth', 'north', 'the-postern-ditch', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drain-mouth', 'east', 'the-postern-carr', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-postern-carr', 'door', 'The Alder Carr', 'Alder grows in standing water and this is where it does it: a wet wood of thin grey stems out of black ground, none of them thick enough to sit on, all of them exactly as far apart as each other. The footing is a guess. There is a way through and it is marked by the fact that somebody''s boots have been this way and the mud remembers.', 0, 0, 'road', 0, 2, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-postern-carr', 'west', 'the-drain-mouth', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-postern-carr', 'east', 'the-stepping-stones', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-stepping-stones', 'door', 'The Stepping Stones', 'Eight flat slabs set in the beck at a stride''s spacing, laid by somebody who knew the stride of a loaded man. Two have shifted. The water goes over them in a smooth lip and drops a hand''s breadth on the far side, and the noise it makes is enough to cover a conversation held quietly on the bank.', 0, 0, 'road', 0, 3, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-stepping-stones', 'west', 'the-postern-carr', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-stepping-stones', 'east', 'the-withy-beds', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-withy-beds', 'door', 'The Withy Beds', 'Willow grown in stools and cut on a rotation, for baskets and hurdles and eel traps — and the rotation stopped, so the stools have thrown rods twenty feet high and gone over under their own weight. The beds are a thicket now. The stools underneath are still alive and would still cut, if anybody wanted a basket.', 0, 0, 'road', 0, 4, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-withy-beds', 'west', 'the-stepping-stones', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-withy-beds', 'east', 'the-trap-line', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-beck-mouth', 'door', 'The Beck Mouth', 'The beck comes down out of the north here to join its own valley, running out of a stony gulley too steep to be worth following far. The paving crosses it a little way up at a ford you can hear from here. This is where the low way and the road are nearest to each other, and neither of them acknowledges it.', 0, 0, 'road', 0, 15, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-beck-mouth', 'south', 'the-hatchpool', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-beck-mouth', 'north', 'the-drowned-ford', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-trap-line', 'door', 'The Eel Traps', 'A line of woven traps set into a weir of stakes across the beck, mouth upstream, exactly as they were set. The withies have gone soft and the frames have gone green but the arrangement is intact and it is still, technically, fishing. Something has been at the far end of the line and made a mess of two of them.', 0, 0, 'road', 0, 5, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-trap-line', 'west', 'the-withy-beds', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-trap-line', 'east', 'the-mill-leat', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-mill-leat', 'door', 'The Mill Leat', 'The beck is taken off into a cut channel here — dead straight, stone-sided, running level along the hillside while the natural stream drops away below it. It is a piece of engineering as good as anything on the paved road and it was built for one purpose, which is to arrive at the top of a wheel.', 0, 0, 'road', 0, 6, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-mill-leat', 'west', 'the-trap-line', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-mill-leat', 'east', 'the-drowned-mill', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-drowned-mill', 'door', 'The Drowned Mill', 'The leat arrives, the wheel is still on its axle, and the wheel is half under water because the tail-race silted up and the pond backed into the building. The ground floor is a pool. The millstones are in it, one flat and one on edge against the wall, and the water is clear enough to read the dressing on them.', 0, 0, 'road', 0, 7, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drowned-mill', 'west', 'the-mill-leat', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drowned-mill', 'east', 'the-millpond', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drowned-mill', 'up', 'the-mill-loft', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-mill-loft', 'door', 'The Mill Loft', 'Above the water: a plank floor, a hoist beam through the gable, and a slot in the boards where the sacks went down. Dry, out of the wind, and reachable only by a ladder that is still sound. Somebody has slept up here — there is a nest of sacking in the corner and it has been shaken out, not just dropped.', 0, 1, 'road', 0, 6, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-mill-loft', 'down', 'the-drowned-mill', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-millpond', 'door', 'The Millpond', 'A held sheet of water behind a dam of earth and stone, wide, still, and much deeper than it looks. The dam is sound. Fish rise on it in the evening and rings go out across the whole of it and meet. Nothing on this water moves quickly and nothing on the bank does either.', 0, 0, 'road', 0, 8, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-millpond', 'west', 'the-drowned-mill', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-millpond', 'east', 'the-dam-walk', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-dam-walk', 'door', 'The Dam Walk', 'The top of the dam, a path of turf over stone with the pond on one hand at your knee and the drop to the tail-race on the other. It is wide enough for a cart and there are wheel-marks. In the middle there is a sluice with a rack and pinion on it, seized in the open position, and the noise of the water going through it fills everything.', 0, 0, 'road', 0, 9, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-dam-walk', 'west', 'the-millpond', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-dam-walk', 'east', 'the-tail-race', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-tail-race', 'door', 'The Tail-Race', 'Below the dam the water comes out fast and cold in a stone channel and then loses its manners and goes back to being a beck. The channel is slick and the sides are sheer for thirty feet. What comes down here arrives quickly. There is a footbridge of two planks, and one of them is new.', 0, 0, 'road', 0, 10, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-tail-race', 'west', 'the-dam-walk', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-tail-race', 'east', 'the-osier-island', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-osier-island', 'door', 'The Osier Island', 'The beck splits round a long low island of gravel and willow, joins itself again, and carries on. The island is a few strides across at the widest and it is the driest ground for some way. Somebody has had a fire on it. The stones of the ring are still stacked and the ash under them is old and dry.', 0, 1, 'road', 0, 11, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-osier-island', 'west', 'the-tail-race', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-osier-island', 'east', 'the-flood-mead', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-flood-mead', 'door', 'The Flood Meadow', 'Level ground either side of the water, grazed short, with the old flood-channels still legible as green scars running down it. It floods on purpose — floods, drops its silt, and grows the best grass in the country. It has not been mown in a long while and the grass is up past the knee and full of seed.', 0, 0, 'road', 0, 12, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-flood-mead', 'west', 'the-osier-island', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-flood-mead', 'east', 'the-cattle-drink', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-cattle-drink', 'door', 'The Cattle Drink', 'A shelving place in the bank, hard-bottomed and churned, where stock came down off the meadow to water. The mud holds prints and holds them a long time. Most of what is written here is hoof. Some of it is not, and the some-of-it-is-not goes down to the water and comes back up the same way.', 0, 0, 'road', 0, 13, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cattle-drink', 'west', 'the-flood-mead', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cattle-drink', 'east', 'the-marl-hole', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-marl-hole', 'door', 'The Marl Hole', 'A pit dug into the meadow''s edge for the lime-rich clay under it, spread on fields to sweeten them. Nobody filled it in. It has taken water and gone a colour that is not quite green, with steep sides of grey clay that would be very difficult to climb out of in a hurry.', 0, 0, 'road', 0, 14, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-marl-hole', 'west', 'the-cattle-drink', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-marl-hole', 'east', 'the-hatchpool', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-hatchpool', 'door', 'The Hatchpool', 'A deep still pool below an old hatch in the bank, where the water turns slowly and goes down further than the light does. This is where the beck keeps its fish and everything that eats fish knows it. The stonework round the hatch is dressed and squared and belongs to the same century as the road.', 0, 0, 'road', 0, 15, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hatchpool', 'west', 'the-marl-hole', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hatchpool', 'east', 'the-plank-crossing', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hatchpool', 'north', 'the-beck-mouth', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-plank-crossing', 'door', 'The Plank Crossing', 'Two elm planks, bolted, on stone abutments, spanning the beck where the valley starts to narrow. It carries one person at a time and lets them know about it. The abutments are far better than the planks and have clearly held three or four sets of them, each in its turn, going back a long way.', 0, 0, 'road', 0, 16, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-plank-crossing', 'west', 'the-hatchpool', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-plank-crossing', 'east', 'the-hanging-wood', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-hanging-wood', 'door', 'The Hanging Wood', 'The valley sides steepen and close in and grow ash and yew out of near-vertical ground, so the wood is above you as much as beside you. Very little light gets down. The beck runs loud in the bottom over stone, and the noise fills the whole cleft and makes anything else in it impossible to hear.', 0, 0, 'road', 0, 17, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hanging-wood', 'west', 'the-plank-crossing', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hanging-wood', 'east', 'the-force', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-force', 'door', 'The Force', 'The beck comes off a lip of hard rock in a single fall twice a man''s height into a black pool, and the sound of it inside the cleft is enormous. The rock behind the fall is undercut and there is dry ground back there, and the spray keeps a green fur of moss on everything within reach of it.', 0, 0, 'road', 0, 18, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-force', 'west', 'the-hanging-wood', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-force', 'east', 'the-scree-run', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-force', 'down', 'the-fall-shelter', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-fall-shelter', 'door', 'Behind the Fall', 'A shelf of dry rock behind the falling water, wide enough to sit on, cold, and loud past the point of usefulness. Nothing outside can hear anything in here and nothing in here can hear anything outside, which cuts both ways and always has. The wall at the back is scratched all over with tallies.', 0, 1, 'road', 0, 19, 13);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fall-shelter', 'up', 'the-force', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-scree-run', 'door', 'The Scree Run', 'Above the force the valley gives up being a valley. Loose stone comes down off the north side in a fan that the beck cuts through, and the way on is up the edge of it on ground that moves under you a little with every step. The paving is visible again above and to the north, cut across the face of the scarp.', 0, 0, 'road', 0, 19, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-scree-run', 'west', 'the-force', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-scree-run', 'east', 'the-otter-holt', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-otter-holt', 'door', 'The Otter Holt', 'The bank on the north side is undercut and there is a way into it under the roots of an alder — a worn slide of mud going down to the water and back up, used often and used recently. Whatever keeps this holt eats fish here and leaves the heads. The valley is narrowing, the sides are steepening, and there is nowhere to go but on.', 0, 0, 'road', 0, 20, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-otter-holt', 'west', 'the-scree-run', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-otter-holt', 'east', 'the-gill-foot', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-gill-foot', 'door', 'The Gill Foot', 'The beck''s valley closes to a gill — a cleft in the hillside with water in the bottom of it and no floor to speak of on either side. You walk in the stream because there is nowhere else to walk. The stones are round, the water is over the ankle, and the noise of it comes back off both walls at once.', 0, 0, 'road', 0, 21, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-gill-foot', 'west', 'the-otter-holt', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-gill-foot', 'east', 'the-gill-pot', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-gill-pot', 'door', 'The Black Pool', 'A pot the water has drilled into solid rock over an unhurried number of centuries, wider at the bottom than at the top and dark all the way down. The way past is a ledge on the north wall, dry, a stride wide, worn smooth. Anything that goes in here is not coming out.', 0, 0, 'road', 0, 22, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-gill-pot', 'west', 'the-gill-foot', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-gill-pot', 'east', 'the-rowan-gill', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-rowan-gill', 'door', 'The Rowan Gill', 'Rowans grow out of the gill walls at angles no tree should manage, roots down into the cracks, berries hanging over the water in bunches the colour of a wound. Nothing browses up here, so the low branches are as full as the high ones. In the wet the whole cleft smells of bruised leaf.', 0, 0, 'road', 0, 23, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rowan-gill', 'west', 'the-gill-pot', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rowan-gill', 'east', 'the-sunken-alders', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-sunken-alders', 'door', 'The Sunken Alders', 'The gill opens into a flat of black peaty ground with alders standing in water to the knee, drowned by something the beck did further up and never undone. Half of them are dead and still standing. The way through is a line of stumps cut flat on purpose, and they are just far enough apart to be a decision each time.', 0, 0, 'road', 0, 24, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sunken-alders', 'west', 'the-rowan-gill', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sunken-alders', 'east', 'the-gill-narrows', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-gill-narrows', 'door', 'The Gill Narrows', 'The walls close until a man with a pack goes through sideways, and the beck goes through the same gap under pressure and comes out the far side white. Four strides of squeeze and then it opens again. There is a jam of wood wedged at head height where a flood put it, which tells you how high this gets, and how fast.', 0, 0, 'road', 0, 25, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-gill-narrows', 'west', 'the-sunken-alders', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-gill-narrows', 'east', 'the-shepherds-ford', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-shepherds-ford', 'door', 'The Shepherd''s Ford', 'Gravel, shallow water, and a crossing wide enough to take a flock — the one place in the gill where the sides lie back and the water spreads out thin. Stone flags were laid in the bed here and most are still where they were put. The drove is somewhere above and north of you, and this is where it came down to drink.', 0, 0, 'road', 0, 26, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-shepherds-ford', 'west', 'the-gill-narrows', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-shepherds-ford', 'east', 'the-spring-line', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-spring-line', 'door', 'The Spring Line', 'Water comes out of the hillside all along this stretch in a dozen separate threads, at the exact height where the rock changes, and the whole slope is wet and hung with moss because of it. The beck below you is made here, out of nothing, in front of you. The ground gives underfoot everywhere the stone does not show.', 0, 0, 'road', 0, 27, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-spring-line', 'west', 'the-shepherds-ford', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-spring-line', 'east', 'the-beck-head', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-beck-head', 'door', 'The Beck Head', 'The last and highest of the springs, in a hollow of clean gravel, with a stone trough set under the flow by somebody who came this way often enough to want one. Above it the scarp stands up grey, and the paved road is a pale scratch across the face of it. The low way ends at the beginning of the water it has been following all day.', 0, 0, 'road', 0, 28, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-beck-head', 'west', 'the-spring-line', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-beck-head', 'north', 'the-beck-stair', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-beck-stair', 'door', 'The Beck Stair', 'Steps cut into the bank between the spring and the road above — not engineering, just somebody''s mattock, one tread at a time, and then a hundred years of boots making them theirs. Two dozen of them, steep, and slick on the fourth from the top where the spring runs across it.', 0, 0, 'road', 0, 28, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-beck-stair', 'south', 'the-beck-head', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-beck-stair', 'north', 'the-scarp-foot', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-first-hairpin', 'door', 'The First Hairpin', 'The track leaves the paving''s last dressed course and begins to climb the scarp face in a hairpin cut into the rock, wide enough for one cart and revetted on the outside with dry stone that somebody trusted. The drop on the open side is not sheer and would not need to be. The gradient is instantly hard work.', 0, 0, 'road', 0, 31, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-first-hairpin', 'west', 'the-paving-end', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-first-hairpin', 'east', 'the-second-hairpin', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-second-hairpin', 'door', 'The Second Hairpin', 'The track doubles back on itself, and from the elbow you can see the whole of the first hairpin below you and the whole of the road beyond it running west until it goes into haze. The fortress is a grey mark on the flat. From up here the country you came through looks small and entirely walked-over.', 0, 0, 'road', 0, 32, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-second-hairpin', 'west', 'the-first-hairpin', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-second-hairpin', 'east', 'the-cutting-ledge', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-cutting-ledge', 'door', 'The Cutting Ledge', 'A shelf blasted and picked out of the face, running level for a while, with the rock overhanging on one side and nothing at all on the other. Drill marks in the stone, hand-sunk, at even spacing. Somebody stood on rope to make this and was paid to and did the work properly.', 0, 0, 'road', 0, 33, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cutting-ledge', 'west', 'the-second-hairpin', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cutting-ledge', 'east', 'the-third-hairpin', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-third-hairpin', 'door', 'The Third Hairpin', 'Higher, colder, and the wind has found you again. The dry-stone revetting on the outside of this bend has gone — pushed out and down, taking a bite of the track with it — and what is left is two-thirds of a width and a long view of where the rest of it went.', 0, 0, 'road', 0, 34, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-third-hairpin', 'west', 'the-cutting-ledge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-third-hairpin', 'east', 'the-rope-post', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-rope-post', 'door', 'The Rope Post', 'An iron post let into the rock at the outside of the worst of the traverse, with a ring in the top of it worn shiny and thin. A rope ran from here to another post further on so that people could go along the bad stretch with one hand on something. The rope is not there. The posts are.', 0, 0, 'road', 0, 35, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rope-post', 'west', 'the-third-hairpin', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rope-post', 'east', 'the-shelter-stone', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-shelter-stone', 'door', 'The Shelter Stone', 'A slab the size of a cottage has come off the face at some point and landed leaning, and the space under it is dry, out of the wind, and floored with old bracken somebody carried up here. This is the halfway house of the climb and everybody who has ever done the climb has known about it.', 0, 1, 'road', 0, 36, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-shelter-stone', 'west', 'the-rope-post', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-shelter-stone', 'east', 'the-scarp-top', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-scarp-top', 'door', 'The Scarp Top', 'The track comes over the lip and the gradient lets go all at once. Behind and below is everything: the road, the drove on its shoulder, the beck''s valley cut into the green, and the fortress right at the end of it. Ahead is a shelf of high moor, and beyond that, standing up out of it, the real thing.', 0, 0, 'road', 0, 37, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-scarp-top', 'west', 'the-shelter-stone', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-scarp-top', 'east', 'the-high-shelf', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-high-shelf', 'door', 'The High Shelf', 'Peat, cotton-grass and standing water, running level for a long way at a height where nothing much grows and everything that does grows flat. The track is a line of laid stones across it, sunk and half-swallowed, and the only reason it is still findable is that somebody put it a foot deeper than it needed to be.', 0, 0, 'road', 0, 38, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-high-shelf', 'west', 'the-scarp-top', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-high-shelf', 'east', 'the-peat-cuttings', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-peat-cuttings', 'door', 'The Peat Cuttings', 'The moor has been cut in long trenches, black-walled and water-floored, with the turfs stacked in herringbone to dry beside them. The stacks are still standing. The peat in them is still good. Whoever cut it meant to come back for it before winter and the winter in question was a very long time ago.', 0, 0, 'road', 0, 39, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-peat-cuttings', 'west', 'the-high-shelf', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-peat-cuttings', 'east', 'the-boundary-cairn', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-boundary-cairn', 'door', 'The Boundary Cairn', 'A cairn on the flat, man-high, carefully built rather than heaped, with a flat stone on top and a hollow in the flat stone. It marks the edge of something. On the far side of it the track stops being maintained in any sense at all and is only the place where feet have gone.', 0, 0, 'road', 0, 40, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-boundary-cairn', 'west', 'the-peat-cuttings', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-boundary-cairn', 'east', 'the-watershed', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-watershed', 'door', 'The Watershed', 'The high point, and you can tell because the water tells you: the runnels on the near side go back the way you came and the runnels on the far side go on. Everything you have drunk since the fortress came off this ground. Everything ahead drains somewhere else entirely.', 0, 0, 'road', 0, 41, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-watershed', 'west', 'the-boundary-cairn', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-watershed', 'east', 'the-first-sight', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-first-sight', 'door', 'The First Sight', 'The moor drops away and the whole east opens up at once, and it is water. A sheet of it filling the valley floor from one wall of hill to the other, grey and enormous and going on further than the eye is willing to accept. The track goes down toward it. Somewhere out in the middle of all that, something stands up out of the water.', 0, 0, 'road', 0, 42, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-first-sight', 'west', 'the-watershed', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-first-sight', 'east', 'the-far-shore-stone', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-far-shore-stone', 'door', 'The Far Shore Stone', 'A single dressed pillar at the head of the descent, the last piece of the fortress''s work in this direction and the finest of it, cut with a face that has been kept clear of lichen by somebody. It looks east over the water. There is a stone bench beside it, set at exactly the height for sitting and looking, and whoever put it here knew that people arriving would need to sit down.', 0, 1, 'road', 0, 43, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-far-shore-stone', 'west', 'the-first-sight', NULL);

-- THE RELAY HOUSE KEEPS A TORCH, like every other gate in the world. Every
-- is_entry room carries a regrowing torch on the floor (mig 183 fixed the four
-- that did not), and a new gate that shipped without one would be the only
-- doorway on the map you could arrive at in the dark with nothing to light.
INSERT INTO ground_spawns (item_id, room_id, regrows) VALUES ('torch', 'the-relay-house', 1);
