-- Generated by scripts/build-rooms.mjs from: regions/open-ground.rooms
-- 33 rooms, 58 exits. Do not hand-edit — regenerate from the source text.
-- Validated: every exit resolves, every exit has a return path (or is marked one-way),
-- no duplicate ids, no orphans, every room reachable from a gate.

-- the-gatefall: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-gatefall', 'north', 'the-siege-bank', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-siege-bank', 'door', 'The Siege Bank', 'A long bank of thrown-up earth running parallel to the wall, grassed over and slumped but unmistakably deliberate — it has a ditch on the fortress side and a flat walk behind it, and it is still exactly high enough to stand behind. Everything about it says somebody expected to be shot at from that direction for a long time.', 0, 0, 'out', 0, -1, 6);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-siege-bank', 'south', 'the-gatefall', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-siege-bank', 'north', 'the-battery', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-siege-bank', 'east', 'the-sap-head', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-siege-bank', 'west', 'the-spoil-heap', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-spoil-heap', 'door', 'The Spoil Heap', 'A ridge of raw chalk gone grey, dumped in a line and never spread, with grass failing to take on it after two hundred years. This came out of the ground somewhere. The quantity of it tells you the hole was not a trench.', 0, 0, 'out', 0, -2, 6);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-spoil-heap', 'east', 'the-siege-bank', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-battery', 'door', 'The Battery', 'Three level platforms of rammed chalk set back behind the bank, each one big enough for something very heavy, each one with a hard track running up to it from the rear. The ground in front of the platforms is scorched in a way that grass has still not forgiven.', 0, 0, 'out', 0, -1, 5);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-battery', 'south', 'the-siege-bank', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-battery', 'north', 'the-camp-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-battery', 'west', 'the-shot-pile', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-battery', 'east', 'the-forge-pit', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-shot-pile', 'door', 'The Shot Pile', 'Stone shot, hundreds of them, sorted into heaps by size and left in their heaps: the big ones you could not lift, the middling ones, and a pile of small ones the size of a fist. They were dressed round by hand, every one. Nobody came back for them because by the end nobody needed them.', 0, 0, 'out', 0, -2, 5);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-shot-pile', 'east', 'the-battery', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-forge-pit', 'door', 'The Forge Pit', 'A dug hollow with a stone hearth in the bottom, a bellows-block still bedded in the clay, and a scatter of hammerscale trodden into the floor so thick it glitters. An army carries its smith. This is where everything that broke got made to work again.', 0, 0, 'out', 0, 0, 5);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-forge-pit', 'west', 'the-battery', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-camp-ground', 'door', 'The Camp Ground', 'Rows of shallow rectangular hollows in the turf, each the size of a hut, in ranks with streets between them, going on further than you would like to count. Nothing above ground survives. The shape of a town that stood here for a season is cut into the grass and will be there for a thousand years.', 0, 0, 'out', 0, -1, 4);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-camp-ground', 'south', 'the-battery', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-camp-ground', 'north', 'the-marshals-lodging', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-camp-ground', 'west', 'the-suttlers-row', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-camp-ground', 'east', 'the-horse-lines', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-suttlers-row', 'door', 'The Sutlers'' Row', 'Off the end of the camp streets, a wider hollow with a great deal of broken pottery in it and the remains of a hard standing. Where the army was sold to: drink, bread, and whatever else. It is the only part of the lines that is not laid out in a straight line, because this part was not the army''s idea.', 0, 0, 'out', 0, -2, 4);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-suttlers-row', 'east', 'the-camp-ground', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-horse-lines', 'door', 'The Horse Lines', 'Two long parallel scars in the turf with the ground between them worn down a foot lower than either side, and the soil in that strip is black and rich and grows nettles like nowhere else on this hill. Horses stood here in their hundreds for long enough to change what the ground is made of.', 0, 0, 'out', 0, 0, 4);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-horse-lines', 'west', 'the-camp-ground', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-marshals-lodging', 'door', 'The Marshal''s Lodging', 'The one building. Stone footings, a hearth, a flagged floor and the stub of a chimney, set on the highest point of the lines with the whole siege laid out below it and the fortress gate dead ahead. Whoever ran this had a roof and a fire and a view of the work, and everybody in the camp below could see that they did.', 0, 1, 'out', 0, -1, 3);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-marshals-lodging', 'south', 'the-camp-ground', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-sap-head', 'door', 'The Sap Head', 'A trench comes up out of the ground here and stops — a proper sap, zigzagged so nothing could shoot down the length of it, driven from the lines toward the wall a spade at a time under wicker screens. The last stretch of it is roofed with rotted hurdles and earth. It does not stop because they gave up.', 0, 0, 'out', 0, 0, 6);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sap-head', 'west', 'the-siege-bank', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sap-head', 'east', 'the-mine-mouth', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-mine-mouth', 'door', 'The Mine Mouth', 'Where the sap goes underground: a timbered opening in the chalk, propped, still standing, angled down and east — which is to say, straight at the foundations of the curtain wall. Twenty yards that way and forty feet up, there is a hole in the fortress the size of a house, and this is the reason for it.', 0, 0, 'out', 0, 1, 6);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-mine-mouth', 'west', 'the-sap-head', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-mine-mouth', 'down', 'the-mine-gallery', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-mine-gallery', 'door', 'The Mine Gallery', 'A timbered gallery in the chalk, four feet wide and just tall enough, running east under the weight of everything. The props are oak and they are sound and they are holding. At the far end it opens into a chamber where the props are CHARRED — packed with brushwood and fired, so that when the timbers burned the roof came down, and the wall on top of it came with it.', 0, 0, 'out', 0, 2, 7);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-mine-gallery', 'up', 'the-mine-mouth', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-mine-gallery', 'east', 'the-camouflet', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-camouflet', 'door', 'The Camouflet', 'The defenders heard the digging and dug back, and the two galleries met here, and what happened in this chamber happened in the dark, underground, with picks, between men who could not stand upright. The chalk on both sides is scored at chest height in long parallel grooves. The countermine goes on east and is choked with fall.', 0, 0, 'out', 0, 3, 7);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-camouflet', 'west', 'the-mine-gallery', NULL);

-- the-burned-village: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-burned-village', 'west', 'the-village-street', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-village-street', 'door', 'The Village Street', 'The one street, running west, with the burned plots on both sides showing as low rectangles of rubble and a black line in the soil at the level of the old floors. Between two of them a cobbled entry still runs, going nowhere now, worn into a dip down the middle by two centuries of people who no longer come this way.', 0, 0, 'out', 0, -2, 9);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-village-street', 'east', 'the-burned-village', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-village-street', 'west', 'the-well-head', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-village-street', 'north', 'the-pound', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-pound', 'door', 'The Pound', 'Four stone walls, chest high, with no roof and one gap for a gate, in the corner of what was somebody''s ground. Stray beasts were shut in here until their owner paid to have them back. The walls are the soundest thing in the village because a pound has to be, and there is nothing in it.', 0, 0, 'out', 0, -2, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-pound', 'south', 'the-village-street', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-pound', 'west', 'the-tithe-barn', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-tithe-barn', 'door', 'The Tithe Barn', 'A long stone building with its roof gone and its gable ends standing, and it is much too big for this village — it took the tenth of everything grown for miles and it needed the room. Swallows have the wall tops. The threshing floor is still there under the grass, hard as a road.', 0, 0, 'out', 0, -3, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-tithe-barn', 'east', 'the-pound', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-tithe-barn', 'north', 'the-green', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-well-head', 'door', 'The Well Head', 'A round stone kerb at the crossing of the street and the way down to the green, with a windlass frame over it, timber, grey, and still standing. There is no bucket and no rope. Drop a stone and the answer comes back after long enough to make you reconsider the depth of this place.', 0, 0, 'out', 0, -3, 9);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-well-head', 'east', 'the-village-street', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-well-head', 'west', 'the-church-shell', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-church-shell', 'door', 'The Church Shell', 'Walls, no roof, and the tower still up to the belfry stage with the louvres burned out of it. The east window is a great empty shape with the tracery gone. Inside, grass, and a font lying on its side, and the whole floor deep in the fallen slates that took two centuries to come down one at a time.', 0, 0, 'out', 0, -4, 9);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-church-shell', 'east', 'the-well-head', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-church-shell', 'north', 'the-churchyard', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-churchyard', 'door', 'The Churchyard', 'Stones leaning at every angle in grass that nobody cuts, most of them illegible, a few of them not. The yews are enormous and were old when the church was new. The ground here is visibly higher than the ground outside the wall, by about a foot, which is what a thousand years of burials does to a field.', 0, 0, 'out', 0, -4, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-churchyard', 'south', 'the-church-shell', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-churchyard', 'west', 'the-bell-pit', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-bell-pit', 'door', 'The Bell Pit', 'A shallow round pit lined with fired clay, with a runner channel cut off one side and a splash of grey metal set hard in the bottom of it. The bell came down out of that tower and was melted here, on the spot, by whoever held this ground and needed the bronze more than they needed the hour.', 0, 0, 'out', 0, -5, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bell-pit', 'east', 'the-churchyard', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-green', 'door', 'The Green', 'Open ground between the church and the last of the houses, cropped short by something that still comes here to crop it, with a stone at the middle that is not a marker and not a mounting block and has a smooth dished top from a very great deal of sitting. This was the middle of somebody''s world.', 0, 0, 'out', 0, -3, 7);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-green', 'south', 'the-tithe-barn', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-green', 'west', 'the-village-smithy', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-village-smithy', 'door', 'The Village Smithy', 'Open-fronted, stone-backed, roofed in slate that has mostly held, with the hearth still in the back wall and the stone trough beside it full of black water. There is an anvil bed and no anvil. An anvil is worth carrying away and everything else here was not.', 0, 1, 'out', 0, -4, 7);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-village-smithy', 'east', 'the-green', NULL);

-- the-sally-ditch: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sally-ditch', 'south', 'the-fish-stew', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-fish-stew', 'door', 'The Fish Stews', 'Three rectangular ponds in a row, stone-kerbed, connected by sluices, and still holding water because whoever cut them cut them properly. They bred fish in these for the fast days. Two are green to the surface with weed. The third is clear, and deeper than the other two, and there is something in it.', 0, 0, 'out', 0, -1, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fish-stew', 'north', 'the-sally-ditch', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fish-stew', 'west', 'the-orchard-rows', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fish-stew', 'south', 'the-culver-house', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-orchard-rows', 'door', 'The Orchard Rows', 'The part of the orchard the water never reached: old trees in ranks, gone to moss and mistletoe and standing at every angle, still fruiting badly out of the tops. The grass between the rows is short. Something keeps it short, and it is not the water.', 0, 0, 'out', 0, -2, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-orchard-rows', 'east', 'the-fish-stew', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-orchard-rows', 'south', 'the-cider-house', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-cider-house', 'door', 'The Cider House', 'A stone building with a great circular stone trough set into the floor and the runner-stone lying in the bottom of it, cracked across. A horse walked round and round in here and the fruit came out as liquid. The smell has not entirely gone, and after two hundred years that says something about how much of it there was.', 0, 1, 'out', 0, -2, 13);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cider-house', 'north', 'the-orchard-rows', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-culver-house', 'door', 'The Culver House', 'A round stone tower with a domed roof and one low door, and inside, from the floor to the top of the dome, five hundred nest-holes cut into the wall in perfect spirals. It is the most carefully made building on this side of the fortress and it was built to breed pigeons to eat. Something is up in the top of it and it is not pigeons.', 0, 0, 'out', 0, -1, 13);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-culver-house', 'north', 'the-fish-stew', NULL);

-- the-old-road: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-old-road', 'south', 'the-gibbet-field', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-gibbet-field', 'door', 'The Gibbet Field', 'A bare field below the hanging hill, out of the parish and off anybody''s good land, with a single post standing in the middle of it — square, oak, iron-strapped, with a long iron arm out of the top and a hook on the end of the arm. It stands where the road can see it, which was the entire point of putting it here. Nothing hangs from it. The grass grows to the foot of the post and stops in a circle.', 0, 0, 'out', 0, 2, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-gibbet-field', 'north', 'the-old-road', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-gibbet-field', 'east', 'the-crossroads-grave', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-crossroads-grave', 'door', 'The Crossroads Grave', 'Where two tracks cross outside consecrated ground: a low mound with a stone laid flat on it rather than standing, and the stone has no name on it and never had. This is where the ones the churchyard would not take were put, at a crossing, so that if they got up they would not know which way to go.', 0, 0, 'out', 0, 3, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-crossroads-grave', 'west', 'the-gibbet-field', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-crossroads-grave', 'east', 'the-charnel', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-charnel', 'door', 'The Charnel', 'A stone shed with a low door and a slate roof, where the bones came when the churchyard needed the room again — stacked, sorted, long bones one side and skulls the other, in courses, by somebody who took the work seriously. It is dry inside. The stacks are still standing and they are still in order.', 0, 0, 'out', 0, 4, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-charnel', 'west', 'the-crossroads-grave', NULL);
