-- Generated by scripts/build-rooms.mjs from: regions/mountain-3.rooms
-- 90 rooms, 246 exits. Do not hand-edit — regenerate from the source text.
-- Validated: every exit resolves, every exit has a return path (or is marked one-way),
-- no duplicate ids, no orphans, every room reachable from a gate.

-- the-rake: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rake', 'east', 'the-rake-top', NULL);

-- the-mid-shelf: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-mid-shelf', 'east', 'the-shelf-head', NULL);

-- the-shattered-crown: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-shattered-crown', 'north', 'the-crown-step', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-rake-top', 'door', 'The Rake Top', 'The ramp runs out onto a shelf under the first of the great ribs, and the ground you have been climbing for two days becomes, in one step, the bottom of something else. The buttress goes up out of the shelf and into cloud about two hundred feet above your head and does not come out of it. You cannot see how much more there is.', 0, 0, 'mountain', 0, 89, 7);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rake-top', 'north', 'the-rib-foot', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rake-top', 'south', 'the-under-rib', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rake-top', 'east', 'the-first-buttress', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rake-top', 'west', 'the-rake', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-first-buttress', 'door', 'The First Buttress', 'A rib of rock standing out from the face like a flying wall, sixty feet through at the base and going up until the cloud takes it. It is the first of five you will pass and it is not the largest. Standing at the foot and looking along the line of them is the first time this mountain has shown you its size on purpose.', 0, 0, 'mountain', 0, 90, 7);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-first-buttress', 'north', 'the-rib-gap', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-first-buttress', 'south', 'the-hanging-scree', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-first-buttress', 'east', 'the-scoop', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-first-buttress', 'west', 'the-rake-top', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-rib-foot', 'door', 'The Rib Foot', 'Where the buttress meets the mountain, in a corner choked with everything the rib has shed, some of it very large and none of it settled. There is a constant small trickle of grit down the back of this corner. It stops when you stop moving and starts again a moment later.', 0, 0, 'mountain', 0, 89, 6);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rib-foot', 'south', 'the-rake-top', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rib-foot', 'east', 'the-rib-gap', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rib-foot', 'west', 'the-cold-ramp', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-rib-gap', 'door', 'The Rib Gap', 'A gap between two ribs, floored with jammed blocks and roofed, in one place, by a boulder that fell in and stuck twenty feet up. It is the only shade on this face and the light in it is green. You go through it single file and you go through it quickly.', 0, 0, 'mountain', 0, 90, 6);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rib-gap', 'south', 'the-first-buttress', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rib-gap', 'east', 'the-second-rib', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rib-gap', 'west', 'the-rib-foot', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-second-rib', 'door', 'The Second Rib', 'The second buttress, thinner than the first and more broken, with ledges on its flank at intervals all the way up like rungs. Somebody could climb this. Nobody has: there is nothing at the top of it that anybody wanted, and that is the whole reason this mountain has never been climbed.', 0, 0, 'mountain', 0, 91, 6);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-second-rib', 'south', 'the-scoop', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-second-rib', 'east', 'the-arete-foot', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-second-rib', 'west', 'the-rib-gap', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-scoop', 'door', 'The Scoop', 'A rounded hollow bitten out of the face between two ribs, floored with fine grit and completely out of the wind. Things come in here to be out of the weather and the grit is churned with the marks of them. None of the marks were made by anything with two feet.', 0, 0, 'mountain', 0, 91, 7);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-scoop', 'north', 'the-second-rib', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-scoop', 'south', 'the-fall-line', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-scoop', 'west', 'the-first-buttress', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-hanging-scree', 'door', 'The Hanging Scree', 'Scree lying at the absolute limit of what scree will lie at, on a shelf with a drop at the bottom of it, so that everything that starts moving here does not stop until it has gone over. Crossing it is a question of not starting anything. It is not steep enough to be frightening and it is exactly steep enough to be fatal.', 0, 0, 'mountain', 0, 90, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hanging-scree', 'north', 'the-first-buttress', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hanging-scree', 'east', 'the-fall-line', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hanging-scree', 'west', 'the-under-rib', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-under-rib', 'door', 'The Under-Rib', 'A dry cave of sorts where the first buttress overhangs its own foot — not deep, but roofed, floored in soft dust, and with a wall of rock between you and everything above. Nothing can come at you from over your head in here, which is a comfort you did not know you needed until this tier.', 0, 1, 'mountain', 0, 89, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-under-rib', 'north', 'the-rake-top', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-under-rib', 'east', 'the-hanging-scree', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-fall-line', 'door', 'The Fall Line', 'The natural line down the face: a shallow trough scoured clean and polished, where everything that comes off the mountain above comes through. It is the fastest way down and the reason you would not stand in it. There is fresh debris at the bottom of the visible section and it was not there yesterday.', 0, 0, 'mountain', 0, 91, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fall-line', 'north', 'the-scoop', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fall-line', 'east', 'the-valley-mouth', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fall-line', 'west', 'the-hanging-scree', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-arete-foot', 'door', 'The Arete Foot', 'The ribs converge and become one, and the one goes up as a wall barely wider than a path with the whole north face falling away on one hand and the whole east face on the other. From here it looks impossible and from the top of it it will look like a path. It is a path. That is what makes it bad.', 0, 0, 'mountain', 0, 92, 6);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-arete-foot', 'north', 'the-first-tower', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-arete-foot', 'east', 'the-drop-either-side', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-arete-foot', 'west', 'the-second-rib', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-first-tower', 'door', 'The First Tower', 'A pinnacle on the ridge, thirty feet of standing rock you go round rather than over, on a ledge on the north side that is out of the sun and iced for most of the year. The rock is sound. The ice on it is not, and it is not always where you can see it.', 0, 0, 'mountain', 0, 92, 5);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-first-tower', 'south', 'the-arete-foot', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-first-tower', 'east', 'the-notch-of-air', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-notch-of-air', 'door', 'The Notch of Air', 'A gap in the ridge where the rock has failed on both sides at once, leaving a saddle a stride wide with several hundred feet of nothing under each end of the stride. The wind comes up through it from below rather than across it, which is a thing you feel through your boots before you understand it.', 0, 0, 'mountain', 0, 93, 5);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-notch-of-air', 'north', 'the-arete-walk', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-notch-of-air', 'east', 'the-second-tower', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-notch-of-air', 'west', 'the-first-tower', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-second-tower', 'door', 'The Second Tower', 'The larger of the two pinnacles, split from crown to base by a crack you can see daylight through, and leaning. It has been leaning a long time and it will lean a while longer. Going round it puts you on the exposed side for eight paces.', 0, 0, 'mountain', 0, 94, 5);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-second-tower', 'north', 'the-bad-step', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-second-tower', 'south', 'the-blade', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-second-tower', 'east', 'the-arete-end', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-second-tower', 'west', 'the-notch-of-air', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-arete-walk', 'door', 'The Arete Walk', 'The ridge at its kindest: four feet wide, level, sound underfoot, and with a view down both faces at once that would be worth the walk if you were able to look at it. In cloud it is simply a strip of rock going into white, with the ground gone from both sides, and the temptation to crawl is considerable and correct.', 0, 0, 'mountain', 0, 93, 4);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-arete-walk', 'north', 'the-spur-end', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-arete-walk', 'south', 'the-notch-of-air', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-arete-walk', 'east', 'the-bad-step', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-bad-step', 'door', 'The Bad Step', 'The ridge narrows to a rib the width of a hand, for about the length of a body, with a step down onto it and a step up off it. There are good holds. It is short. Everything about it is manageable and it has still killed things, because managing it requires a decision and the wind up here makes decisions for you.', 0, 0, 'mountain', 0, 94, 4);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bad-step', 'south', 'the-second-tower', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bad-step', 'east', 'the-horns', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bad-step', 'west', 'the-arete-walk', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-horns', 'door', 'The Horns', 'Two blades of rock standing up off the ridge side by side, of a stone harder than what was round them, left behind when everything softer went. They are the shape the mountain shows from thirty miles away — the thing that makes it recognisable on the horizon — and up close they are two rocks.', 0, 0, 'mountain', 0, 95, 4);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-horns', 'south', 'the-arete-end', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-horns', 'west', 'the-bad-step', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-arete-end', 'door', 'The Arete End', 'The ridge runs into the mountain''s mass and stops being a ridge, in a jumble of broken blocks with the ice beginning just beyond them. Behind you the whole arete goes down and out and disappears into cloud partway. It looks entirely impassable from this end too.', 0, 0, 'mountain', 0, 95, 5);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-arete-end', 'north', 'the-horns', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-arete-end', 'east', 'the-neve', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-arete-end', 'west', 'the-second-tower', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-drop-either-side', 'door', 'The Drop Either Side', 'A stretch of the ridge with nothing to hold and nothing to do but walk it, six feet wide and dead level, with the ground simply absent to left and right. It is the safest ten paces on the arete by any measure you could take. It does not feel like it and it never will.', 0, 0, 'mountain', 0, 93, 6);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drop-either-side', 'south', 'the-valley-shoulder', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drop-either-side', 'east', 'the-blade', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drop-either-side', 'west', 'the-arete-foot', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-blade', 'door', 'The Blade', 'The ridge here is a single sheet of rock stood on its edge, weathered to a knife along the top, with the sides falling away smooth and unbroken. You do not walk on the top. There is a line of holds a body''s length down the east side and that is the way past.', 0, 0, 'mountain', 0, 94, 6);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-blade', 'north', 'the-second-tower', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-blade', 'west', 'the-drop-either-side', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-valley-mouth', 'door', 'The Valley Mouth', 'The ground opens sideways into a valley that has no business being here — a full glen, floor and walls and a stream in the bottom of it, hanging in the side of the mountain with its lower end simply stopping in mid-air above the drop. The stream goes over that end and is gone as spray before it lands.', 0, 0, 'mountain', 0, 92, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-valley-mouth', 'south', 'the-outwash', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-valley-mouth', 'east', 'the-hanging-floor', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-valley-mouth', 'west', 'the-fall-line', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-hanging-floor', 'door', 'The Hanging Floor', 'Flat ground, and after two tiers of slope it is disorienting rather than restful: gravel and short grass and braided water, walled a thousand feet on both sides, and level enough to run on. It is the largest flat place on this mountain and there is nothing on it that needs the space.', 0, 0, 'mountain', 0, 93, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hanging-floor', 'north', 'the-valley-shoulder', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hanging-floor', 'south', 'the-moraine-loop', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hanging-floor', 'east', 'the-upper-lochan', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hanging-floor', 'west', 'the-valley-mouth', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-upper-lochan', 'door', 'The Upper Lochan', 'A second lochan, higher and smaller and paler than the one in the corrie below, floored with grey silt that comes up in clouds if anything disturbs it and takes an hour to settle. You can see the bottom, which the lower one never allowed. There is nothing on the bottom.', 0, 0, 'mountain', 0, 94, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-upper-lochan', 'north', 'the-north-bank', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-upper-lochan', 'south', 'the-braided-flats', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-upper-lochan', 'east', 'the-far-shore-high', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-upper-lochan', 'west', 'the-hanging-floor', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-far-shore-high', 'door', 'The Far Shore', 'The head end of the water, where the valley''s stream comes in over a fan of its own gravel in a dozen shifting channels. The fan is bare, pale, and completely without cover, and it is a hundred yards across. Everything that crosses this valley crosses here or goes the long way round.', 0, 0, 'mountain', 0, 95, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-far-shore-high', 'north', 'the-south-bank', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-far-shore-high', 'south', 'the-till', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-far-shore-high', 'east', 'the-valley-head', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-far-shore-high', 'west', 'the-upper-lochan', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-valley-head', 'door', 'The Valley Head', 'The back of the hanging valley, walled by a headwall with the ice above it, and the stream coming down that wall in a thread that is blown sideways to nothing halfway. Only about half the water that leaves the top of it arrives at the bottom. The rest goes into the air.', 0, 0, 'mountain', 0, 96, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-valley-head', 'north', 'the-cloud-base', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-valley-head', 'south', 'the-step-in-the-floor', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-valley-head', 'east', 'the-grey-nothing', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-valley-head', 'west', 'the-far-shore-high', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-moraine-loop', 'door', 'The Moraine Loop', 'A crescent bank of rubble looping across the valley floor, twenty feet high and as regular as an earthwork, marking exactly where something stopped and sat for a long time before going back. It is the tidiest thing on this mountain and nothing tidied it.', 0, 0, 'mountain', 0, 93, 9);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-moraine-loop', 'north', 'the-hanging-floor', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-moraine-loop', 'east', 'the-braided-flats', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-moraine-loop', 'west', 'the-outwash', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-outwash', 'door', 'The Outwash', 'A plain of sorted sand and gravel where the valley''s water spreads and drops what it is carrying before going over the lip. It is soft walking, the only soft walking up here, and it takes a print beautifully. There are prints in it now, deep, crossing, and larger than a hand.', 0, 0, 'mountain', 0, 92, 9);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-outwash', 'north', 'the-valley-mouth', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-outwash', 'east', 'the-moraine-loop', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-braided-flats', 'door', 'The Braided Flats', 'The stream splits into a dozen shallow channels across a bed of pale gravel, each one an inch deep and running fast, rejoining and splitting again. It is loud. Standing in the middle of it you cannot hear anything else at all, and there is no cover in any direction.', 0, 0, 'mountain', 0, 94, 9);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-braided-flats', 'north', 'the-upper-lochan', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-braided-flats', 'east', 'the-till', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-braided-flats', 'west', 'the-moraine-loop', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-till', 'door', 'The Till', 'Unsorted ground: clay, sand, gravel and boulders all through each other in no order, dumped in a heap and left, with the stream cutting a raw face into one side of it. Things stick out of that face. Bone, mostly, and a good deal of it, all of it very old.', 0, 0, 'mountain', 0, 95, 9);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-till', 'north', 'the-far-shore-high', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-till', 'east', 'the-step-in-the-floor', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-till', 'west', 'the-braided-flats', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-step-in-the-floor', 'door', 'The Step in the Floor', 'The valley floor is not one floor: it goes up a rock step forty feet high, worn smooth and rounded, with the stream coming down a groove in it. Above the step there is another flat, and above that another step. The whole valley is a stair for something that was very much larger than the stream.', 0, 0, 'mountain', 0, 96, 9);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-step-in-the-floor', 'north', 'the-valley-head', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-step-in-the-floor', 'west', 'the-till', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-valley-shoulder', 'door', 'The Valley Shoulder', 'The rim of the hanging valley, on the north side, where the flat floor stops and the ground goes up to the arete. From here you can see the whole valley at once, and the drop it hangs above, and the country far below the drop. On a clear hour it is the best view on the mountain. There are perhaps six clear hours a month.', 0, 0, 'mountain', 0, 93, 7);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-valley-shoulder', 'north', 'the-drop-either-side', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-valley-shoulder', 'south', 'the-hanging-floor', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-valley-shoulder', 'east', 'the-north-bank', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-north-bank', 'door', 'The North Bank', 'The shaded side of the valley, under the arete, with the ground stony and the snow lying in patches well into the summer and the grass giving out entirely. Nothing grazes on this side. Things cross it, and they cross it fast.', 0, 0, 'mountain', 0, 94, 7);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-north-bank', 'south', 'the-upper-lochan', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-north-bank', 'east', 'the-south-bank', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-north-bank', 'west', 'the-valley-shoulder', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-south-bank', 'door', 'The South Bank', 'The sunny side, which up here means merely that it is not frozen, with a thin grass in the hollows and small flowers flat against the ground in the sheltered spots. There is more living on this bank than on the whole north side of the valley put together, and it is not much.', 0, 0, 'mountain', 0, 95, 7);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-south-bank', 'south', 'the-far-shore-high', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-south-bank', 'east', 'the-cloud-base', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-south-bank', 'west', 'the-north-bank', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-cloud-base', 'door', 'The Cloud Base', 'A line across the mountain, sharp enough to walk through in one step, where the air gives up its water and everything above is inside the cloud. Below the line: rock, distance, weather happening elsewhere. Above it: your own hands and about eight feet of grey. The line moves up and down through the day and nobody consults you.', 0, 0, 'mountain', 0, 96, 7);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cloud-base', 'north', 'the-inversion', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cloud-base', 'south', 'the-valley-head', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cloud-base', 'east', 'the-white-out', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cloud-base', 'west', 'the-south-bank', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-white-out', 'door', 'The White Out', 'Cloud on snow, and the two are the same colour and the same brightness, and the ground and the air stop being different things. You cannot see the slope you are standing on. You find out which way is downhill by falling over, and that is not a joke — it is the recommended method.', 0, 0, 'mountain', 0, 97, 7);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-white-out', 'north', 'the-brocken', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-white-out', 'south', 'the-grey-nothing', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-white-out', 'east', 'the-standing-cloud', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-white-out', 'west', 'the-cloud-base', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-grey-nothing', 'door', 'The Grey Nothing', 'Inside the cloud on bare rock, where there is no horizon, no sky, no ground beyond your boots, and no sound except your own. Distance stops working: something ten feet away and something a mile away look identical, which is to say both look like nothing at all.', 0, 0, 'mountain', 0, 97, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-grey-nothing', 'north', 'the-white-out', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-grey-nothing', 'south', 'the-rising-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-grey-nothing', 'east', 'the-cloud-shelf', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-grey-nothing', 'west', 'the-valley-head', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-inversion', 'door', 'The Inversion', 'You come up out of the cloud, and it is below you: a floor of white lying flat across the whole country from horizon to horizon, with two or three other summits standing out of it like islands and nothing else in the world existing at all. It is the most beautiful thing anybody up here has ever seen and there has never been anybody up here.', 0, 0, 'mountain', 0, 96, 6);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-inversion', 'north', 'the-neve', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-inversion', 'south', 'the-cloud-base', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-inversion', 'east', 'the-brocken', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-brocken', 'door', 'The Brocken', 'Standing with the sun behind you and the cloud in front, your own shadow is thrown onto the cloud enormously, with a ring of light round its head, and it moves when you move. Everything about it is explicable. Knowing that does not help as much as you would expect.', 0, 0, 'mountain', 0, 97, 6);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-brocken', 'north', 'the-ice-fall', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-brocken', 'south', 'the-white-out', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-brocken', 'east', 'the-clear-window', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-brocken', 'west', 'the-inversion', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-standing-cloud', 'door', 'The Standing Cloud', 'Cloud that forms on this shoulder and stays there while the wind goes through it, so that the air is moving hard and the cloud is not moving at all — condensing on one side, evaporating on the other, holding station. It is the same cloud and it is entirely new every few seconds.', 0, 0, 'mountain', 0, 98, 7);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-standing-cloud', 'north', 'the-clear-window', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-standing-cloud', 'south', 'the-cloud-shelf', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-standing-cloud', 'west', 'the-white-out', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-clear-window', 'door', 'The Clear Window', 'A hollow in the rock that the cloud does not come into, for reasons to do with the shape of it and the way the air turns, so that there is a pocket of clear cold air here with grey walls on every side of it. It is dry and out of the wind and you can see. All three are rare.', 0, 1, 'mountain', 0, 98, 6);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-clear-window', 'south', 'the-standing-cloud', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-clear-window', 'west', 'the-brocken', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-cloud-shelf', 'door', 'The Cloud Shelf', 'A broad terrace on the cloud line, half in and half out, so that one end of it is in weather and the other end is in sun and you can stand with the boundary crossing you. Things lie up at the sunny end. The wet end is where you come in.', 0, 0, 'mountain', 0, 98, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cloud-shelf', 'north', 'the-standing-cloud', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cloud-shelf', 'west', 'the-grey-nothing', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-cloud-foot', 'door', 'The Cloud Foot', 'The bottom of the cloud on the south side, where the ground rises out of the shelves and into the grey, and the last of the plants stop within a few strides of each other in a line you could draw. Above this there is nothing green at all on this whole mountain.', 0, 0, 'mountain', 0, 97, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cloud-foot', 'north', 'the-rising-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cloud-foot', 'south', 'the-last-shelf', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-rising-ground', 'door', 'The Rising Ground', 'Steepening rock going up into the cloud, with the way ahead visible for ten paces and no further, and the sense the whole time that you are about to come out on top of something. You are not. There is a great deal more of this than there appears to be, precisely because there is nothing to appear.', 0, 0, 'mountain', 0, 97, 9);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rising-ground', 'north', 'the-grey-nothing', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rising-ground', 'south', 'the-cloud-foot', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-neve', 'door', 'The Neve', 'The top of the ice, where snow has been falling and packing for longer than anything else on this mountain has been happening, in a smooth white field that goes up at an even angle and out of sight. It is firm in the morning and it is not firm in the afternoon and the difference matters entirely.', 0, 0, 'mountain', 0, 96, 5);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-neve', 'north', 'the-blue-wall', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-neve', 'south', 'the-inversion', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-neve', 'east', 'the-ice-fall', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-neve', 'west', 'the-arete-end', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-ice-fall', 'door', 'The Ice Fall', 'Where the ice goes over a step in the rock beneath it and breaks up doing it, into a chaos of leaning blocks and towers the size of houses, none of them stable and all of them moving slower than you can see. There is a way through. It is not the same way it was last year.', 0, 0, 'mountain', 0, 97, 5);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ice-fall', 'north', 'the-crevasse-field', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ice-fall', 'south', 'the-brocken', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ice-fall', 'west', 'the-neve', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-crevasse-field', 'door', 'The Crevasse Field', 'The ice here is split into parallel cracks running across the slope, some of them a hand''s width and some of them wide enough to lose a horse, and a good many of them roofed over with snow that will hold a hare and will not hold you. There is no way to tell which is which by looking.', 0, 0, 'mountain', 0, 97, 4);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-crevasse-field', 'north', 'the-rime', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-crevasse-field', 'south', 'the-ice-fall', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-crevasse-field', 'east', 'the-cornice', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-crevasse-field', 'west', 'the-blue-wall', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-blue-wall', 'door', 'The Blue Wall', 'A face of bare ice twenty feet high where the field has torn away from itself, and it is BLUE — not white, not grey, a deep and genuine blue that gets stronger the further into the crack you look. It is the colour of the pressure it has been under. Water runs down it all day and freezes on it every night.', 0, 0, 'mountain', 0, 96, 4);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-blue-wall', 'north', 'the-ice-shelf', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-blue-wall', 'south', 'the-neve', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-blue-wall', 'east', 'the-crevasse-field', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-bergschrund', 'door', 'The Bergschrund', 'The gap where the moving ice has pulled away from the rock face it sits against, a trench of unknown depth running along the base of the headwall, floored somewhere below with everything that has fallen into it. Cold air comes out of it. So does a faint constant sound of water, from a long way down.', 0, 0, 'mountain', 0, 95, 3);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bergschrund', 'east', 'the-ice-shelf', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-ice-shelf', 'door', 'The Ice Shelf', 'A level bench of old hard ice under the headwall, swept clean by wind and polished, with stones lying on it that came off the wall and are slowly melting themselves into it. Each stone sits in its own shallow bowl. Walking on this needs something on your boots that you do not have.', 0, 0, 'mountain', 0, 96, 3);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ice-shelf', 'south', 'the-blue-wall', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ice-shelf', 'east', 'the-rime', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ice-shelf', 'west', 'the-bergschrund', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-rime', 'door', 'The Rime', 'Every surface up here is furred with ice grown sideways into the wind — feathers of it a hand long, all pointing the same way, on the rocks and the ice and the dead things. It builds at a finger''s width an hour in the right conditions. It is beautiful and it is a very direct statement about what the air is doing.', 0, 0, 'mountain', 0, 97, 3);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rime', 'south', 'the-crevasse-field', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rime', 'east', 'the-cold-crest', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rime', 'west', 'the-ice-shelf', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-cornice', 'door', 'The Cornice', 'The wind has built a lip of snow out over the edge of the crest, curling, unsupported, and reaching a good ten feet past where the ground actually stops. From above there is no way to see where the rock ends. From below you can see exactly, and it is nowhere near where you would have walked.', 0, 0, 'mountain', 0, 98, 4);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cornice', 'north', 'the-cold-crest', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cornice', 'west', 'the-crevasse-field', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-cold-crest', 'door', 'The Cold Crest', 'The top of this tier: a crest of rime-covered rock with the ice below on one side and cloud on the other, and above it the mountain going up again into something you cannot see the shape of. This is as far as the ground you understand goes.', 0, 0, 'mountain', 0, 98, 3);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cold-crest', 'south', 'the-cornice', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cold-crest', 'west', 'the-rime', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-crown-step', 'door', 'The Crown Step', 'Up off the shattered crown onto the spur, in a step of broken plates with the wind arriving the moment you top it. The spur runs away north and east from here, level and bare and about forty feet wide, with nothing on it and a drop on both sides.', 0, 0, 'mountain', 0, 86, 3);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-crown-step', 'south', 'the-shattered-crown', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-crown-step', 'east', 'the-north-rib', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-north-rib', 'door', 'The North Rib', 'The spur proper: a rib of the mountain running out into the air, wide enough not to be frightening and narrow enough that you can see over both edges without moving. There is no shelter on it anywhere along its length and you can see that from the start of it.', 0, 0, 'mountain', 0, 87, 3);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-north-rib', 'east', 'the-spur-walk', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-north-rib', 'west', 'the-crown-step', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-spur-walk', 'door', 'The Spur Walk', 'Easy level walking on frost-shattered plates that rock and clink under the boot, so that you are audible for a very long way in every direction and cannot help it. The noise is the ground, not you. There is no quiet way to cross this.', 0, 0, 'mountain', 0, 88, 3);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-spur-walk', 'east', 'the-spur-head', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-spur-walk', 'west', 'the-north-rib', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-spur-head', 'door', 'The Spur Head', 'The spur widens into a head of ground with the tarn beyond it and the plateau beyond that, and for the first time in a while there is more than one direction to go. It is also the first place on the spur that anything could be standing without your having seen it from half a mile back.', 0, 0, 'mountain', 0, 89, 3);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-spur-head', 'north', 'the-wind-scoop', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-spur-head', 'east', 'the-cold-plateau', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-spur-head', 'west', 'the-spur-walk', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-wind-scoop', 'door', 'The Wind Scoop', 'A hollow blown out of the ground on the lee side, bowl-shaped and floored with the coarse gravel the wind could not lift, and dead calm in the middle of a gale. Everything that lives up here knows this hollow. There is a good deal of sign in it and some of it is fresh.', 0, 0, 'mountain', 0, 89, 2);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wind-scoop', 'south', 'the-spur-head', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wind-scoop', 'east', 'the-lee-drift', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-cold-plateau', 'door', 'The Cold Plateau', 'Level ground at a height where level ground has no right to exist, floored in shattered stone with ice in the joints of it that never entirely goes. The plants are lichen and one cushion moss and nothing else. It goes on for further than you would like.', 0, 0, 'mountain', 0, 90, 3);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cold-plateau', 'north', 'the-lee-drift', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cold-plateau', 'east', 'the-frost-pavement', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cold-plateau', 'west', 'the-spur-head', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-frost-pavement', 'door', 'The Frost Pavement', 'Flat slabs of rock lying edge to edge like paving, with the cracks between them filled with fine sorted gravel, laid out over acres by nothing but freezing and thawing. It looks so exactly like a made floor that you keep expecting a wall. There has never been a wall.', 0, 0, 'mountain', 0, 91, 3);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-frost-pavement', 'north', 'the-tarn-edge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-frost-pavement', 'east', 'the-stripe-field', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-frost-pavement', 'west', 'the-cold-plateau', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-stripe-field', 'door', 'The Stripe Field', 'Stone stripes again, as on the shoulder far below, but up here they are enormous — lines of boulders twenty feet apart running dead straight down the slope for a quarter of a mile. The same small process, given more time and worse weather. Walking across the grain of them is slow and walking along them is easy and wrong.', 0, 0, 'mountain', 0, 92, 3);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-stripe-field', 'north', 'the-high-tarn', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-stripe-field', 'east', 'the-spur-end', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-stripe-field', 'west', 'the-frost-pavement', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-high-tarn', 'door', 'The High Tarn', 'A pool of meltwater in a hollow of the pavement, three strides across, absolutely clear and absolutely still, with the stones on its bottom as sharp as if there were no water there at all. It freezes solid most nights of the year. Nothing lives in it, which up here has stopped being remarkable.', 0, 0, 'mountain', 0, 92, 2);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-high-tarn', 'south', 'the-stripe-field', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-high-tarn', 'west', 'the-tarn-edge', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-tarn-edge', 'door', 'The Tarn Edge', 'A crescent of dry gravel on the sheltered side of the tarn, with a low wall of stacked slabs round the back of it about knee high — not built, or not by anybody; the frost stacks them like that and always has. Whatever the reason, it is out of the wind and there is water, and things use it.', 0, 1, 'mountain', 0, 91, 2);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-tarn-edge', 'south', 'the-frost-pavement', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-tarn-edge', 'east', 'the-high-tarn', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-tarn-edge', 'west', 'the-lee-drift', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-spur-end', 'door', 'The Spur End', 'The spur runs into the main mass and the ground rears up to meet the arete, in a slope of jammed blocks with the ridge line above it. From down on the spur this looked like the end of the walk. It is the beginning of the other one.', 0, 0, 'mountain', 0, 93, 3);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-spur-end', 'south', 'the-arete-walk', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-spur-end', 'west', 'the-stripe-field', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-lee-drift', 'door', 'The Lee Drift', 'Snow banked in the spur''s lee in a long tongue that lasts most of the year, hard, wind-carved into scallops, and with a wet grey line at the foot of it where it is always melting a little. It is the only water on this end of the spur and everything comes to it.', 0, 0, 'mountain', 0, 90, 2);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lee-drift', 'south', 'the-cold-plateau', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lee-drift', 'east', 'the-tarn-edge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lee-drift', 'west', 'the-wind-scoop', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-shelf-head', 'door', 'The Shelf Head', 'Round onto the south side and the wind goes off you like a coat coming off, and there is grass again — not much, and thin, but green. The shelves run east from here in a series of terraces, each one a little higher, and after the north side they feel like a kindness. They are not a kindness. They are simply where the sun is.', 0, 0, 'mountain', 0, 89, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-shelf-head', 'east', 'the-long-shelf', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-shelf-head', 'west', 'the-mid-shelf', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-long-shelf', 'door', 'The Long Shelf', 'A terrace running a quarter mile east under a wall, level, dry, and floored with short turf, which up here is close to a road. You can walk it without thinking, which is the first time that has been true since the foot, and it is a habit worth breaking before the shelf ends.', 0, 0, 'mountain', 0, 90, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-long-shelf', 'north', 'the-upper-heather', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-long-shelf', 'east', 'the-shelf-break', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-long-shelf', 'west', 'the-shelf-head', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-shelf-break', 'door', 'The Shelf Break', 'The terrace is cut through by a gully coming down from above, ten feet deep with vertical sides of packed gravel, and you go down into it and up the other side. Things wash down this gully. There is a heap at the bottom of what has washed down it, and it is not all stone.', 0, 0, 'mountain', 0, 91, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-shelf-break', 'north', 'the-last-green', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-shelf-break', 'east', 'the-sun-buttress', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-shelf-break', 'west', 'the-long-shelf', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-upper-heather', 'door', 'The Upper Heather', 'The last heather on the mountain, prostrate, woody, and no higher than your ankle, growing in a mat that follows every dip in the rock. Below this it stood waist high. It is the same plant. This is what the same plant looks like when it is fifteen hundred feet higher up.', 0, 0, 'mountain', 0, 90, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-upper-heather', 'south', 'the-long-shelf', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-upper-heather', 'east', 'the-last-green', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-upper-heather', 'west', 'the-heather-step', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-last-green', 'door', 'The Last Green', 'A patch of real grass, bright and cropped tight, in a hollow where water seeps out and the sun sits all afternoon. It is about the size of a cottage floor. It is the best thing to eat within a mile in any direction, and consequently the most dangerous ground on this side of the tier.', 0, 0, 'mountain', 0, 91, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-last-green', 'south', 'the-shelf-break', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-last-green', 'east', 'the-stone-run', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-last-green', 'west', 'the-upper-heather', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-stone-run', 'door', 'The Stone Run', 'A river of blocks pouring down between two shelves, each one the size of a chest and all of them locked together, with the gaps going down into blackness between them. Something small lives in there. You can hear it moving under your feet and you will not see it.', 0, 0, 'mountain', 0, 92, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-stone-run', 'south', 'the-sun-buttress', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-stone-run', 'east', 'the-shelf-end', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-stone-run', 'west', 'the-last-green', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-sun-buttress', 'door', 'The Sun Buttress', 'A rib on the sunny side, warm to the hand well into the evening, with ledges on it at head height where things sit and look out over the whole south country. The droppings on the ledges are white and old and layered, and there are a great many of them.', 0, 0, 'mountain', 0, 92, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sun-buttress', 'north', 'the-stone-run', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sun-buttress', 'east', 'the-warm-gully', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sun-buttress', 'west', 'the-shelf-break', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-warm-gully', 'door', 'The Warm Gully', 'A gully taking the afternoon sun end to end, sheltered from every wind, with the rock hot enough to be uncomfortable to sit on. Nothing at all is moving in here at midday. Wait an hour past the sun going off it and that changes.', 0, 0, 'mountain', 0, 93, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-warm-gully', 'north', 'the-shelf-end', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-warm-gully', 'east', 'the-high-spring', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-warm-gully', 'west', 'the-sun-buttress', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-shelf-end', 'door', 'The Shelf End', 'The terrace narrows to a point against a buttress and stops, with the next shelf twenty feet above and no way up at this end. You have to go back and round. It is the third time this tier has made you do that and it will not be the last.', 0, 0, 'mountain', 0, 93, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-shelf-end', 'south', 'the-warm-gully', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-shelf-end', 'east', 'the-scoop-of-grass', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-shelf-end', 'west', 'the-stone-run', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-scoop-of-grass', 'door', 'The Scoop of Grass', 'A green bowl in the rock, spring-fed, out of the wind, floored with the last real grass on this mountain and looking down the whole south side to the country beyond. Everything on this side of the hill comes here and the grass is cropped to the roots to prove it. It is the most comfortable place on this tier and it is comfortable for the same reason it is dangerous.', 0, 0, 'mountain', 0, 94, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-scoop-of-grass', 'south', 'the-high-spring', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-scoop-of-grass', 'east', 'the-south-rib', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-scoop-of-grass', 'west', 'the-shelf-end', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-high-spring', 'door', 'The High Spring', 'Water coming out of the rock at a height where there should be no water left to come out, clear and steady and very cold, running twenty feet and sinking again into the gravel. It has done this without stopping through droughts that emptied the burns below. Nobody knows where it comes from and there is nobody to ask.', 0, 0, 'mountain', 0, 94, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-high-spring', 'north', 'the-scoop-of-grass', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-high-spring', 'east', 'the-dry-shelf', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-high-spring', 'west', 'the-warm-gully', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-dry-shelf', 'door', 'The Dry Shelf', 'A terrace of bare baked gravel with the grass gone entirely, sloping just enough to shed every drop that falls on it. It is the driest ground on the mountain and it is forty yards from the spring. Nothing about this hill distributes anything evenly.', 0, 0, 'mountain', 0, 95, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-dry-shelf', 'north', 'the-south-rib', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-dry-shelf', 'east', 'the-terrace-end', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-dry-shelf', 'west', 'the-high-spring', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-south-rib', 'door', 'The South Rib', 'A rib running down the sun side with a path worn along the crest of it — a real path, narrow and continuous and beaten into the gravel by generations of something going the same way. It is not a made path. It is the shortest line between the spring and the shelves and everything worked that out.', 0, 0, 'mountain', 0, 95, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-south-rib', 'south', 'the-dry-shelf', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-south-rib', 'east', 'the-sun-notch', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-south-rib', 'west', 'the-scoop-of-grass', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-sun-notch', 'door', 'The Sun Notch', 'A cleft through the rib, a stride wide and twice your height, which the path goes through because there is nowhere else. It is a choke point and it looks like one. Anything waiting for anything on this side of the mountain waits here, and it has been used that way for a very long time.', 0, 0, 'mountain', 0, 96, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sun-notch', 'south', 'the-terrace-end', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sun-notch', 'east', 'the-last-shelf', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sun-notch', 'west', 'the-south-rib', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-terrace-end', 'door', 'The Terrace End', 'The last of the wide shelves, running out east into steeper ground with the terrace petering into a series of ledges too narrow to walk. From here the easy country is behind you and it is visibly behind you: you can see the whole line of shelves going back west and down.', 0, 0, 'mountain', 0, 96, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-terrace-end', 'north', 'the-sun-notch', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-terrace-end', 'east', 'the-shelf-drop', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-terrace-end', 'west', 'the-dry-shelf', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-last-shelf', 'door', 'The Last Shelf', 'A ledge under the cloud line with the grey sitting on the rock a few feet above your head, so that the shelf is in daylight and the mountain above it is not. It is the boundary of what you can see, drawn along the ground, and it moves when the cloud does.', 0, 0, 'mountain', 0, 97, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-last-shelf', 'north', 'the-cloud-foot', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-last-shelf', 'south', 'the-shelf-drop', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-last-shelf', 'west', 'the-sun-notch', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-shelf-drop', 'door', 'The Shelf Drop', 'The shelves end at a drop of two hundred feet onto the tier below, with the ground going over in a clean rounded lip worn smooth by water. You can look straight down onto ground you crossed yesterday and it is a very long way away. There is no way down here and it looks like there might be.', 0, 0, 'mountain', 0, 97, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-shelf-drop', 'north', 'the-last-shelf', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-shelf-drop', 'west', 'the-terrace-end', NULL);

-- the-late-field: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-late-field', 'east', 'the-cold-ramp', NULL);

-- the-hot-scree: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hot-scree', 'east', 'the-hot-ledge', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-cold-ramp', 'door', 'The Cold Ramp', 'A tongue of old snow lying up the back of the rib, hard all day and harder at night, running up at an angle you can just walk if you kick steps and do not stop. It is the shaded side, so the snow never rots, so the ramp is here in every month of the year. It is the only thing on this face that is reliable.', 0, 0, 'mountain', 0, 88, 6);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cold-ramp', 'east', 'the-rib-foot', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cold-ramp', 'west', 'the-late-field', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-hot-ledge', 'door', 'The Hot Ledge', 'A ledge a stride wide running east across the face above the scree, dry, dusty, and warm enough that the air over it shakes. There is nothing above it but rock and nothing below it for a long way. Everything with hooves on this side of the mountain uses it and the dust is beaten to powder.', 0, 0, 'mountain', 0, 86, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hot-ledge', 'east', 'the-sun-traverse', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hot-ledge', 'west', 'the-hot-scree', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-sun-traverse', 'door', 'The Sun Traverse', 'The ledge narrows to the width of your boots and holds that width for a hundred paces, with the rock leaning out slightly overhead so that you go along it turned half sideways. The stone is warm through your palms. There is no possibility of turning round on this and nothing to do about anything you meet.', 0, 0, 'mountain', 0, 87, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sun-traverse', 'east', 'the-dry-ledge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sun-traverse', 'west', 'the-hot-ledge', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-dry-ledge', 'door', 'The Dry Ledge', 'It widens again, and there is grit underfoot, and droppings, old and new and in two sizes. Something eats here regularly and something else waits for it here regularly, and the two of them have been keeping this appointment on a ledge a yard wide for a great many years.', 0, 0, 'mountain', 0, 88, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-dry-ledge', 'east', 'the-heather-step', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-dry-ledge', 'west', 'the-sun-traverse', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-heather-step', 'door', 'The Heather Step', 'The ledge runs out onto a step of broken ground with the first heather on it, ankle high and woody, and after the traverse the sheer amount of room to stand in is briefly ridiculous. Everything that came along the ledge stops here, and it shows: the heather is beaten into paths going three ways.', 0, 0, 'mountain', 0, 89, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-heather-step', 'east', 'the-upper-heather', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-heather-step', 'west', 'the-dry-ledge', NULL);
