-- Generated by scripts/build-rooms.mjs from: regions/mountain-4.rooms
-- 85 rooms, 240 exits. Do not hand-edit — regenerate from the source text.
-- Validated: every exit resolves, every exit has a return path (or is marked one-way),
-- no duplicate ids, no orphans, every room reachable from a gate.

-- the-cold-crest: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cold-crest', 'east', 'the-crest-step', NULL);

-- the-standing-cloud: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-standing-cloud', 'east', 'the-high-neve', NULL);

-- the-cloud-shelf: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cloud-shelf', 'east', 'the-drift-foot', NULL);

-- the-shelf-drop: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-shelf-drop', 'east', 'the-shelf-tail', NULL);

-- the-cloud-foot: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cloud-foot', 'east', 'the-fan-head', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-fan-head', 'door', 'The Fan Head', 'The cloud thins at the corner and the ground ahead falls away into a fan of grey stone running out further than you can see the end of, with everything the mountain has shed lying somewhere on it, sorted by weight. You are standing at the top of it. From here it is all downhill and none of it is walking.', 0, 0, 'mountain', 0, 98, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fan-head', 'east', 'the-catch-slope', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fan-head', 'west', 'the-cloud-foot', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-upper-brim', 'door', 'The Upper Brim', 'The top edge of the snowfield, where the white stops and the sky starts, and the line between them is so clean it looks cut. Snow curls over the edge in a lip you cannot see the underside of from here. Standing on the brim you can be seen from every square foot of this tier and from most of the one below it.', 0, 0, 'mountain', 0, 99, 5);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-upper-brim', 'south', 'the-snow-brim', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-upper-brim', 'east', 'the-frost-face', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-frost-face', 'door', 'The Frost Face', 'A face of old snow standing steeper than snow should stand, grown over in feathers of frost the length of your hand, all of them pointing into the wind. They break off when you touch them and go rattling away downhill for a long time. It is the only sound out here that anything makes on purpose.', 0, 0, 'mountain', 0, 100, 5);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-frost-face', 'south', 'the-white-slope', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-frost-face', 'west', 'the-upper-brim', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-snow-brim', 'door', 'The Snow Brim', 'Wind-packed snow that takes your weight for four steps out of five, and the fifth drops you to the knee without warning. There is no way to tell them apart by looking. After a while you stop trying and simply walk, and the mountain lets you off four times out of five.', 0, 0, 'mountain', 0, 99, 6);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-snow-brim', 'north', 'the-upper-brim', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-snow-brim', 'south', 'the-high-neve', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-snow-brim', 'east', 'the-white-slope', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-high-neve', 'door', 'The High Neve', 'You come out of the cloud into flat white light with no shadow in it anywhere, and the ground and the air are the same colour. This is where last year''s snow becomes next century''s ice, one weight at a time. It is perfectly quiet and enormously bright and there is not one thing to look at.', 0, 0, 'mountain', 0, 99, 7);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-high-neve', 'north', 'the-snow-brim', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-high-neve', 'south', 'the-drift-foot', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-high-neve', 'east', 'the-wind-slab', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-high-neve', 'west', 'the-standing-cloud', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-drift-foot', 'door', 'The Drift Foot', 'The bottom of a drift the size of a village, in the lee where the wind puts down everything it has been carrying. The snow here is deep and soft and slow, and a thing that came down the face this winter is somewhere under it, and will keep until spring, and spring does not come to this height.', 0, 0, 'mountain', 0, 99, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drift-foot', 'north', 'the-high-neve', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drift-foot', 'east', 'the-sun-cup', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drift-foot', 'west', 'the-cloud-shelf', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-white-slope', 'door', 'The White Slope', 'A long even slope of white with a single line of tracks going across it, made by something with a stride longer than yours, walking without hurrying, from nowhere in particular to nowhere in particular. The tracks are old enough to have gone hard and stand up in relief where the wind has taken the loose snow off round them.', 0, 0, 'mountain', 0, 100, 6);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-white-slope', 'north', 'the-frost-face', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-white-slope', 'south', 'the-wind-slab', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-white-slope', 'east', 'the-snow-dome', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-white-slope', 'west', 'the-snow-brim', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-wind-slab', 'door', 'The Wind Slab', 'Snow packed into a slab that rings hollow when you step on it, laid over softer stuff that will not hold it. It is stable until it is not, and the change happens all at once and across the whole width. Every step out here is a small argument with the surface about whose weight this is.', 0, 0, 'mountain', 0, 100, 7);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wind-slab', 'north', 'the-white-slope', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wind-slab', 'south', 'the-sun-cup', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wind-slab', 'east', 'the-broken-crust', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wind-slab', 'west', 'the-high-neve', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-sun-cup', 'door', 'The Sun Cup', 'The snow has melted into a field of shallow bowls a foot across, each with a ridge of ice standing between it and the next, so the whole surface is a honeycomb you cannot walk across without breaking. It is made by sunlight and it happens where nothing is ever warm. The mountain does this for its own reasons.', 0, 0, 'mountain', 0, 100, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sun-cup', 'north', 'the-wind-slab', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sun-cup', 'east', 'the-runnel', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sun-cup', 'west', 'the-drift-foot', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-snow-dome', 'door', 'The Snow Dome', 'A rise of snow with no rock in it at all — the ice underneath is deep enough that the shape of the mountain has been forgotten and the shape of the weather has taken over. From the top of it you can see the whole snowfield and everything standing on it, and everything standing on it can see you.', 0, 0, 'mountain', 0, 101, 6);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-snow-dome', 'south', 'the-broken-crust', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-snow-dome', 'east', 'the-hard-pack', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-snow-dome', 'west', 'the-white-slope', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-broken-crust', 'door', 'The Broken Crust', 'A hard crust over soft snow, broken into plates the size of doors and tipped every way, and something heavy went through it in a straight line not long ago. The holes are the shape of a foot and further apart than a person''s stride. They fill in slowly at this height.', 0, 0, 'mountain', 0, 101, 7);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-broken-crust', 'north', 'the-snow-dome', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-broken-crust', 'south', 'the-runnel', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-broken-crust', 'east', 'the-blue-shadow', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-broken-crust', 'west', 'the-wind-slab', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-runnel', 'door', 'The Runnel', 'A channel cut into the snow by meltwater that only runs for an hour a day, waist deep and smooth-walled and running dead straight downhill. In it you are out of the wind and out of sight of everything, which is the first of either since you came out of the cloud. It is also a channel, and things follow channels.', 0, 0, 'mountain', 0, 101, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-runnel', 'north', 'the-broken-crust', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-runnel', 'east', 'the-snow-hollow', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-runnel', 'west', 'the-sun-cup', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-hard-pack', 'door', 'The Hard Pack', 'Snow that has been blown on so long it has the texture of stone and will not take a print at all. Nothing crossing here leaves any record of having crossed. The east edge goes over in a cornice and there is no way down onto the ice from it — the drop is the whole height of the glacier''s flank.', 0, 0, 'mountain', 0, 102, 6);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hard-pack', 'south', 'the-blue-shadow', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-hard-pack', 'west', 'the-snow-dome', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-blue-shadow', 'door', 'The Blue Shadow', 'The shade under the cornice, where the light comes through the snow instead of onto it and everything in here is the colour of deep water. It is a good deal colder in the blue than four feet away in the white, and things that hunt on the snowfield know precisely where the line is.', 0, 0, 'mountain', 0, 102, 7);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-blue-shadow', 'north', 'the-hard-pack', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-blue-shadow', 'south', 'the-snow-hollow', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-blue-shadow', 'east', 'the-crevasse-lip', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-blue-shadow', 'west', 'the-broken-crust', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-snow-hollow', 'door', 'The Snow Hollow', 'A scoop dug back into the drift, deeper than weather makes and roofed by the drift above it, with room to sit up and no room to stand. Something dug this, more than once, in more than one winter. There is nothing in it now and nothing follows you into it, and out of the wind at this height that is very nearly everything.', 0, 1, 'mountain', 0, 102, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-snow-hollow', 'north', 'the-blue-shadow', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-snow-hollow', 'south', 'the-snow-tongue', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-snow-hollow', 'west', 'the-runnel', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-snow-tongue', 'door', 'The Snow Tongue', 'A finger of old snow running down off the field into the rocks, narrow enough to touch both edges, hard enough to walk and steep enough that you would not stop if you sat down. It is the one place the white ground and the grey ground meet without a drop between them, and everything that uses this mountain knows it.', 0, 0, 'mountain', 0, 102, 9);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-snow-tongue', 'north', 'the-snow-hollow', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-snow-tongue', 'south', 'the-tongue-foot', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-tongue-foot', 'door', 'The Tongue Foot', 'The snow ends in a wet grey lip a foot thick, undercut, dripping, with black rock showing under it. Below the lip the ground is stones. There is a smell here, faint and not fresh, of something that came down the tongue and did not get up.', 0, 0, 'mountain', 0, 102, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-tongue-foot', 'north', 'the-snow-tongue', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-tongue-foot', 'south', 'the-dry-bones', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-tongue-foot', 'east', 'the-red-edge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-tongue-foot', 'west', 'the-grey-run', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-shelf-tail', 'door', 'The Shelf Tail', 'The sun shelves finally run out — the grass gives up, then the moss, then the soil, and what is left is a tail of loose stone spilling east into open ground with nothing growing on it at all. It is the last step out of anywhere that feeds you.', 0, 0, 'mountain', 0, 98, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-shelf-tail', 'east', 'the-fall-fan', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-shelf-tail', 'west', 'the-shelf-drop', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-fall-fan', 'door', 'The Fall Fan', 'The bottom of the fan, where the smallest things end up: grit, chips, the light stuff that bounced furthest. It is soft walking and dull to look at and the only bones in it are small enough to take for gravel until you pick one up.', 0, 0, 'mountain', 0, 99, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fall-fan', 'north', 'the-bone-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fall-fan', 'east', 'the-lower-fan', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-fall-fan', 'west', 'the-shelf-tail', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-bone-ground', 'door', 'The Bone Ground', 'Bone, in quantity, lying loose among the stones over an area you could not cross in a minute — ribs, cannon bones, the long spiral of a horn, skulls with the teeth still bedded. None of it is arranged and none of it is fresh. Everything that dies anywhere above here comes to this fan eventually, and this is where the heavy pieces stop rolling.', 0, 0, 'mountain', 0, 99, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bone-ground', 'north', 'the-catch-slope', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bone-ground', 'south', 'the-fall-fan', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bone-ground', 'east', 'the-splinter-field', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-catch-slope', 'door', 'The Catch Slope', 'A slope of fine scree lying at exactly the angle it can hold, which catches what comes off the face above and holds it a while before letting it go again. Things sit here for years. There is a hind''s skull halfway up, sun-bleached on the top and still dark underneath, and nothing has moved it in a long time. The cloud stands in a wall along the western edge of it and the ground goes into that wall and stops being visible rather than stopping.', 0, 0, 'mountain', 0, 99, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-catch-slope', 'south', 'the-bone-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-catch-slope', 'east', 'the-boulder-nose', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-catch-slope', 'west', 'the-fan-head', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-boulder-nose', 'door', 'The Boulder Nose', 'A nose of solid rock standing out of the scree, the only thing on this fan that did not arrive by falling. It splits what comes down into two streams, and everything on one side of it goes west and everything on the other goes east, and the sorting the whole fan does starts here.', 0, 0, 'mountain', 0, 100, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-boulder-nose', 'south', 'the-splinter-field', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-boulder-nose', 'east', 'the-grey-run', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-boulder-nose', 'west', 'the-catch-slope', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-splinter-field', 'door', 'The Splinter Field', 'Rock broken into blades and splinters rather than pebbles — frost does this, over and over, until a boulder is a heap of knives lying edge-up. It is bad ground to walk and worse to fall on, and the animals cross it at a specific place because everything crosses it at that place.', 0, 0, 'mountain', 0, 100, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-splinter-field', 'north', 'the-boulder-nose', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-splinter-field', 'south', 'the-lower-fan', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-splinter-field', 'east', 'the-rib-cage', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-splinter-field', 'west', 'the-bone-ground', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-lower-fan', 'door', 'The Lower Fan', 'Where the fan flattens out and stops sorting, and everything that got this far lies mixed together: chips, splinters, one antler, half a jaw. Water runs under it rather than over it and you can hear that, faintly, through the stones.', 0, 0, 'mountain', 0, 100, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lower-fan', 'north', 'the-splinter-field', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lower-fan', 'east', 'the-scoured-flat', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lower-fan', 'west', 'the-fall-fan', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-grey-run', 'door', 'The Grey Run', 'A chute of grey stone worn smooth down the middle by everything that has come down it, running from the foot of the snow tongue out onto the fan. Standing in it is standing in the path. Nothing has come down it while you have been here, which is not the same as nothing coming down it.', 0, 0, 'mountain', 0, 101, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-grey-run', 'south', 'the-rib-cage', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-grey-run', 'east', 'the-tongue-foot', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-grey-run', 'west', 'the-boulder-nose', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-rib-cage', 'door', 'The Rib Cage', 'The ribcage of something the size of a horse, lying on its side, picked absolutely clean and gone the colour of the stones around it. The bones are still articulated and the arch of them makes a space underneath a person can lie in out of the weather. Nothing comes in here. Whatever cleaned this did it a very long time ago and has not been back.', 0, 1, 'mountain', 0, 101, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rib-cage', 'north', 'the-grey-run', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rib-cage', 'south', 'the-scoured-flat', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rib-cage', 'east', 'the-dry-bones', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rib-cage', 'west', 'the-splinter-field', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-scoured-flat', 'door', 'The Scoured Flat', 'A flat of packed grit swept bare by the wind that comes down the face every afternoon, so clean it looks swept on purpose. Bones that lie here do not stay — they go on down the fan. Only the heaviest thing in sight stays put, and the heaviest thing in sight is a vertebra the width of a dinner plate.', 0, 0, 'mountain', 0, 101, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-scoured-flat', 'north', 'the-rib-cage', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-scoured-flat', 'east', 'the-last-fan', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-scoured-flat', 'west', 'the-lower-fan', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-dry-bones', 'door', 'The Dry Bones', 'Bone that has been up here long enough to stop being bone in any useful sense: chalky, light as cork, crumbling at a touch and blowing away as powder. The mountain finishes everything eventually. Something has still been chewing on the ends of these, which is the only reason anything comes to this room.', 0, 0, 'mountain', 0, 102, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-dry-bones', 'north', 'the-tongue-foot', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-dry-bones', 'south', 'the-last-fan', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-dry-bones', 'east', 'the-red-scree', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-dry-bones', 'west', 'the-rib-cage', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-last-fan', 'door', 'The Last Fan', 'The eastern edge of the bone ground, where the grey stone gives out and the ground under your boots starts to have colour in it. The change happens across about ten feet. Behind you everything is the colour of ash; ahead of you everything is the colour of old blood, and neither of them grows anything.', 0, 0, 'mountain', 0, 102, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-last-fan', 'north', 'the-dry-bones', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-last-fan', 'east', 'the-rust-slope', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-last-fan', 'west', 'the-scoured-flat', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-red-edge', 'door', 'The Red Edge', 'The top edge of the red ground, a band of rust-coloured rock running along the hill as straight as a drawn line. Above it grey, below it red, and no gradual anything. It looks like the warmest ground on the mountain from any distance and is the coldest to stand on, because there is nothing here to hold a day''s heat.', 0, 0, 'mountain', 0, 103, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-red-edge', 'south', 'the-red-scree', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-red-edge', 'east', 'the-oxide-flat', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-red-edge', 'west', 'the-tongue-foot', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-oxide-flat', 'door', 'The Oxide Flat', 'A flat pavement of red rock furred over in a bloom of rust that comes off on your hands and does not wash off. Water lying in the hollows is the colour of tea and tastes of iron and pennies. Nothing drinks it. Nothing up here can afford to be that thirsty.', 0, 0, 'mountain', 0, 104, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-oxide-flat', 'south', 'the-iron-band', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-oxide-flat', 'east', 'the-burnt-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-oxide-flat', 'west', 'the-red-edge', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-burnt-ground', 'door', 'The Burnt Ground', 'Ground that looks scorched and never has been — the red goes almost black here, in patches with clean edges, and the rock rings differently underfoot from one patch to the next. The glacier''s toe comes down into the north side of it and the meeting of grey ice and black-red stone is the strangest-looking thing on this mountain.', 0, 0, 'mountain', 0, 105, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-burnt-ground', 'north', 'the-glacier-toe', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-burnt-ground', 'south', 'the-ochre-shelf', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-burnt-ground', 'east', 'the-high-red', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-burnt-ground', 'west', 'the-oxide-flat', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-high-red', 'door', 'The High Red', 'The top corner of the red ground, high enough to look back over the whole of it, and from here you can see it is not a slope but a bowl — everything drains to the middle and the middle drains nowhere. Whatever gets in has to come out the way it came in.', 0, 0, 'mountain', 0, 106, 10);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-high-red', 'south', 'the-scree-head', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-high-red', 'west', 'the-burnt-ground', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-red-scree', 'door', 'The Red Scree', 'Loose red stone at the exact angle it will hold, which is to say it is not holding, it is failing slowly the whole time you stand on it. Every step starts a small collapse that runs away downhill and gets quieter and never quite stops. There is no such thing as arriving here silently.', 0, 0, 'mountain', 0, 103, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-red-scree', 'north', 'the-red-edge', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-red-scree', 'south', 'the-rust-slope', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-red-scree', 'east', 'the-iron-band', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-red-scree', 'west', 'the-dry-bones', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-iron-band', 'door', 'The Iron Band', 'A seam of something harder standing proud of the scree, black-red and heavy and cold enough to take the skin off wet fingers. It rings when struck, which nothing else up here does. There are chips off it lying about, and the chips have edges you could cut with.', 0, 0, 'mountain', 0, 104, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-iron-band', 'north', 'the-oxide-flat', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-iron-band', 'south', 'the-stained-run', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-iron-band', 'east', 'the-ochre-shelf', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-iron-band', 'west', 'the-red-scree', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-ochre-shelf', 'door', 'The Ochre Shelf', 'A shelf of soft yellow-red stone that crumbles under a boot into powder the colour of a brick, and everything that has crossed it recently has left a print with a clean edge. There are a lot of prints. Only two kinds, and both of them are the kind with claws.', 0, 0, 'mountain', 0, 105, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ochre-shelf', 'north', 'the-burnt-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ochre-shelf', 'south', 'the-red-gully', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ochre-shelf', 'east', 'the-scree-head', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ochre-shelf', 'west', 'the-iron-band', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-scree-head', 'door', 'The Scree Head', 'The head of the gully that drains the whole red bowl, where all the loose stuff on this hillside is queuing to go down one channel. It is like standing at the top of an hourglass. Everything about the ground here is on its way somewhere and only stopped because the ones underneath have not moved yet.', 0, 0, 'mountain', 0, 106, 11);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-scree-head', 'north', 'the-high-red', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-scree-head', 'south', 'the-gully-top', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-scree-head', 'west', 'the-ochre-shelf', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-rust-slope', 'door', 'The Rust Slope', 'A long slope of small red stones with nothing whatever growing on it, running down out of sight to the south. The colour is so even and so total that after a while your eyes give up looking for detail and you find you have walked a long way without noticing anything at all, which is how ground like this gets people.', 0, 0, 'mountain', 0, 103, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rust-slope', 'north', 'the-red-scree', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rust-slope', 'east', 'the-stained-run', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-rust-slope', 'west', 'the-last-fan', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-stained-run', 'door', 'The Stained Run', 'Where water has run down the red rock for long enough to stain a stripe darker than the ground either side, twenty feet wide and running the whole length of the slope. It is dry now. It is dry for eleven months and it moves the entire hillside in the twelfth.', 0, 0, 'mountain', 0, 104, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-stained-run', 'north', 'the-iron-band', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-stained-run', 'east', 'the-red-gully', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-stained-run', 'west', 'the-rust-slope', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-red-gully', 'door', 'The Red Gully', 'A gully cut deep into the red, walls above head height, floor of loose stone, and everything that comes off this side of the mountain funnels into it. Down here you can see nothing but the two walls and the strip of sky. Something has been sleeping against the west wall, in the dry, and the shape of it is still in the grit.', 0, 0, 'mountain', 0, 105, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-red-gully', 'north', 'the-ochre-shelf', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-red-gully', 'east', 'the-gully-top', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-red-gully', 'west', 'the-stained-run', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-gully-top', 'door', 'The Gully Top', 'The gully''s head narrows to a slot you could touch both sides of, and above it the ground simply stops — the whole drainage of the red bowl comes through a gap the width of a door. Everything up here that moves has to come through this, or go round the entire hillside.', 0, 0, 'mountain', 0, 106, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-gully-top', 'north', 'the-scree-head', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-gully-top', 'west', 'the-red-gully', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-crest-step', 'door', 'The Crest Step', 'The permanent ice ends and rock begins, and the rock is a step up onto the crest of a ridge that runs away east as far as you can see it. Both sides fall away immediately. From this step on there is no such thing as walking round anything.', 0, 0, 'mountain', 0, 99, 3);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-crest-step', 'north', 'the-first-notch', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-crest-step', 'east', 'the-knife', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-crest-step', 'west', 'the-cold-crest', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-first-notch', 'door', 'The First Notch', 'A gap in the crest where the ridge dips and the wind comes through from the far side hard enough to lean on. Standing in the notch you can see down the north face, which nobody has any reason to look at twice: it is black, it is vertical, and there is nothing on it.', 0, 0, 'mountain', 0, 99, 2);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-first-notch', 'south', 'the-crest-step', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-knife', 'door', 'The Knife', 'The ridge narrows to the width of a plank of stone with air on both sides and a very long way down on each. There is no wind shelter, no wide place and nothing to hold. The only way to do this is to keep going at a steady pace and not stop in the middle to think about it.', 0, 0, 'mountain', 0, 100, 3);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-knife', 'north', 'the-north-drop', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-knife', 'east', 'the-second-notch', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-knife', 'west', 'the-crest-step', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-north-drop', 'door', 'The North Drop', 'A step off the north side of the ridge onto a ledge the size of a table, which is the only place on this whole crest a person can sit down. It ends in nothing. Birds have been using it: the rock is white with them, and there are pellets, and the pellets are full of small bones.', 0, 0, 'mountain', 0, 100, 2);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-north-drop', 'south', 'the-knife', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-second-notch', 'door', 'The Second Notch', 'Another dip in the crest, deeper than the first, with old snow lying in the bottom of it that never sees sun. Something crossed the snow within the last day or so. The prints go over the ridge and down the north side, which is not something with four legs should be able to do.', 0, 0, 'mountain', 0, 101, 3);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-second-notch', 'north', 'the-gendarme', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-second-notch', 'east', 'the-ridge-walk', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-second-notch', 'west', 'the-knife', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-gendarme', 'door', 'The Gendarme', 'A tower of rock standing on the ridge like a post, twice your height, that everything has to go round. There is a worn line round its base on the south side where everything has gone round it, and the wear is deep enough to be a path in its own right. Nothing has ever gone round it on the north.', 0, 0, 'mountain', 0, 101, 2);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-gendarme', 'south', 'the-second-notch', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-ridge-walk', 'door', 'The Ridge Walk', 'Broad enough here to walk two abreast, and after the knife that feels like a road. The rock is shattered into loose plates that slide against each other under your weight and make a noise like crockery. You are audible from a very long way off along a ridge, in both directions.', 0, 0, 'mountain', 0, 102, 3);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ridge-walk', 'north', 'the-wind-tooth', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ridge-walk', 'east', 'the-third-notch', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ridge-walk', 'west', 'the-second-notch', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-wind-tooth', 'door', 'The Wind Tooth', 'A blade of rock standing off the north side, undercut by the wind until it is thinner at the bottom than the top. It hums. Not loudly, and not always, but in a steady wind the whole tooth resonates and you can feel it through the soles of your boots before you can hear it.', 0, 0, 'mountain', 0, 102, 2);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wind-tooth', 'south', 'the-ridge-walk', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-third-notch', 'door', 'The Third Notch', 'The last dip, and the widest, filled to the brim with hard old snow so that the ridge appears to be continuous when it is in fact a gap with snow in it. How much of the snow is standing on rock and how much is standing on itself is not a question this notch will answer from up here.', 0, 0, 'mountain', 0, 103, 3);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-third-notch', 'north', 'the-lean', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-third-notch', 'east', 'the-ridge-end', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-third-notch', 'west', 'the-ridge-walk', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-lean', 'door', 'The Lean', 'A slab the size of a barn door that came off the ridge and did not fall — it leaned against what it came off and stopped, leaving a triangular gap underneath, dry and dark and out of the wind. There are old droppings in the back of it, dried to nothing, and a smell that has almost gone.', 0, 0, 'mountain', 0, 103, 2);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lean', 'south', 'the-third-notch', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-ridge-end', 'door', 'The Ridge End', 'The crest broadens, loses its edge, and dies into a shoulder of broken rock. After a mile of having nothing on either side of you, ground that goes on in more than one direction is briefly disorienting, and you will stand here longer than you need to.', 0, 0, 'mountain', 0, 104, 3);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ridge-end', 'north', 'the-last-tooth', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ridge-end', 'south', 'the-ridge-drop', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ridge-end', 'west', 'the-third-notch', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-last-tooth', 'door', 'The Last Tooth', 'The final pinnacle on the crest, and the only one you can get on top of. From up here the whole tier lies out below — the white of the snowfield, the grey fan, the red bowl, the ice — and above all of them the swept ground, and past that the shape you cannot see the top of.', 0, 0, 'mountain', 0, 104, 2);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-last-tooth', 'south', 'the-ridge-end', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-ridge-drop', 'door', 'The Ridge Drop', 'The shoulder drops away to the glacier''s head, and between the rock and the ice there is a gap running the whole width of it — the ice has pulled away from the mountain and gone on downhill without it. There is one snow bridge across, and one is enough, and it is not a thing to stand about on.', 0, 0, 'mountain', 0, 104, 4);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ridge-drop', 'north', 'the-ridge-end', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ridge-drop', 'south', 'the-white-tower', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-serac-field', 'door', 'The Serac Field', 'The ice has gone over a step in the rock beneath it and broken into towers and blocks the size of houses, leaning every way, with lanes of shadow between them. Some of these will fall this year. Nothing about looking at them tells you which, and the lanes between them are the only way through.', 0, 0, 'mountain', 0, 103, 5);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-serac-field', 'south', 'the-ice-blocks', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-serac-field', 'east', 'the-white-tower', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-ice-blocks', 'door', 'The Ice Blocks', 'Fallen towers lying where they landed, already rounding off at the corners, some of them clear enough to see a foot into and some of them white as chalk. Between two of them there is a gap you go through sideways and it is the coldest air on the mountain.', 0, 0, 'mountain', 0, 103, 6);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ice-blocks', 'north', 'the-serac-field', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ice-blocks', 'south', 'the-crevasse-lip', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ice-blocks', 'east', 'the-blue-ice', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-crevasse-lip', 'door', 'The Crevasse Lip', 'The edge of a crack across the whole glacier, wide enough to swallow a cart, with walls that go from white to blue to a blue so dark it reads as black. There is no bottom visible. Things that go in here come out at the toe, later, a great deal later, and in the condition they went in.', 0, 0, 'mountain', 0, 103, 7);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-crevasse-lip', 'north', 'the-ice-blocks', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-crevasse-lip', 'south', 'the-glacier-bend', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-crevasse-lip', 'east', 'the-slot', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-crevasse-lip', 'west', 'the-blue-shadow', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-glacier-bend', 'door', 'The Glacier Bend', 'The ice turns a corner round a buttress of rock, and turning has torn it: the whole flank is a fan of cracks, none of them wide, all of them deep. Walking it is a matter of stepping over things you cannot see the end of, one after another, for longer than is comfortable.', 0, 0, 'mountain', 0, 103, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-glacier-bend', 'north', 'the-crevasse-lip', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-glacier-bend', 'east', 'the-melt-lip', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-white-tower', 'door', 'The White Tower', 'A serac standing alone at the head of the ice, taller than the rest and gone chalk-white with age, leaning very slightly downhill the way they all do just before. Under it the snow bridge from the ridge comes in. This is the head of the glacier and everything on the glacier started here.', 0, 0, 'mountain', 0, 104, 5);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-white-tower', 'north', 'the-ridge-drop', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-white-tower', 'south', 'the-blue-ice', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-white-tower', 'east', 'the-ice-plain', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-white-tower', 'west', 'the-serac-field', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-blue-ice', 'door', 'The Blue Ice', 'Bare ice with no snow on it at all, polished by wind, hard as glass and the colour of a deep pool. You can see down into it a long way, and about four feet under the surface there is something dark and about the size of a dog, and it is going to be another century getting to the bottom.', 0, 0, 'mountain', 0, 104, 6);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-blue-ice', 'north', 'the-white-tower', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-blue-ice', 'south', 'the-slot', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-blue-ice', 'east', 'the-drift-hollow', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-blue-ice', 'west', 'the-ice-blocks', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-slot', 'door', 'The Slot', 'A crevasse so narrow you could step across it without thinking, and that is the danger of it — it is bridged over by a foot of snow along most of its length and the bridge looks exactly like the ground either side. Where it is open you can see it goes down further than the wide ones do.', 0, 0, 'mountain', 0, 104, 7);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-slot', 'north', 'the-blue-ice', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-slot', 'south', 'the-melt-lip', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-slot', 'east', 'the-glacier-head', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-slot', 'west', 'the-crevasse-lip', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-melt-lip', 'door', 'The Melt Lip', 'The ice ends in a wall twice your height, undercut by its own meltwater into an overhanging lip with a cave under it, and the cave breathes cold and drips steadily. Nothing hangs about under a lip like this. The ice above it is standing on the air it has melted out from under itself.', 0, 0, 'mountain', 0, 104, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-melt-lip', 'north', 'the-slot', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-melt-lip', 'south', 'the-melt-run', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-melt-lip', 'east', 'the-moulin', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-melt-lip', 'west', 'the-glacier-bend', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-ice-plain', 'door', 'The Ice Plain', 'Flat ice under an inch of dry snow, the smoothest ground on the whole mountain, running for what looks like half a mile. It is a pleasure to walk on, which is the trap: there is nothing to hold your attention here and you will not notice the surface stop being ice and start being roof.', 0, 0, 'mountain', 0, 105, 5);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ice-plain', 'south', 'the-drift-hollow', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ice-plain', 'east', 'the-stone-desert', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-ice-plain', 'west', 'the-white-tower', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-drift-hollow', 'door', 'The Drift Hollow', 'A hollow in the lee of a rock frozen into the ice, drifted over into a chamber with a floor of dry snow and a doorway a person has to crawl through. It is out of the wind entirely and nothing bigger than you can get in. There are no tracks going in. There are none coming out either.', 0, 1, 'mountain', 0, 105, 6);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drift-hollow', 'north', 'the-ice-plain', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drift-hollow', 'south', 'the-glacier-head', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drift-hollow', 'east', 'the-swept-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drift-hollow', 'west', 'the-blue-ice', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-glacier-head', 'door', 'The Glacier Head', 'Where the ice comes hard against the rock of the upper mountain and buckles against it, thrown up into a ridge of broken white along the join. Everything that falls off the scoured ground above lands somewhere along this line, and the line is a mile long, and you can walk it.', 0, 0, 'mountain', 0, 105, 7);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-glacier-head', 'north', 'the-drift-hollow', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-glacier-head', 'south', 'the-moulin', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-glacier-head', 'east', 'the-pavement', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-glacier-head', 'west', 'the-slot', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-moulin', 'door', 'The Moulin', 'A round shaft in the ice, six feet across and perfectly circular, with a stream going into it and no sound of the stream arriving anywhere. The walls are ribbed and blue and turn out of sight within twenty feet. Snow at the lip is packed hard by something that has stood here and looked in, more than once.', 0, 0, 'mountain', 0, 105, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-moulin', 'north', 'the-glacier-head', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-moulin', 'east', 'the-cold-terrace', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-moulin', 'west', 'the-melt-lip', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-melt-run', 'door', 'The Melt Run', 'A channel of grey stone under the lip of the ice, running with meltwater in the afternoon and dry by dark, floored in silt so fine it takes a print like wax. The prints in it now are from this morning. There are three sets and they are all going the same way.', 0, 0, 'mountain', 0, 104, 9);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-melt-run', 'north', 'the-melt-lip', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-melt-run', 'east', 'the-glacier-toe', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-glacier-toe', 'door', 'The Glacier Toe', 'The end of the ice, filthy with the rock it has carried, giving back the things it took in at the top — stones, gravel, a scatter of bone, all of it in the same condition it went in and none of it from any animal that has been up here in living memory. This is the only place the ice and the red ground touch.', 0, 0, 'mountain', 0, 105, 9);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-glacier-toe', 'south', 'the-burnt-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-glacier-toe', 'west', 'the-melt-run', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-stone-desert', 'door', 'The Stone Desert', 'Bare rock from here to the skyline, broken into flat plates and swept clean of every loose thing, with wind coming across it that has not touched anything since the sea. There is no snow. There is no ice. There is nothing here for anything, and the completeness of it is what you notice.', 0, 0, 'mountain', 0, 106, 5);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-stone-desert', 'south', 'the-swept-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-stone-desert', 'east', 'the-cold-plain', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-stone-desert', 'west', 'the-ice-plain', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-swept-ground', 'door', 'The Swept Ground', 'Stone pavement blown so clean that a stone the size of a fist looks like it was placed. Below this the whole mountain is either producing something or eating something. This is the first ground on the climb that is doing neither, and after four tiers of a hillside busy with living the silence of it is the loudest thing about it.', 0, 0, 'mountain', 0, 106, 6);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-swept-ground', 'north', 'the-stone-desert', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-swept-ground', 'south', 'the-pavement', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-swept-ground', 'east', 'the-wind-cut', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-swept-ground', 'west', 'the-drift-hollow', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-pavement', 'door', 'The Pavement', 'Frost has broken the rock into slabs with straight cracks between them, laid out in a pattern that looks made from a distance and looks like nothing at all from on top of it. Water gets in the cracks, freezes, and takes the rock apart another notch, every night of every year, forever.', 0, 0, 'mountain', 0, 106, 7);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-pavement', 'north', 'the-swept-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-pavement', 'south', 'the-cold-terrace', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-pavement', 'east', 'the-approach', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-pavement', 'west', 'the-glacier-head', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-cold-terrace', 'door', 'The Cold Terrace', 'A terrace under the swept ground, lower and out of the main of the wind, where the loose stuff the pavement sheds collects in a strip along the back wall. It is the last ground on this tier with any shelter in it at all, and it is where anything that intends to be up here for a night is going to be.', 0, 0, 'mountain', 0, 106, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cold-terrace', 'north', 'the-pavement', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cold-terrace', 'east', 'the-shelf-under', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cold-terrace', 'west', 'the-moulin', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-cold-plain', 'door', 'The Cold Plain', 'A plain of frost-shattered rock with a sky over it that is a darker blue than sky is at any height you have stood at before. There is nothing between you and it. The cold up here is not the wet cold of the corries — it is dry, and it takes the moisture out of you without ever once feeling like weather.', 0, 0, 'mountain', 0, 107, 5);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cold-plain', 'south', 'the-wind-cut', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cold-plain', 'west', 'the-stone-desert', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-wind-cut', 'door', 'The Wind Cut', 'A trench worn into solid rock by nothing but moving air and the grit it carries, a foot deep and running dead straight for two hundred paces. The stone in the bottom of it is polished. Whatever the wind does up here, it has been doing since before there was anything on this mountain to watch it.', 0, 0, 'mountain', 0, 107, 6);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wind-cut', 'north', 'the-cold-plain', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wind-cut', 'south', 'the-approach', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wind-cut', 'east', 'the-last-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wind-cut', 'west', 'the-swept-ground', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-approach', 'door', 'The Approach', 'The ground begins to rise again after a mile of not rising, and rises evenly, and the evenness is the odd part — everything else on this mountain is broken. Nothing is growing, nothing is living, and there is not one bone here, which after the ground you have come across is the thing you notice.', 0, 0, 'mountain', 0, 107, 7);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-approach', 'north', 'the-wind-cut', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-approach', 'south', 'the-shelf-under', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-approach', 'east', 'the-summit-foot', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-approach', 'west', 'the-pavement', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-shelf-under', 'door', 'The Shelf Under', 'A shelf under the approach, wide and level, that ought to be a nesting ledge — it faces the sun, it is out of the wind, it has a wall at its back. It has been used as one. The old nests are still on it, three of them, packed with sticks carried up from four tiers down, and every one of them is empty and has been for years.', 0, 0, 'mountain', 0, 107, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-shelf-under', 'north', 'the-approach', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-shelf-under', 'east', 'the-under-shelf', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-shelf-under', 'west', 'the-cold-terrace', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-last-ground', 'door', 'The Last Ground', 'The last of the flat, and the ground here has been swept in a way the wind does not sweep: the loose stone is pushed to the edges of the room in a rough band, and the middle of it is bare rock over an area the size of a barn. The wind at this height comes from one direction. Whatever cleared this did not.', 0, 0, 'mountain', 0, 108, 6);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-last-ground', 'south', 'the-summit-foot', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-last-ground', 'west', 'the-wind-cut', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-summit-foot', 'door', 'The Summit Foot', 'The foot of the last rise, where the mountain stops being a mountain you walk up and becomes a thing standing over you. The rock changes here — it is darker, and glazed, and in places it has run and set again. Nothing on this tier has an explanation for that. Nothing on this tier comes up here either: no tracks, no droppings, no bones, nothing.', 0, 0, 'mountain', 0, 108, 7);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-summit-foot', 'north', 'the-last-ground', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-summit-foot', 'south', 'the-under-shelf', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-summit-foot', 'east', 'the-way-up', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-summit-foot', 'west', 'the-approach', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-under-shelf', 'door', 'The Under-Shelf', 'A shelf tucked under the summit foot, out of sight from above, and the ground in it is a foot deep in bone chips — small ones, all of them cracked, all of them the same size, as though everything larger had been sorted out and taken away. Whatever eats here does not eat here. It brings it down.', 0, 0, 'mountain', 0, 108, 8);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-under-shelf', 'north', 'the-summit-foot', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-under-shelf', 'west', 'the-shelf-under', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-way-up', 'door', 'The Way Up', 'A ramp of dark rock running up out of the last ground into the cloud that stands on the summit whatever the weather is doing anywhere else. It is scoured bare and it is warm underfoot — genuinely warm, in a place where the shade never rises above freezing — and it goes up out of sight. Nothing follows you onto it. Not one thing on this mountain will set foot on this.', 0, 0, 'mountain', 0, 109, 7);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-way-up', 'west', 'the-summit-foot', NULL);
