-- Generated by scripts/build-rooms.mjs from: regions/mountain-6.rooms
-- 2 rooms, 2 exits. Do not hand-edit — regenerate from the source text.
-- Validated: every exit resolves, every exit has a return path (or is marked one-way),
-- no duplicate ids, no orphans, every room reachable from a gate.

-- the-summit-gate: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-summit-gate', 'east', 'the-summit', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-summit', 'door', 'The Summit', 'The wall opens and the top of the mountain is a bowl of bare rock perhaps two hundred paces across, and there is nothing in it: no snow, no ice, no lichen, no bone. The floor is swept and it is warm. Off the middle of it the rock has run and set in ropes and lobes with the front edges curled over, in a rough ring, and inside the ring the stone is glazed and black and worn smooth in the way a doorstep is worn. The whole sky is here. There is no higher ground anywhere you can see in any direction, and nothing between you and any of it. Whatever made this ring is not small and does not need to be anywhere else, and the wind that has been on you for five tiers has stopped, because there is nothing up here for it to come round.', 0, 0, 'mountain', 0, 120, 3);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-summit', 'west', 'the-summit-gate', NULL);
