-- Generated by scripts/build-rooms.mjs from: regions/crossing-6.rooms
-- 8 rooms, 14 exits. Do not hand-edit — regenerate from the source text.
-- Validated: every exit resolves, every exit has a return path (or is marked one-way),
-- no duplicate ids, no orphans, every room reachable from a gate.

-- the-marsh-road: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-marsh-road', 'east', 'the-sea-dyke', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-sea-dyke', 'door', 'The Sea Dyke', 'An old turf bank running north and south, thrown up by hand to keep the tide off ground that has since stopped being worth keeping it off. It is breached in two places within sight and nobody has closed either. The way east goes over it on a worn ramp of the same turf, and from the top you can see how flat everything ahead of you is, and how far away the hill is that all of it drains toward.', 0, 0, 'crossing', 0, 64, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sea-dyke', 'west', 'the-marsh-road', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sea-dyke', 'east', 'the-flashes', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-flashes', 'door', 'The Flashes', 'Standing water in sheets across the salting, too shallow to be pools and too wide to be puddles, lying in every dip the tide ever cut. They are brackish and still and they hold the sky perfectly, so the ground reads as a broken mirror laid out flat to the east. Wading is unavoidable. Nothing here is deeper than your boot and all of it is colder than you expect.', 0, 0, 'crossing', 0, 65, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-flashes', 'west', 'the-sea-dyke', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-flashes', 'east', 'the-drain-cut', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-drain-cut', 'door', 'The Drain Cut', 'A straight channel, cut dead east by people who wanted the water off this ground and had the labour to insist on it. It has silted to half its depth and the reeds have taken the rest, but it still runs, and it still runs the right way. Following a drain inland is the oldest way there is of finding out where the water came from.', 0, 0, 'crossing', 0, 66, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drain-cut', 'west', 'the-flashes', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drain-cut', 'east', 'the-wet-carr', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-wet-carr', 'door', 'The Wet Carr', 'Scrub willow and sallow standing in water, none of it higher than a man, all of it leaning the same way off the wind that comes down off the hill. The ground between the stems is not ground — it is root and black water and a mat of last year''s leaves floating on top of both, and it takes your weight right up until it doesn''t.', 0, 0, 'crossing', 0, 67, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wet-carr', 'west', 'the-drain-cut', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wet-carr', 'east', 'the-burn-flats', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-burn-flats', 'door', 'The Burn Flats', 'The silt gives out and there is gravel underfoot, grey and rounded and graded by size the way only running water grades anything. This is what the hill has been sending down here for a very long time, spread flat where the water lost the speed to carry it further. The stones get bigger toward the east, which tells you which way you are about to be going.', 0, 0, 'crossing', 0, 68, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-burn-flats', 'west', 'the-wet-carr', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-burn-flats', 'east', 'the-outfall', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-outfall', 'door', 'The Outfall', 'Where the hill''s water finally reaches the flat and stops being a burn: it comes out of the alders ahead in one brown chute, hits the gravel, spreads, and gives up. Standing in the spread of it you can hear the whole of it working somewhere up in the trees, much louder than what is arriving at your feet. Everything you have walked since the dyke came out of here.', 0, 0, 'crossing', 0, 69, 12);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-outfall', 'west', 'the-burn-flats', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-outfall', 'east', 'the-alder-thicket', NULL);

-- the-alder-thicket: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-alder-thicket', 'west', 'the-outfall', NULL);

-- ============================ WHO LIVES ON IT ============================
--
-- Four, off the marsh's own roster, because a corridor with nothing in it is
-- not a route — it is a bypass, and it would have made the low way strictly
-- safer than the stair for no reason but that it was newer.
--
-- The placing is the point as much as the count. TERRITORY_RADIUS is 3, so a
-- creature holds three rooms of ground around its den and no more: with dens
-- only at the ends, the middle of a six-room corridor is ground nothing alive
-- can reach, and the marsh and the mountain would have gone on being two
-- ecologies with a dead passage between them. At x64, x65, x67 and x69 the four
-- territories overlap each other AND both ends, so the salting way is walked.
INSERT INTO mob_spawns (room_id, template_id) VALUES
  -- a viper on a sun-warmed turf bank, which is where a viper is
  ('the-sea-dyke',   'fen-viper'),
  -- standing water and reed: the bittern's whole animal
  ('the-flashes',    'bittern'),
  -- wet scrub, and the hound is the marsh's own hunter
  ('the-wet-carr',   'marsh-hound'),
  -- the burn's chute, coming off the hill
  ('the-outfall',    'ford-eel');
