-- Generated by scripts/build-rooms.mjs from: regions/the-deep-2.rooms
-- 65 rooms, 122 exits. Do not hand-edit — regenerate from the source text.
-- Validated: every exit resolves, every exit has a return path (or is marked one-way),
-- no duplicate ids, no orphans, every room reachable from a gate.

-- weeping-cells: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('weeping-cells', 'west', 'the-sluice-walk', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-sluice-walk', 'door', 'The Sluice-Walk', 'A stone ledge a boot wide runs along a channel of black water, the wall at your other shoulder slick and close. Iron rings are set into it every few paces at the height of a hand, and every one of them is worn bright.', 0, 0, 'deep', 0, -1, 49);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sluice-walk', 'east', 'weeping-cells', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sluice-walk', 'west', 'the-chain-well', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sluice-walk', 'north', 'the-flooded-cloister', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-chain-well', 'door', 'The Chain-Well', 'A square shaft of water in the floor, and hanging down into it from somewhere above, a chain with links the size of a fist. It goes down further than the water lets you see. Every so often it moves, one link''s worth, and is still again.', 0, 0, 'deep', 0, -2, 49);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-chain-well', 'east', 'the-sluice-walk', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-chain-well', 'north', 'the-sunk-bell', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-flooded-cloister', 'door', 'The Flooded Cloister', 'Four arcades around a court that is a pool now, the water standing level with the walk so that you cannot tell where the path stops. The pillars go down into their reflections, and the reflections go on further than the pillars do.', 0, 0, 'deep', 0, -1, 48);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-flooded-cloister', 'south', 'the-sluice-walk', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-flooded-cloister', 'west', 'the-sunk-bell', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-sunk-bell', 'door', 'The Sunk Bell', 'A bell the height of a man lies on its lip in the middle of the floor, cracked from crown to rim and half sunk in silt. It fell from somewhere. There is nothing above it now but dark. When the water moves against it, it hums.', 0, 0, 'deep', 0, -2, 48);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sunk-bell', 'east', 'the-flooded-cloister', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sunk-bell', 'south', 'the-chain-well', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sunk-bell', 'west', 'the-silt-bank', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-silt-bank', 'door', 'The Silt-Bank', 'The flood has dropped its load here: a long bank of grey silt shelving up out of the water, soft and faintly warm, printed all over with tracks. Most of the tracks come up out of the water. Fewer of them go back in.', 0, 0, 'deep', 0, -3, 48);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-silt-bank', 'east', 'the-sunk-bell', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-silt-bank', 'north', 'the-drowned-kitchens', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-silt-bank', 'west', 'the-charnel-chute', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-drowned-kitchens', 'door', 'The Drowned Kitchens', 'Hearths big enough to stand in, a spit-rack rusted into one red lump, and stone troughs where a garrison''s food was once washed. The water is at the knee and very cold. Something has been keeping the troughs clear.', 0, 0, 'deep', 0, -3, 47);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drowned-kitchens', 'south', 'the-silt-bank', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drowned-kitchens', 'west', 'the-cold-pantry', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-cold-pantry', 'door', 'The Cold Pantry', 'A low store-room on a step above the flood, lined with shelves cut into the rock. Whatever was kept here was kept against a long siege, and the siege won. The shelves are bare except for the bones, which somebody has sorted by size.', 0, 0, 'deep', 0, -4, 47);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cold-pantry', 'east', 'the-drowned-kitchens', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cold-pantry', 'south', 'the-charnel-chute', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-charnel-chute', 'door', 'The Charnel Chute', 'A slot in the floor, polished like a slide by everything that ever went down it: the garrison''s dead, when there got to be too many to carry up. The draught that comes out of it is dry and smells of dust and old marrow. There is no stair. There is only down.', 0, 0, 'deep', 0, -4, 48);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-charnel-chute', 'north', 'the-cold-pantry', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-charnel-chute', 'east', 'the-silt-bank', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-charnel-chute', 'down', 'the-chute-foot', NULL);

-- black-canal: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('black-canal', 'north', 'the-lock-keepers-room', NULL);

-- the-weir: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-weir', 'north', 'the-sluice-gear', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-lock-keepers-room', 'door', 'The Lock-Keeper''s Room', 'A little room above the canal where somebody once worked the water: a stool, a peg-board of tallies for barges that never came, and a window of iron bars looking down on the black channel. The tallies stop partway along a row.', 0, 0, 'deep', 0, 3, 47);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lock-keepers-room', 'south', 'black-canal', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lock-keepers-room', 'east', 'the-sluice-gear', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-sluice-gear', 'door', 'The Sluice-Gear', 'The winding gear for the weir''s gates: two great wooden drums on iron axles, their chains running down through slots in the floor. The drums are swollen and split and will never turn again. Under the slots the weir roars on, as if nobody had ever tried to stop it.', 0, 0, 'deep', 0, 4, 47);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sluice-gear', 'south', 'the-weir', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sluice-gear', 'west', 'the-lock-keepers-room', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sluice-gear', 'east', 'the-flood-mark', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-flood-mark', 'door', 'The Flood-Mark', 'A narrow room whose walls are ruled with high-water marks, each one cut by hand and dated in some old reckoning, climbing the stone year by year. The last and highest is above your head. Nothing was cut after it.', 0, 0, 'deep', 0, 5, 47);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-flood-mark', 'west', 'the-sluice-gear', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-chute-foot', 'door', 'The Chute''s Foot', 'The chute spits you out onto a slope of loose bone that shifts and settles under you like shingle. Everything that was ever sent down lies here in a fan, the newest on top. Getting back up means climbing the chute against its own polish.', 0, 0, 'deep', 0, -3, 49);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-chute-foot', 'up', 'the-charnel-chute', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-chute-foot', 'south', 'the-blind-gallery', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-blind-gallery', 'door', 'The Blind Gallery', 'A gallery built for eyes that has lost the use of them. Niches are cut all along the walls at head height, each with a stone lamp in it, and every lamp is full of dust. Nobody has lit anything here in longer than the dust has been falling.', 0, 0, 'deep', 0, -3, 50);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-blind-gallery', 'north', 'the-chute-foot', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-blind-gallery', 'west', 'the-scraped-hall', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-blind-gallery', 'south', 'the-feeling-wall', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-scraped-hall', 'door', 'The Scraped Hall', 'Every surface in this room has been scraped. Not carved: scraped, in long parallel grooves at the height of something crouching, as if it went round and round the walls feeling for the way out. It did not find it here.', 0, 0, 'deep', 0, -4, 50);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-scraped-hall', 'east', 'the-blind-gallery', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-scraped-hall', 'south', 'the-wormcast-pit', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-wormcast-pit', 'door', 'The Wormcast Pit', 'A round pit in the floor, filled to the brim with coiled grey castings, cold and dry and packed as hard as mortar. Some of the coils are as thick as your thigh. The newest ones, on top, are not dry.', 0, 0, 'deep', 0, -4, 51);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wormcast-pit', 'north', 'the-scraped-hall', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-wormcast-pit', 'east', 'the-feeling-wall', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-feeling-wall', 'door', 'The Feeling Wall', 'A passage so narrow and so dark that the stone at your shoulder has been worn smooth by hands. Not yours, not recent, and not all of them hands. The polish runs at the height of a hip, and then, lower down, at the height of a belly.', 0, 0, 'deep', 0, -3, 51);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-feeling-wall', 'north', 'the-blind-gallery', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-feeling-wall', 'west', 'the-wormcast-pit', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-feeling-wall', 'east', 'the-gnawed-arch', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-gnawed-arch', 'door', 'The Gnawed Arch', 'An arch of good dressed stone with half its blocks gnawed away, the tooth-marks on them the width of a thumb. It has held this long on the other half. The bitten stone lies in a heap underneath, and none of it has been eaten. Only taken down.', 0, 0, 'deep', 0, -2, 51);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-gnawed-arch', 'west', 'the-feeling-wall', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-gnawed-arch', 'east', 'the-bored-passage', NULL);

-- worm-cloister: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('worm-cloister', 'south', 'the-bored-passage', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-bored-passage', 'door', 'The Bored Passage', 'The worm-holes of the cloister open here into one bore big enough to walk in bent double, perfectly round and perfectly smooth, its floor grooved down the middle by the weight of whatever made it. The groove is not old.', 0, 0, 'deep', 0, -1, 51);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bored-passage', 'north', 'worm-cloister', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bored-passage', 'west', 'the-gnawed-arch', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bored-passage', 'south', 'the-crawlway', NULL);

-- carrion-gallery: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('carrion-gallery', 'west', 'the-crawlway', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('carrion-gallery', 'south', 'the-bone-sift', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-crawlway', 'door', 'The Crawlway', 'A low run between the bored passage and the carrion gallery, too low to stand in, floored with bone-grit ground fine. You can smell the gallery long before you see it, and the air is warm in the way a den is warm.', 0, 0, 'deep', 0, -1, 52);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-crawlway', 'east', 'carrion-gallery', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-crawlway', 'north', 'the-bored-passage', NULL);

-- the-undertow: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-undertow', 'west', 'the-drag', NULL);

-- the-lightless-march: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lightless-march', 'south', 'the-drag', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-drag', 'door', 'The Drag', 'The floor slopes toward the undertow, and something has been dragged down it so often that it has worn a channel in the stone, shallow and smooth and the width of a body. It runs one way. Nothing has been dragged back up.', 0, 0, 'deep', 0, 0, 51);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drag', 'east', 'the-undertow', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drag', 'north', 'the-lightless-march', NULL);

-- the-gasping-dark: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-gasping-dark', 'west', 'the-bone-sift', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-bone-sift', 'door', 'The Bone-Sift', 'The carrion gallery''s midden drains down into this low room through a grate, and the fall sorts what comes through: the fine stuff in drifts along the walls, the heavy stuff in the middle, and teeth everywhere, like gravel. The air is dry and smells of old broth.', 0, 0, 'deep', 0, 0, 53);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bone-sift', 'north', 'carrion-gallery', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bone-sift', 'east', 'the-gasping-dark', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bone-sift', 'south', 'the-scavengers-shelf', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-scavengers-shelf', 'door', 'The Scavengers'' Shelf', 'A shelf of rock above the sift, reached by a scramble, where something has been bringing the best of the fall to eat in peace. The floor is a litter of cracked long-bones, every one split lengthways and licked clean.', 0, 0, 'deep', 0, 0, 54);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-scavengers-shelf', 'north', 'the-bone-sift', NULL);

-- the-sump: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-sump', 'east', 'the-root-shaft', NULL);

-- root-vault: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('root-vault', 'down', 'the-root-shaft', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-root-shaft', 'door', 'The Root-Shaft', 'The roots that split the vault above go on down through its floor, and here they hang in a shaft like the ropes of a bell-tower, thick and grey and long dead. They will take a climber''s weight. They are the only reason anybody comes this way.', 0, 0, 'deep', 0, 2, 52);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-root-shaft', 'west', 'the-sump', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-root-shaft', 'up', 'root-vault', NULL);

-- the-marrow-road: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-marrow-road', 'down', 'the-choir-stair', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-choir-stair', 'door', 'The Choir Stair', 'The marrow road does not end here; it goes down, a stair of knucklebones set on edge like cobbles, each step worn to a dish in the middle. From below comes a sound, faint and steady, that you will spend the next few rooms trying to believe is wind.', 0, 0, 'deep', 0, 3, 54);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-choir-stair', 'up', 'the-marrow-road', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-choir-stair', 'south', 'the-singing-gallery', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-singing-gallery', 'door', 'The Singing Gallery', 'A long gallery walled in skulls laid jaw-out, thousands of them, and every jaw propped open with a sliver of bone. When the draught moves through the room it moves through all of them at once. The note is low and it does not stop. It is not wind.', 0, 0, 'deep', 0, 3, 55);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-singing-gallery', 'north', 'the-choir-stair', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-singing-gallery', 'west', 'the-lectern-room', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-singing-gallery', 'south', 'the-choir-floor', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-lectern-room', 'door', 'The Lectern Room', 'A bronze lectern green with age stands in the middle of the floor, holding a book whose pages are cut from something thinner than vellum. The marks on them are not writing: they are rows of lengths and depths, how long and how low. A hymnal, for voices that no longer need breath.', 0, 0, 'deep', 0, 2, 55);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lectern-room', 'east', 'the-singing-gallery', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lectern-room', 'south', 'the-bone-organ', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-bone-organ', 'door', 'The Bone Organ', 'One wall of this room is an instrument: long-bones of every length, bored and fitted rank on rank into a frame of ribs, the longest thicker than a man. The bellows rotted away long ago. Something still presses its keys now and then, and the room answers with a note you feel in your teeth.', 0, 0, 'deep', 0, 2, 56);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bone-organ', 'north', 'the-lectern-room', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bone-organ', 'south', 'the-silt-fall', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-silt-fall', 'door', 'The Silt-Fall', 'The silted stair spills out into this room through a gap in the ceiling, a long frozen slump of black silt stepped where feet have gone up and down it. Beneath it the bones of the floor are furred grey. The choir''s hum comes through the walls muffled here, like a song heard under water.', 0, 0, 'deep', 0, 2, 57);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-silt-fall', 'north', 'the-bone-organ', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-silt-fall', 'east', 'the-bone-font', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-choir-floor', 'door', 'The Choir Floor', 'The heart of the choir: two banks of stone stalls facing each other across a floor of polished bone, empty and ranked and waiting. Every seat is worn to the shape of whoever sat in it. The air hums very slightly, with something that stopped a moment before you came in.', 0, 0, 'deep', 0, 3, 56);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-choir-floor', 'north', 'the-singing-gallery', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-choir-floor', 'south', 'the-bone-font', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-bone-font', 'door', 'The Bone Font', 'A font carved from a single great skull, too big to have belonged to anything you would want to meet, set on a pedestal of stacked vertebrae. It is full to the brim with water that is perfectly clear and perfectly still. Nothing has drunk from it. Nothing has dared.', 0, 0, 'deep', 0, 3, 57);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bone-font', 'west', 'the-silt-fall', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bone-font', 'north', 'the-choir-floor', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bone-font', 'east', 'the-long-pews', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bone-font', 'south', 'the-marrow-seat', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-long-pews', 'door', 'The Long Pews', 'Row on row of bone benches run off into the dark, every one facing the same blank wall. The congregation is still here, after a fashion: a finger-bone on this seat, a jaw on that one, set down carefully, as if keeping a place for someone who stepped out.', 0, 0, 'deep', 0, 4, 57);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-long-pews', 'west', 'the-bone-font', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-long-pews', 'north', 'the-held-note', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-held-note', 'door', 'The Held Note', 'A round chamber shaped so that a sound made in it never ends. Your step comes back to you, and back again, and is still coming back when you take the next. Stand still and the room goes on with whatever was last sung in it, very faint, the same note, for ever.', 0, 0, 'deep', 0, 4, 56);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-held-note', 'south', 'the-long-pews', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-held-note', 'north', 'the-cantors-cells', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-held-note', 'east', 'the-cantors-door', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-cantors-cells', 'door', 'The Cantors'' Cells', 'A row of cells too small to lie down in, each with a stone seat facing the wall and a hollow worn into the wall at the height of a mouth. They practised here, alone, face to the stone, for a very long time. Some of the hollows go right through.', 0, 0, 'deep', 0, 4, 55);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cantors-cells', 'south', 'the-held-note', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-cantors-door', 'door', 'The Cantors'' Door', 'A narrow door of black stone at the foot of the choir''s last stair, and the moment you are through it the hum stops dead, the way sound stops at the edge of a church. Below, the skull-walls of the processional begin. The cantors pass this way often. They never linger on the far side.', 0, 0, 'deep', 0, 5, 56);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cantors-door', 'west', 'the-held-note', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cantors-door', 'east', 'the-choir-drain', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-choir-drain', 'door', 'The Choir Drain', 'The death cell''s drain comes out here through a grate in the ceiling, and under it a stain runs down the wall and across the floor into a gutter. The cantors have built a low wall of skulls along the gutter, as if to keep whatever runs in it out of the choir.', 0, 0, 'deep', 0, 6, 56);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-choir-drain', 'west', 'the-cantors-door', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-choir-drain', 'up', 'the-drain-run', NULL);

-- kings-oratory: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('kings-oratory', 'south', 'the-embalming-room', NULL);

-- bone-reliquary: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('bone-reliquary', 'west', 'the-embalming-room', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('bone-reliquary', 'south', 'the-bone-vestry', NULL);

-- the-death-cell: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-death-cell', 'west', 'the-bone-vestry', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-death-cell', 'south', 'the-drain-run', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-embalming-room', 'door', 'The Embalming Room', 'Stone slabs with channels cut along their edges, jars stoppered with wax, hooks, and fine blades gone black. The King''s household was made ready here before being set out in the court to wait on him for ever. Some of the jars are still full. The wax on those is new.', 0, 0, 'deep', 0, 3, 53);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-embalming-room', 'north', 'kings-oratory', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-embalming-room', 'east', 'bone-reliquary', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-bone-vestry', 'door', 'The Bone-Vestry', 'The court''s robing room: pegs along the walls, and on the pegs, vestments stiff with age and sewn all over with small bones in patterns like scales. The cantors come up from the choir to dress here. One peg is bare, and the dust beneath it is not.', 0, 0, 'deep', 0, 4, 54);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bone-vestry', 'north', 'bone-reliquary', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-bone-vestry', 'east', 'the-death-cell', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-drain-run', 'door', 'The Drain-Run', 'The death cell''s floor slopes to a drain, and this is where the drain goes: a low culvert running down and away under the court, its floor dark and slick. Old iron grates are set across it at intervals, and every one is bent outward, from the inside.', 0, 0, 'deep', 0, 5, 55);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drain-run', 'north', 'the-death-cell', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-drain-run', 'down', 'the-choir-drain', NULL);

-- black-threshold: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('black-threshold', 'down', 'the-kings-stair', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-kings-stair', 'door', 'The King''s Stair', 'Past the threshold the cold goes down a broad stair cut for processions, every step wide enough for six abreast and every one of them empty. The walls are bare stone and unmarked: whatever waits at the bottom never needed to be announced. With each step down, the water sounds nearer.', 0, 0, 'deep', 0, 5, 53);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-kings-stair', 'up', 'black-threshold', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-kings-stair', 'down', 'the-waiting-hall', NULL);

-- sunken-throne: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('sunken-throne', 'north', 'the-waiting-hall', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-waiting-hall', 'door', 'The Waiting Hall', 'An antechamber of black stone where petitioners once stood to wait on the King''s pleasure. They are still standing: rows of figures gone to salt and silt, waist-deep in still water, every face turned toward the far door. None of them was ever called. The door in front of them stands open.', 0, 0, 'deep', 0, 6, 54);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-waiting-hall', 'up', 'the-kings-stair', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-waiting-hall', 'south', 'sunken-throne', NULL);

-- the-salt-vault: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-salt-vault', 'east', 'the-cooperage', NULL);

-- the-breathing-hall: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-breathing-hall', 'east', 'the-lung-vent', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-cooperage', 'door', 'The Cooperage', 'Where the garrison''s barrels were made and mended: staves stacked in racks, hoops rusted into rings of red lace, a bench with the drawknife still lying on it. The tide comes into this room only as far as the sill, and has left a clean line to prove it.', 0, 0, 'deep', 0, 7, 51);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cooperage', 'west', 'the-salt-vault', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cooperage', 'south', 'the-cable-walk', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-cable-walk', 'door', 'The Cable-Walk', 'A long, narrow room where the tideway''s ropes were laid, with hooks at one end and a turning-wheel at the other, and between them sixty paces of rope stretched taut and gone as hard as wood. Something has been gnawing at it, patiently, from the middle.', 0, 0, 'deep', 0, 7, 52);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cable-walk', 'north', 'the-cooperage', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-cable-walk', 'east', 'the-brine-cellar', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-brine-cellar', 'door', 'The Brine Cellar', 'Vats of brine are sunk into the floor, their lids long gone and the brine crusted over white and thick as ice. Under the crust of the largest vat something is floating. It has been pickled so well and for so long that it still has its face.', 0, 0, 'deep', 0, 8, 52);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-brine-cellar', 'west', 'the-cable-walk', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-brine-cellar', 'south', 'the-lung-vent', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-lung-vent', 'door', 'The Lung-Vent', 'A shaft in the wall where the wing''s air comes and goes. Stand in front of it and it draws on you, slow and strong, pulling at your clothes and your breath; then it lets go and breathes out cold and salt into your face. Whatever it breathes through is a long way down.', 0, 0, 'deep', 0, 8, 53);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lung-vent', 'west', 'the-breathing-hall', NULL);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-lung-vent', 'north', 'the-brine-cellar', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-marrow-seat', 'door', 'The Marrow Seat', 'Past the font the choir has built itself a throne: a high seat of fused long-bones and ribs on a dais of skulls, turned back toward the singing. The cantors made it, and they are still making it. The newest bones in it are white. Whoever wears the crown sits here while the choir sings to him, and every time, he is wound a little further into the seat.', 0, 0, 'deep', 0, 3, 58);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-marrow-seat', 'north', 'the-bone-font', NULL);

-- the-still-cradle: existing room, new doors only
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-still-cradle', 'down', 'the-gods-pool', NULL);

INSERT INTO rooms (id, zone, name, description, is_entry, is_safe, region, is_spawn, map_x, map_y) VALUES
  ('the-gods-pool', 'door', 'The God''s Pool', 'Below the bottom there is one more room, and it is nearly all water: a round black pool from wall to wall, with a rim of stone just wide enough to stand on. The water rises and falls, slow as breathing, and every time it rises it comes a little further over the rim. Something in it was a king once. It has been sitting in the water so long that it no longer knows which of them is which.', 0, 0, 'deep', 0, 10, 56);
INSERT INTO exits (room_id, dir, to_room, key_item) VALUES ('the-gods-pool', 'up', 'the-still-cradle', NULL);
